// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CloudBackup struct {
	pulumi.CustomResourceState

	// Preserve absolute paths in each backup (cannot be true when snapshot is true). Defaults to false. Immutable: excluded from cloud_backup.update's accepted fields (probed against core.get_methods), so changing this forces a new resource.
	AbsolutePaths pulumi.BoolOutput `pulumi:"absolutePaths"`
	// JSON document of provider-specific attributes. Must include "bucket" (non-empty); "folder" and other provider-specific keys (fast_list, bucket_policy_only, chunk_size, acknowledge_abuse, region, encryption, storage_class) are optional, e.g. {"bucket": "...", "folder": "backups"}.
	Attributes pulumi.StringOutput `pulumi:"attributes"`
	// Local path used to cache restic metadata. If not set, performance may degrade. Null when unset.
	CachePath pulumi.StringOutput `pulumi:"cachePath"`
	// ID of the cloud sync credentials (truenas_cloudsync_credentials) to use for each backup.
	Credentials pulumi.IntOutput `pulumi:"credentials"`
	// Name of the task to display in the UI. Defaults to an empty string.
	Description pulumi.StringOutput `pulumi:"description"`
	// Whether the task is enabled. Defaults to true.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Paths to pass to `restic backup --exclude`. Defaults to an empty list.
	Excludes pulumi.StringArrayOutput `pulumi:"excludes"`
	// Paths to pass to `restic backup --include`. Defaults to an empty list.
	Includes pulumi.StringArrayOutput `pulumi:"includes"`
	// How many of the most recent backup snapshots to keep after each backup. Must be at least 1.
	KeepLast pulumi.IntOutput `pulumi:"keepLast"`
	// Password for the restic repository (RESTIC_PASSWORD). Marked Sensitive (kept out of plan/apply output), but — unlike<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>— it IS stored in state and read back on refresh (TrueNAS returns it unmasked to an admin session). Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>instead to keep it out of state. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only alternative to password: the restic repository password read from configuration and never stored in state, and not read back on refresh. Requires password_wo_version. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	PasswordWo pulumi.StringPtrOutput `pulumi:"passwordWo"`
	// Version trigger for password_wo. Because a write-only value is absent from state, its rotation cannot be detected automatically; bump this integer to re-send a changed password_wo. Required when<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>is set.
	PasswordWoVersion pulumi.IntPtrOutput `pulumi:"passwordWoVersion"`
	// The local path to back up, beginning with /mnt or /dev/zvol. Updatable in place.
	Path pulumi.StringOutput `pulumi:"path"`
	// A Bash script to run immediately after every backup if it succeeds. Defaults to an empty string.
	PostScript pulumi.StringOutput `pulumi:"postScript"`
	// A Bash script to run immediately before every backup. Defaults to an empty string.
	PreScript pulumi.StringOutput `pulumi:"preScript"`
	// Maximum upload/download rate in KiB/s, applied to cloud_backup.sync/restore. Null (the default) means no rate limit. Must be positive when set.
	RateLimit pulumi.IntOutput `pulumi:"rateLimit"`
	// Cron schedule dictating when the task should run.
	Schedule CloudBackupScheduleOutput `pulumi:"schedule"`
	// Whether to create a temporary snapshot of the dataset before every backup. Defaults to false. Cannot be true when<span pulumi-lang-nodejs=" absolutePaths " pulumi-lang-dotnet=" AbsolutePaths " pulumi-lang-go=" absolutePaths " pulumi-lang-python=" absolute_paths " pulumi-lang-yaml=" absolutePaths " pulumi-lang-java=" absolutePaths " pulumi-lang-hcl=" absolute_paths "> absolutePaths </span>is true.
	Snapshot pulumi.BoolOutput `pulumi:"snapshot"`
	// Transfer performance profile, one of the values returned by cloud_backup.transfer_setting_choices (probed live: DEFAULT, PERFORMANCE, FAST_STORAGE). Defaults to DEFAULT.
	TransferSetting pulumi.StringOutput `pulumi:"transferSetting"`
}

// NewCloudBackup registers a new resource with the given unique name, arguments, and options.
func NewCloudBackup(ctx *pulumi.Context,
	name string, args *CloudBackupArgs, opts ...pulumi.ResourceOption) (*CloudBackup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Attributes == nil {
		return nil, errors.New("invalid value for required argument 'Attributes'")
	}
	if args.Credentials == nil {
		return nil, errors.New("invalid value for required argument 'Credentials'")
	}
	if args.KeepLast == nil {
		return nil, errors.New("invalid value for required argument 'KeepLast'")
	}
	if args.Path == nil {
		return nil, errors.New("invalid value for required argument 'Path'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	if args.PasswordWo != nil {
		args.PasswordWo = pulumi.ToSecret(args.PasswordWo).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
		"passwordWo",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CloudBackup
	err := ctx.RegisterResource("truenas:index/cloudBackup:CloudBackup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudBackup gets an existing CloudBackup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudBackup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudBackupState, opts ...pulumi.ResourceOption) (*CloudBackup, error) {
	var resource CloudBackup
	err := ctx.ReadResource("truenas:index/cloudBackup:CloudBackup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudBackup resources.
type cloudBackupState struct {
	// Preserve absolute paths in each backup (cannot be true when snapshot is true). Defaults to false. Immutable: excluded from cloud_backup.update's accepted fields (probed against core.get_methods), so changing this forces a new resource.
	AbsolutePaths *bool `pulumi:"absolutePaths"`
	// JSON document of provider-specific attributes. Must include "bucket" (non-empty); "folder" and other provider-specific keys (fast_list, bucket_policy_only, chunk_size, acknowledge_abuse, region, encryption, storage_class) are optional, e.g. {"bucket": "...", "folder": "backups"}.
	Attributes *string `pulumi:"attributes"`
	// Local path used to cache restic metadata. If not set, performance may degrade. Null when unset.
	CachePath *string `pulumi:"cachePath"`
	// ID of the cloud sync credentials (truenas_cloudsync_credentials) to use for each backup.
	Credentials *int `pulumi:"credentials"`
	// Name of the task to display in the UI. Defaults to an empty string.
	Description *string `pulumi:"description"`
	// Whether the task is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// Paths to pass to `restic backup --exclude`. Defaults to an empty list.
	Excludes []string `pulumi:"excludes"`
	// Paths to pass to `restic backup --include`. Defaults to an empty list.
	Includes []string `pulumi:"includes"`
	// How many of the most recent backup snapshots to keep after each backup. Must be at least 1.
	KeepLast *int `pulumi:"keepLast"`
	// Password for the restic repository (RESTIC_PASSWORD). Marked Sensitive (kept out of plan/apply output), but — unlike<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>— it IS stored in state and read back on refresh (TrueNAS returns it unmasked to an admin session). Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>instead to keep it out of state. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only alternative to password: the restic repository password read from configuration and never stored in state, and not read back on refresh. Requires password_wo_version. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version trigger for password_wo. Because a write-only value is absent from state, its rotation cannot be detected automatically; bump this integer to re-send a changed password_wo. Required when<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>is set.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
	// The local path to back up, beginning with /mnt or /dev/zvol. Updatable in place.
	Path *string `pulumi:"path"`
	// A Bash script to run immediately after every backup if it succeeds. Defaults to an empty string.
	PostScript *string `pulumi:"postScript"`
	// A Bash script to run immediately before every backup. Defaults to an empty string.
	PreScript *string `pulumi:"preScript"`
	// Maximum upload/download rate in KiB/s, applied to cloud_backup.sync/restore. Null (the default) means no rate limit. Must be positive when set.
	RateLimit *int `pulumi:"rateLimit"`
	// Cron schedule dictating when the task should run.
	Schedule *CloudBackupSchedule `pulumi:"schedule"`
	// Whether to create a temporary snapshot of the dataset before every backup. Defaults to false. Cannot be true when<span pulumi-lang-nodejs=" absolutePaths " pulumi-lang-dotnet=" AbsolutePaths " pulumi-lang-go=" absolutePaths " pulumi-lang-python=" absolute_paths " pulumi-lang-yaml=" absolutePaths " pulumi-lang-java=" absolutePaths " pulumi-lang-hcl=" absolute_paths "> absolutePaths </span>is true.
	Snapshot *bool `pulumi:"snapshot"`
	// Transfer performance profile, one of the values returned by cloud_backup.transfer_setting_choices (probed live: DEFAULT, PERFORMANCE, FAST_STORAGE). Defaults to DEFAULT.
	TransferSetting *string `pulumi:"transferSetting"`
}

type CloudBackupState struct {
	// Preserve absolute paths in each backup (cannot be true when snapshot is true). Defaults to false. Immutable: excluded from cloud_backup.update's accepted fields (probed against core.get_methods), so changing this forces a new resource.
	AbsolutePaths pulumi.BoolPtrInput
	// JSON document of provider-specific attributes. Must include "bucket" (non-empty); "folder" and other provider-specific keys (fast_list, bucket_policy_only, chunk_size, acknowledge_abuse, region, encryption, storage_class) are optional, e.g. {"bucket": "...", "folder": "backups"}.
	Attributes pulumi.StringPtrInput
	// Local path used to cache restic metadata. If not set, performance may degrade. Null when unset.
	CachePath pulumi.StringPtrInput
	// ID of the cloud sync credentials (truenas_cloudsync_credentials) to use for each backup.
	Credentials pulumi.IntPtrInput
	// Name of the task to display in the UI. Defaults to an empty string.
	Description pulumi.StringPtrInput
	// Whether the task is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// Paths to pass to `restic backup --exclude`. Defaults to an empty list.
	Excludes pulumi.StringArrayInput
	// Paths to pass to `restic backup --include`. Defaults to an empty list.
	Includes pulumi.StringArrayInput
	// How many of the most recent backup snapshots to keep after each backup. Must be at least 1.
	KeepLast pulumi.IntPtrInput
	// Password for the restic repository (RESTIC_PASSWORD). Marked Sensitive (kept out of plan/apply output), but — unlike<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>— it IS stored in state and read back on refresh (TrueNAS returns it unmasked to an admin session). Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>instead to keep it out of state. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only alternative to password: the restic repository password read from configuration and never stored in state, and not read back on refresh. Requires password_wo_version. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	PasswordWo pulumi.StringPtrInput
	// Version trigger for password_wo. Because a write-only value is absent from state, its rotation cannot be detected automatically; bump this integer to re-send a changed password_wo. Required when<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>is set.
	PasswordWoVersion pulumi.IntPtrInput
	// The local path to back up, beginning with /mnt or /dev/zvol. Updatable in place.
	Path pulumi.StringPtrInput
	// A Bash script to run immediately after every backup if it succeeds. Defaults to an empty string.
	PostScript pulumi.StringPtrInput
	// A Bash script to run immediately before every backup. Defaults to an empty string.
	PreScript pulumi.StringPtrInput
	// Maximum upload/download rate in KiB/s, applied to cloud_backup.sync/restore. Null (the default) means no rate limit. Must be positive when set.
	RateLimit pulumi.IntPtrInput
	// Cron schedule dictating when the task should run.
	Schedule CloudBackupSchedulePtrInput
	// Whether to create a temporary snapshot of the dataset before every backup. Defaults to false. Cannot be true when<span pulumi-lang-nodejs=" absolutePaths " pulumi-lang-dotnet=" AbsolutePaths " pulumi-lang-go=" absolutePaths " pulumi-lang-python=" absolute_paths " pulumi-lang-yaml=" absolutePaths " pulumi-lang-java=" absolutePaths " pulumi-lang-hcl=" absolute_paths "> absolutePaths </span>is true.
	Snapshot pulumi.BoolPtrInput
	// Transfer performance profile, one of the values returned by cloud_backup.transfer_setting_choices (probed live: DEFAULT, PERFORMANCE, FAST_STORAGE). Defaults to DEFAULT.
	TransferSetting pulumi.StringPtrInput
}

func (CloudBackupState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudBackupState)(nil)).Elem()
}

type cloudBackupArgs struct {
	// Preserve absolute paths in each backup (cannot be true when snapshot is true). Defaults to false. Immutable: excluded from cloud_backup.update's accepted fields (probed against core.get_methods), so changing this forces a new resource.
	AbsolutePaths *bool `pulumi:"absolutePaths"`
	// JSON document of provider-specific attributes. Must include "bucket" (non-empty); "folder" and other provider-specific keys (fast_list, bucket_policy_only, chunk_size, acknowledge_abuse, region, encryption, storage_class) are optional, e.g. {"bucket": "...", "folder": "backups"}.
	Attributes string `pulumi:"attributes"`
	// Local path used to cache restic metadata. If not set, performance may degrade. Null when unset.
	CachePath *string `pulumi:"cachePath"`
	// ID of the cloud sync credentials (truenas_cloudsync_credentials) to use for each backup.
	Credentials int `pulumi:"credentials"`
	// Name of the task to display in the UI. Defaults to an empty string.
	Description *string `pulumi:"description"`
	// Whether the task is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// Paths to pass to `restic backup --exclude`. Defaults to an empty list.
	Excludes []string `pulumi:"excludes"`
	// Paths to pass to `restic backup --include`. Defaults to an empty list.
	Includes []string `pulumi:"includes"`
	// How many of the most recent backup snapshots to keep after each backup. Must be at least 1.
	KeepLast int `pulumi:"keepLast"`
	// Password for the restic repository (RESTIC_PASSWORD). Marked Sensitive (kept out of plan/apply output), but — unlike<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>— it IS stored in state and read back on refresh (TrueNAS returns it unmasked to an admin session). Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>instead to keep it out of state. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	Password *string `pulumi:"password"`
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only alternative to password: the restic repository password read from configuration and never stored in state, and not read back on refresh. Requires password_wo_version. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	PasswordWo *string `pulumi:"passwordWo"`
	// Version trigger for password_wo. Because a write-only value is absent from state, its rotation cannot be detected automatically; bump this integer to re-send a changed password_wo. Required when<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>is set.
	PasswordWoVersion *int `pulumi:"passwordWoVersion"`
	// The local path to back up, beginning with /mnt or /dev/zvol. Updatable in place.
	Path string `pulumi:"path"`
	// A Bash script to run immediately after every backup if it succeeds. Defaults to an empty string.
	PostScript *string `pulumi:"postScript"`
	// A Bash script to run immediately before every backup. Defaults to an empty string.
	PreScript *string `pulumi:"preScript"`
	// Maximum upload/download rate in KiB/s, applied to cloud_backup.sync/restore. Null (the default) means no rate limit. Must be positive when set.
	RateLimit *int `pulumi:"rateLimit"`
	// Cron schedule dictating when the task should run.
	Schedule *CloudBackupSchedule `pulumi:"schedule"`
	// Whether to create a temporary snapshot of the dataset before every backup. Defaults to false. Cannot be true when<span pulumi-lang-nodejs=" absolutePaths " pulumi-lang-dotnet=" AbsolutePaths " pulumi-lang-go=" absolutePaths " pulumi-lang-python=" absolute_paths " pulumi-lang-yaml=" absolutePaths " pulumi-lang-java=" absolutePaths " pulumi-lang-hcl=" absolute_paths "> absolutePaths </span>is true.
	Snapshot *bool `pulumi:"snapshot"`
	// Transfer performance profile, one of the values returned by cloud_backup.transfer_setting_choices (probed live: DEFAULT, PERFORMANCE, FAST_STORAGE). Defaults to DEFAULT.
	TransferSetting *string `pulumi:"transferSetting"`
}

// The set of arguments for constructing a CloudBackup resource.
type CloudBackupArgs struct {
	// Preserve absolute paths in each backup (cannot be true when snapshot is true). Defaults to false. Immutable: excluded from cloud_backup.update's accepted fields (probed against core.get_methods), so changing this forces a new resource.
	AbsolutePaths pulumi.BoolPtrInput
	// JSON document of provider-specific attributes. Must include "bucket" (non-empty); "folder" and other provider-specific keys (fast_list, bucket_policy_only, chunk_size, acknowledge_abuse, region, encryption, storage_class) are optional, e.g. {"bucket": "...", "folder": "backups"}.
	Attributes pulumi.StringInput
	// Local path used to cache restic metadata. If not set, performance may degrade. Null when unset.
	CachePath pulumi.StringPtrInput
	// ID of the cloud sync credentials (truenas_cloudsync_credentials) to use for each backup.
	Credentials pulumi.IntInput
	// Name of the task to display in the UI. Defaults to an empty string.
	Description pulumi.StringPtrInput
	// Whether the task is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// Paths to pass to `restic backup --exclude`. Defaults to an empty list.
	Excludes pulumi.StringArrayInput
	// Paths to pass to `restic backup --include`. Defaults to an empty list.
	Includes pulumi.StringArrayInput
	// How many of the most recent backup snapshots to keep after each backup. Must be at least 1.
	KeepLast pulumi.IntInput
	// Password for the restic repository (RESTIC_PASSWORD). Marked Sensitive (kept out of plan/apply output), but — unlike<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>— it IS stored in state and read back on refresh (TrueNAS returns it unmasked to an admin session). Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>instead to keep it out of state. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	Password pulumi.StringPtrInput
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Write-only alternative to password: the restic repository password read from configuration and never stored in state, and not read back on refresh. Requires password_wo_version. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
	PasswordWo pulumi.StringPtrInput
	// Version trigger for password_wo. Because a write-only value is absent from state, its rotation cannot be detected automatically; bump this integer to re-send a changed password_wo. Required when<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>is set.
	PasswordWoVersion pulumi.IntPtrInput
	// The local path to back up, beginning with /mnt or /dev/zvol. Updatable in place.
	Path pulumi.StringInput
	// A Bash script to run immediately after every backup if it succeeds. Defaults to an empty string.
	PostScript pulumi.StringPtrInput
	// A Bash script to run immediately before every backup. Defaults to an empty string.
	PreScript pulumi.StringPtrInput
	// Maximum upload/download rate in KiB/s, applied to cloud_backup.sync/restore. Null (the default) means no rate limit. Must be positive when set.
	RateLimit pulumi.IntPtrInput
	// Cron schedule dictating when the task should run.
	Schedule CloudBackupSchedulePtrInput
	// Whether to create a temporary snapshot of the dataset before every backup. Defaults to false. Cannot be true when<span pulumi-lang-nodejs=" absolutePaths " pulumi-lang-dotnet=" AbsolutePaths " pulumi-lang-go=" absolutePaths " pulumi-lang-python=" absolute_paths " pulumi-lang-yaml=" absolutePaths " pulumi-lang-java=" absolutePaths " pulumi-lang-hcl=" absolute_paths "> absolutePaths </span>is true.
	Snapshot pulumi.BoolPtrInput
	// Transfer performance profile, one of the values returned by cloud_backup.transfer_setting_choices (probed live: DEFAULT, PERFORMANCE, FAST_STORAGE). Defaults to DEFAULT.
	TransferSetting pulumi.StringPtrInput
}

func (CloudBackupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudBackupArgs)(nil)).Elem()
}

type CloudBackupInput interface {
	pulumi.Input

	ToCloudBackupOutput() CloudBackupOutput
	ToCloudBackupOutputWithContext(ctx context.Context) CloudBackupOutput
}

func (*CloudBackup) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudBackup)(nil)).Elem()
}

func (i *CloudBackup) ToCloudBackupOutput() CloudBackupOutput {
	return i.ToCloudBackupOutputWithContext(context.Background())
}

func (i *CloudBackup) ToCloudBackupOutputWithContext(ctx context.Context) CloudBackupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudBackupOutput)
}

// CloudBackupArrayInput is an input type that accepts CloudBackupArray and CloudBackupArrayOutput values.
// You can construct a concrete instance of `CloudBackupArrayInput` via:
//
//	CloudBackupArray{ CloudBackupArgs{...} }
type CloudBackupArrayInput interface {
	pulumi.Input

	ToCloudBackupArrayOutput() CloudBackupArrayOutput
	ToCloudBackupArrayOutputWithContext(context.Context) CloudBackupArrayOutput
}

type CloudBackupArray []CloudBackupInput

func (CloudBackupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudBackup)(nil)).Elem()
}

func (i CloudBackupArray) ToCloudBackupArrayOutput() CloudBackupArrayOutput {
	return i.ToCloudBackupArrayOutputWithContext(context.Background())
}

func (i CloudBackupArray) ToCloudBackupArrayOutputWithContext(ctx context.Context) CloudBackupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudBackupArrayOutput)
}

// CloudBackupMapInput is an input type that accepts CloudBackupMap and CloudBackupMapOutput values.
// You can construct a concrete instance of `CloudBackupMapInput` via:
//
//	CloudBackupMap{ "key": CloudBackupArgs{...} }
type CloudBackupMapInput interface {
	pulumi.Input

	ToCloudBackupMapOutput() CloudBackupMapOutput
	ToCloudBackupMapOutputWithContext(context.Context) CloudBackupMapOutput
}

type CloudBackupMap map[string]CloudBackupInput

func (CloudBackupMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudBackup)(nil)).Elem()
}

func (i CloudBackupMap) ToCloudBackupMapOutput() CloudBackupMapOutput {
	return i.ToCloudBackupMapOutputWithContext(context.Background())
}

func (i CloudBackupMap) ToCloudBackupMapOutputWithContext(ctx context.Context) CloudBackupMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudBackupMapOutput)
}

type CloudBackupOutput struct{ *pulumi.OutputState }

func (CloudBackupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudBackup)(nil)).Elem()
}

func (o CloudBackupOutput) ToCloudBackupOutput() CloudBackupOutput {
	return o
}

func (o CloudBackupOutput) ToCloudBackupOutputWithContext(ctx context.Context) CloudBackupOutput {
	return o
}

// Preserve absolute paths in each backup (cannot be true when snapshot is true). Defaults to false. Immutable: excluded from cloud_backup.update's accepted fields (probed against core.get_methods), so changing this forces a new resource.
func (o CloudBackupOutput) AbsolutePaths() pulumi.BoolOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.BoolOutput { return v.AbsolutePaths }).(pulumi.BoolOutput)
}

// JSON document of provider-specific attributes. Must include "bucket" (non-empty); "folder" and other provider-specific keys (fast_list, bucket_policy_only, chunk_size, acknowledge_abuse, region, encryption, storage_class) are optional, e.g. {"bucket": "...", "folder": "backups"}.
func (o CloudBackupOutput) Attributes() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringOutput { return v.Attributes }).(pulumi.StringOutput)
}

// Local path used to cache restic metadata. If not set, performance may degrade. Null when unset.
func (o CloudBackupOutput) CachePath() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringOutput { return v.CachePath }).(pulumi.StringOutput)
}

// ID of the cloud sync credentials (truenas_cloudsync_credentials) to use for each backup.
func (o CloudBackupOutput) Credentials() pulumi.IntOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.IntOutput { return v.Credentials }).(pulumi.IntOutput)
}

// Name of the task to display in the UI. Defaults to an empty string.
func (o CloudBackupOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Whether the task is enabled. Defaults to true.
func (o CloudBackupOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Paths to pass to `restic backup --exclude`. Defaults to an empty list.
func (o CloudBackupOutput) Excludes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringArrayOutput { return v.Excludes }).(pulumi.StringArrayOutput)
}

// Paths to pass to `restic backup --include`. Defaults to an empty list.
func (o CloudBackupOutput) Includes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringArrayOutput { return v.Includes }).(pulumi.StringArrayOutput)
}

// How many of the most recent backup snapshots to keep after each backup. Must be at least 1.
func (o CloudBackupOutput) KeepLast() pulumi.IntOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.IntOutput { return v.KeepLast }).(pulumi.IntOutput)
}

// Password for the restic repository (RESTIC_PASSWORD). Marked Sensitive (kept out of plan/apply output), but — unlike<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>— it IS stored in state and read back on refresh (TrueNAS returns it unmasked to an admin session). Use<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>instead to keep it out of state. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
func (o CloudBackupOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
//
// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Write-only alternative to password: the restic repository password read from configuration and never stored in state, and not read back on refresh. Requires password_wo_version. Exactly one of password or<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>must be set.
func (o CloudBackupOutput) PasswordWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringPtrOutput { return v.PasswordWo }).(pulumi.StringPtrOutput)
}

// Version trigger for password_wo. Because a write-only value is absent from state, its rotation cannot be detected automatically; bump this integer to re-send a changed password_wo. Required when<span pulumi-lang-nodejs=" passwordWo " pulumi-lang-dotnet=" PasswordWo " pulumi-lang-go=" passwordWo " pulumi-lang-python=" password_wo " pulumi-lang-yaml=" passwordWo " pulumi-lang-java=" passwordWo " pulumi-lang-hcl=" password_wo "> passwordWo </span>is set.
func (o CloudBackupOutput) PasswordWoVersion() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.IntPtrOutput { return v.PasswordWoVersion }).(pulumi.IntPtrOutput)
}

// The local path to back up, beginning with /mnt or /dev/zvol. Updatable in place.
func (o CloudBackupOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

// A Bash script to run immediately after every backup if it succeeds. Defaults to an empty string.
func (o CloudBackupOutput) PostScript() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringOutput { return v.PostScript }).(pulumi.StringOutput)
}

// A Bash script to run immediately before every backup. Defaults to an empty string.
func (o CloudBackupOutput) PreScript() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringOutput { return v.PreScript }).(pulumi.StringOutput)
}

// Maximum upload/download rate in KiB/s, applied to cloud_backup.sync/restore. Null (the default) means no rate limit. Must be positive when set.
func (o CloudBackupOutput) RateLimit() pulumi.IntOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.IntOutput { return v.RateLimit }).(pulumi.IntOutput)
}

// Cron schedule dictating when the task should run.
func (o CloudBackupOutput) Schedule() CloudBackupScheduleOutput {
	return o.ApplyT(func(v *CloudBackup) CloudBackupScheduleOutput { return v.Schedule }).(CloudBackupScheduleOutput)
}

// Whether to create a temporary snapshot of the dataset before every backup. Defaults to false. Cannot be true when<span pulumi-lang-nodejs=" absolutePaths " pulumi-lang-dotnet=" AbsolutePaths " pulumi-lang-go=" absolutePaths " pulumi-lang-python=" absolute_paths " pulumi-lang-yaml=" absolutePaths " pulumi-lang-java=" absolutePaths " pulumi-lang-hcl=" absolute_paths "> absolutePaths </span>is true.
func (o CloudBackupOutput) Snapshot() pulumi.BoolOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.BoolOutput { return v.Snapshot }).(pulumi.BoolOutput)
}

// Transfer performance profile, one of the values returned by cloud_backup.transfer_setting_choices (probed live: DEFAULT, PERFORMANCE, FAST_STORAGE). Defaults to DEFAULT.
func (o CloudBackupOutput) TransferSetting() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudBackup) pulumi.StringOutput { return v.TransferSetting }).(pulumi.StringOutput)
}

type CloudBackupArrayOutput struct{ *pulumi.OutputState }

func (CloudBackupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudBackup)(nil)).Elem()
}

func (o CloudBackupArrayOutput) ToCloudBackupArrayOutput() CloudBackupArrayOutput {
	return o
}

func (o CloudBackupArrayOutput) ToCloudBackupArrayOutputWithContext(ctx context.Context) CloudBackupArrayOutput {
	return o
}

func (o CloudBackupArrayOutput) Index(i pulumi.IntInput) CloudBackupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CloudBackup {
		return vs[0].([]*CloudBackup)[vs[1].(int)]
	}).(CloudBackupOutput)
}

type CloudBackupMapOutput struct{ *pulumi.OutputState }

func (CloudBackupMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudBackup)(nil)).Elem()
}

func (o CloudBackupMapOutput) ToCloudBackupMapOutput() CloudBackupMapOutput {
	return o
}

func (o CloudBackupMapOutput) ToCloudBackupMapOutputWithContext(ctx context.Context) CloudBackupMapOutput {
	return o
}

func (o CloudBackupMapOutput) MapIndex(k pulumi.StringInput) CloudBackupOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CloudBackup {
		return vs[0].(map[string]*CloudBackup)[vs[1].(string)]
	}).(CloudBackupOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudBackupInput)(nil)).Elem(), &CloudBackup{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudBackupArrayInput)(nil)).Elem(), CloudBackupArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudBackupMapInput)(nil)).Elem(), CloudBackupMap{})
	pulumi.RegisterOutputType(CloudBackupOutput{})
	pulumi.RegisterOutputType(CloudBackupArrayOutput{})
	pulumi.RegisterOutputType(CloudBackupMapOutput{})
}
