// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CloudsyncCredentials struct {
	pulumi.CustomResourceState

	// Name of the cloud sync credentials.
	Name pulumi.StringOutput `pulumi:"name"`
	// JSON document of provider settings. Must include "type" (e.g. S3, B2, GOOGLE_CLOUD_STORAGE, STORJ_IX).
	ProviderConfig pulumi.StringOutput `pulumi:"providerConfig"`
}

// NewCloudsyncCredentials registers a new resource with the given unique name, arguments, and options.
func NewCloudsyncCredentials(ctx *pulumi.Context,
	name string, args *CloudsyncCredentialsArgs, opts ...pulumi.ResourceOption) (*CloudsyncCredentials, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.ProviderConfig == nil {
		return nil, errors.New("invalid value for required argument 'ProviderConfig'")
	}
	if args.ProviderConfig != nil {
		args.ProviderConfig = pulumi.ToSecret(args.ProviderConfig).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"providerConfig",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CloudsyncCredentials
	err := ctx.RegisterResource("truenas:index/cloudsyncCredentials:CloudsyncCredentials", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudsyncCredentials gets an existing CloudsyncCredentials resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudsyncCredentials(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudsyncCredentialsState, opts ...pulumi.ResourceOption) (*CloudsyncCredentials, error) {
	var resource CloudsyncCredentials
	err := ctx.ReadResource("truenas:index/cloudsyncCredentials:CloudsyncCredentials", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudsyncCredentials resources.
type cloudsyncCredentialsState struct {
	// Name of the cloud sync credentials.
	Name *string `pulumi:"name"`
	// JSON document of provider settings. Must include "type" (e.g. S3, B2, GOOGLE_CLOUD_STORAGE, STORJ_IX).
	ProviderConfig *string `pulumi:"providerConfig"`
}

type CloudsyncCredentialsState struct {
	// Name of the cloud sync credentials.
	Name pulumi.StringPtrInput
	// JSON document of provider settings. Must include "type" (e.g. S3, B2, GOOGLE_CLOUD_STORAGE, STORJ_IX).
	ProviderConfig pulumi.StringPtrInput
}

func (CloudsyncCredentialsState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudsyncCredentialsState)(nil)).Elem()
}

type cloudsyncCredentialsArgs struct {
	// Name of the cloud sync credentials.
	Name string `pulumi:"name"`
	// JSON document of provider settings. Must include "type" (e.g. S3, B2, GOOGLE_CLOUD_STORAGE, STORJ_IX).
	ProviderConfig string `pulumi:"providerConfig"`
}

// The set of arguments for constructing a CloudsyncCredentials resource.
type CloudsyncCredentialsArgs struct {
	// Name of the cloud sync credentials.
	Name pulumi.StringInput
	// JSON document of provider settings. Must include "type" (e.g. S3, B2, GOOGLE_CLOUD_STORAGE, STORJ_IX).
	ProviderConfig pulumi.StringInput
}

func (CloudsyncCredentialsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudsyncCredentialsArgs)(nil)).Elem()
}

type CloudsyncCredentialsInput interface {
	pulumi.Input

	ToCloudsyncCredentialsOutput() CloudsyncCredentialsOutput
	ToCloudsyncCredentialsOutputWithContext(ctx context.Context) CloudsyncCredentialsOutput
}

func (*CloudsyncCredentials) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudsyncCredentials)(nil)).Elem()
}

func (i *CloudsyncCredentials) ToCloudsyncCredentialsOutput() CloudsyncCredentialsOutput {
	return i.ToCloudsyncCredentialsOutputWithContext(context.Background())
}

func (i *CloudsyncCredentials) ToCloudsyncCredentialsOutputWithContext(ctx context.Context) CloudsyncCredentialsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudsyncCredentialsOutput)
}

// CloudsyncCredentialsArrayInput is an input type that accepts CloudsyncCredentialsArray and CloudsyncCredentialsArrayOutput values.
// You can construct a concrete instance of `CloudsyncCredentialsArrayInput` via:
//
//	CloudsyncCredentialsArray{ CloudsyncCredentialsArgs{...} }
type CloudsyncCredentialsArrayInput interface {
	pulumi.Input

	ToCloudsyncCredentialsArrayOutput() CloudsyncCredentialsArrayOutput
	ToCloudsyncCredentialsArrayOutputWithContext(context.Context) CloudsyncCredentialsArrayOutput
}

type CloudsyncCredentialsArray []CloudsyncCredentialsInput

func (CloudsyncCredentialsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudsyncCredentials)(nil)).Elem()
}

func (i CloudsyncCredentialsArray) ToCloudsyncCredentialsArrayOutput() CloudsyncCredentialsArrayOutput {
	return i.ToCloudsyncCredentialsArrayOutputWithContext(context.Background())
}

func (i CloudsyncCredentialsArray) ToCloudsyncCredentialsArrayOutputWithContext(ctx context.Context) CloudsyncCredentialsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudsyncCredentialsArrayOutput)
}

// CloudsyncCredentialsMapInput is an input type that accepts CloudsyncCredentialsMap and CloudsyncCredentialsMapOutput values.
// You can construct a concrete instance of `CloudsyncCredentialsMapInput` via:
//
//	CloudsyncCredentialsMap{ "key": CloudsyncCredentialsArgs{...} }
type CloudsyncCredentialsMapInput interface {
	pulumi.Input

	ToCloudsyncCredentialsMapOutput() CloudsyncCredentialsMapOutput
	ToCloudsyncCredentialsMapOutputWithContext(context.Context) CloudsyncCredentialsMapOutput
}

type CloudsyncCredentialsMap map[string]CloudsyncCredentialsInput

func (CloudsyncCredentialsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudsyncCredentials)(nil)).Elem()
}

func (i CloudsyncCredentialsMap) ToCloudsyncCredentialsMapOutput() CloudsyncCredentialsMapOutput {
	return i.ToCloudsyncCredentialsMapOutputWithContext(context.Background())
}

func (i CloudsyncCredentialsMap) ToCloudsyncCredentialsMapOutputWithContext(ctx context.Context) CloudsyncCredentialsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudsyncCredentialsMapOutput)
}

type CloudsyncCredentialsOutput struct{ *pulumi.OutputState }

func (CloudsyncCredentialsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudsyncCredentials)(nil)).Elem()
}

func (o CloudsyncCredentialsOutput) ToCloudsyncCredentialsOutput() CloudsyncCredentialsOutput {
	return o
}

func (o CloudsyncCredentialsOutput) ToCloudsyncCredentialsOutputWithContext(ctx context.Context) CloudsyncCredentialsOutput {
	return o
}

// Name of the cloud sync credentials.
func (o CloudsyncCredentialsOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudsyncCredentials) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// JSON document of provider settings. Must include "type" (e.g. S3, B2, GOOGLE_CLOUD_STORAGE, STORJ_IX).
func (o CloudsyncCredentialsOutput) ProviderConfig() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudsyncCredentials) pulumi.StringOutput { return v.ProviderConfig }).(pulumi.StringOutput)
}

type CloudsyncCredentialsArrayOutput struct{ *pulumi.OutputState }

func (CloudsyncCredentialsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudsyncCredentials)(nil)).Elem()
}

func (o CloudsyncCredentialsArrayOutput) ToCloudsyncCredentialsArrayOutput() CloudsyncCredentialsArrayOutput {
	return o
}

func (o CloudsyncCredentialsArrayOutput) ToCloudsyncCredentialsArrayOutputWithContext(ctx context.Context) CloudsyncCredentialsArrayOutput {
	return o
}

func (o CloudsyncCredentialsArrayOutput) Index(i pulumi.IntInput) CloudsyncCredentialsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CloudsyncCredentials {
		return vs[0].([]*CloudsyncCredentials)[vs[1].(int)]
	}).(CloudsyncCredentialsOutput)
}

type CloudsyncCredentialsMapOutput struct{ *pulumi.OutputState }

func (CloudsyncCredentialsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudsyncCredentials)(nil)).Elem()
}

func (o CloudsyncCredentialsMapOutput) ToCloudsyncCredentialsMapOutput() CloudsyncCredentialsMapOutput {
	return o
}

func (o CloudsyncCredentialsMapOutput) ToCloudsyncCredentialsMapOutputWithContext(ctx context.Context) CloudsyncCredentialsMapOutput {
	return o
}

func (o CloudsyncCredentialsMapOutput) MapIndex(k pulumi.StringInput) CloudsyncCredentialsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CloudsyncCredentials {
		return vs[0].(map[string]*CloudsyncCredentials)[vs[1].(string)]
	}).(CloudsyncCredentialsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudsyncCredentialsInput)(nil)).Elem(), &CloudsyncCredentials{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudsyncCredentialsArrayInput)(nil)).Elem(), CloudsyncCredentialsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudsyncCredentialsMapInput)(nil)).Elem(), CloudsyncCredentialsMap{})
	pulumi.RegisterOutputType(CloudsyncCredentialsOutput{})
	pulumi.RegisterOutputType(CloudsyncCredentialsArrayOutput{})
	pulumi.RegisterOutputType(CloudsyncCredentialsMapOutput{})
}
