// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupAlertService(ctx *pulumi.Context, args *LookupAlertServiceArgs, opts ...pulumi.InvokeOption) (*LookupAlertServiceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAlertServiceResult
	err := ctx.Invoke("truenas:index/getAlertService:getAlertService", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAlertService.
type LookupAlertServiceArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getAlertService.
type LookupAlertServiceResult struct {
	Attributes string `pulumi:"attributes"`
	Enabled    bool   `pulumi:"enabled"`
	Id         int    `pulumi:"id"`
	Level      string `pulumi:"level"`
	Name       string `pulumi:"name"`
}

func LookupAlertServiceOutput(ctx *pulumi.Context, args LookupAlertServiceOutputArgs, opts ...pulumi.InvokeOption) LookupAlertServiceResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getAlertService:getAlertService", args, LookupAlertServiceResultOutput{}, options).(LookupAlertServiceResultOutput)
}

// A collection of arguments for invoking getAlertService.
type LookupAlertServiceOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupAlertServiceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlertServiceArgs)(nil)).Elem()
}

// A collection of values returned by getAlertService.
type LookupAlertServiceResultOutput struct{ *pulumi.OutputState }

func (LookupAlertServiceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlertServiceResult)(nil)).Elem()
}

func (o LookupAlertServiceResultOutput) ToLookupAlertServiceResultOutput() LookupAlertServiceResultOutput {
	return o
}

func (o LookupAlertServiceResultOutput) ToLookupAlertServiceResultOutputWithContext(ctx context.Context) LookupAlertServiceResultOutput {
	return o
}

func (o LookupAlertServiceResultOutput) Attributes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertServiceResult) string { return v.Attributes }).(pulumi.StringOutput)
}

func (o LookupAlertServiceResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAlertServiceResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupAlertServiceResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAlertServiceResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupAlertServiceResultOutput) Level() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertServiceResult) string { return v.Level }).(pulumi.StringOutput)
}

func (o LookupAlertServiceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertServiceResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAlertServiceResultOutput{})
}
