// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupAlertPolicy(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupAlertPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAlertPolicyResult
	err := ctx.Invoke("truenas:index/getAlertPolicy:getAlertPolicy", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getAlertPolicy.
type LookupAlertPolicyResult struct {
	Classes string `pulumi:"classes"`
	Id      string `pulumi:"id"`
}

func LookupAlertPolicyOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupAlertPolicyResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getAlertPolicy:getAlertPolicy", nil, LookupAlertPolicyResultOutput{}, options).(LookupAlertPolicyResultOutput)
}

// A collection of values returned by getAlertPolicy.
type LookupAlertPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupAlertPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAlertPolicyResult)(nil)).Elem()
}

func (o LookupAlertPolicyResultOutput) ToLookupAlertPolicyResultOutput() LookupAlertPolicyResultOutput {
	return o
}

func (o LookupAlertPolicyResultOutput) ToLookupAlertPolicyResultOutputWithContext(ctx context.Context) LookupAlertPolicyResultOutput {
	return o
}

func (o LookupAlertPolicyResultOutput) Classes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertPolicyResult) string { return v.Classes }).(pulumi.StringOutput)
}

func (o LookupAlertPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAlertPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAlertPolicyResultOutput{})
}
