// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupAcmeDnsAuthenticator(ctx *pulumi.Context, args *LookupAcmeDnsAuthenticatorArgs, opts ...pulumi.InvokeOption) (*LookupAcmeDnsAuthenticatorResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAcmeDnsAuthenticatorResult
	err := ctx.Invoke("truenas:index/getAcmeDnsAuthenticator:getAcmeDnsAuthenticator", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAcmeDnsAuthenticator.
type LookupAcmeDnsAuthenticatorArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getAcmeDnsAuthenticator.
type LookupAcmeDnsAuthenticatorResult struct {
	Attributes string `pulumi:"attributes"`
	Id         int    `pulumi:"id"`
	Name       string `pulumi:"name"`
}

func LookupAcmeDnsAuthenticatorOutput(ctx *pulumi.Context, args LookupAcmeDnsAuthenticatorOutputArgs, opts ...pulumi.InvokeOption) LookupAcmeDnsAuthenticatorResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getAcmeDnsAuthenticator:getAcmeDnsAuthenticator", args, LookupAcmeDnsAuthenticatorResultOutput{}, options).(LookupAcmeDnsAuthenticatorResultOutput)
}

// A collection of arguments for invoking getAcmeDnsAuthenticator.
type LookupAcmeDnsAuthenticatorOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupAcmeDnsAuthenticatorOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAcmeDnsAuthenticatorArgs)(nil)).Elem()
}

// A collection of values returned by getAcmeDnsAuthenticator.
type LookupAcmeDnsAuthenticatorResultOutput struct{ *pulumi.OutputState }

func (LookupAcmeDnsAuthenticatorResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAcmeDnsAuthenticatorResult)(nil)).Elem()
}

func (o LookupAcmeDnsAuthenticatorResultOutput) ToLookupAcmeDnsAuthenticatorResultOutput() LookupAcmeDnsAuthenticatorResultOutput {
	return o
}

func (o LookupAcmeDnsAuthenticatorResultOutput) ToLookupAcmeDnsAuthenticatorResultOutputWithContext(ctx context.Context) LookupAcmeDnsAuthenticatorResultOutput {
	return o
}

func (o LookupAcmeDnsAuthenticatorResultOutput) Attributes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAcmeDnsAuthenticatorResult) string { return v.Attributes }).(pulumi.StringOutput)
}

func (o LookupAcmeDnsAuthenticatorResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAcmeDnsAuthenticatorResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupAcmeDnsAuthenticatorResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAcmeDnsAuthenticatorResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAcmeDnsAuthenticatorResultOutput{})
}
