// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupContainerDevice(ctx *pulumi.Context, args *LookupContainerDeviceArgs, opts ...pulumi.InvokeOption) (*LookupContainerDeviceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupContainerDeviceResult
	err := ctx.Invoke("truenas:index/getContainerDevice:getContainerDevice", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContainerDevice.
type LookupContainerDeviceArgs struct {
	Id int `pulumi:"id"`
}

// A collection of values returned by getContainerDevice.
type LookupContainerDeviceResult struct {
	Attributes string `pulumi:"attributes"`
	Container  int    `pulumi:"container"`
	Id         int    `pulumi:"id"`
}

func LookupContainerDeviceOutput(ctx *pulumi.Context, args LookupContainerDeviceOutputArgs, opts ...pulumi.InvokeOption) LookupContainerDeviceResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getContainerDevice:getContainerDevice", args, LookupContainerDeviceResultOutput{}, options).(LookupContainerDeviceResultOutput)
}

// A collection of arguments for invoking getContainerDevice.
type LookupContainerDeviceOutputArgs struct {
	Id pulumi.IntInput `pulumi:"id"`
}

func (LookupContainerDeviceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContainerDeviceArgs)(nil)).Elem()
}

// A collection of values returned by getContainerDevice.
type LookupContainerDeviceResultOutput struct{ *pulumi.OutputState }

func (LookupContainerDeviceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContainerDeviceResult)(nil)).Elem()
}

func (o LookupContainerDeviceResultOutput) ToLookupContainerDeviceResultOutput() LookupContainerDeviceResultOutput {
	return o
}

func (o LookupContainerDeviceResultOutput) ToLookupContainerDeviceResultOutputWithContext(ctx context.Context) LookupContainerDeviceResultOutput {
	return o
}

func (o LookupContainerDeviceResultOutput) Attributes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerDeviceResult) string { return v.Attributes }).(pulumi.StringOutput)
}

func (o LookupContainerDeviceResultOutput) Container() pulumi.IntOutput {
	return o.ApplyT(func(v LookupContainerDeviceResult) int { return v.Container }).(pulumi.IntOutput)
}

func (o LookupContainerDeviceResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupContainerDeviceResult) int { return v.Id }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupContainerDeviceResultOutput{})
}
