// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupContainer(ctx *pulumi.Context, args *LookupContainerArgs, opts ...pulumi.InvokeOption) (*LookupContainerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupContainerResult
	err := ctx.Invoke("truenas:index/getContainer:getContainer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContainer.
type LookupContainerArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getContainer.
type LookupContainerResult struct {
	Autostart          bool              `pulumi:"autostart"`
	CapabilitiesPolicy string            `pulumi:"capabilitiesPolicy"`
	CapabilitiesState  map[string]bool   `pulumi:"capabilitiesState"`
	Cpuset             string            `pulumi:"cpuset"`
	Dataset            string            `pulumi:"dataset"`
	DefaultNetwork     string            `pulumi:"defaultNetwork"`
	Description        string            `pulumi:"description"`
	Id                 int               `pulumi:"id"`
	Idmap              string            `pulumi:"idmap"`
	Init               string            `pulumi:"init"`
	Initdir            string            `pulumi:"initdir"`
	Initenv            map[string]string `pulumi:"initenv"`
	Initgroup          string            `pulumi:"initgroup"`
	Inituser           string            `pulumi:"inituser"`
	Name               string            `pulumi:"name"`
	Pool               string            `pulumi:"pool"`
	Running            bool              `pulumi:"running"`
	ShutdownTimeout    int               `pulumi:"shutdownTimeout"`
	Status             string            `pulumi:"status"`
	Time               string            `pulumi:"time"`
	Uuid               string            `pulumi:"uuid"`
}

func LookupContainerOutput(ctx *pulumi.Context, args LookupContainerOutputArgs, opts ...pulumi.InvokeOption) LookupContainerResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getContainer:getContainer", args, LookupContainerResultOutput{}, options).(LookupContainerResultOutput)
}

// A collection of arguments for invoking getContainer.
type LookupContainerOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupContainerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContainerArgs)(nil)).Elem()
}

// A collection of values returned by getContainer.
type LookupContainerResultOutput struct{ *pulumi.OutputState }

func (LookupContainerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContainerResult)(nil)).Elem()
}

func (o LookupContainerResultOutput) ToLookupContainerResultOutput() LookupContainerResultOutput {
	return o
}

func (o LookupContainerResultOutput) ToLookupContainerResultOutputWithContext(ctx context.Context) LookupContainerResultOutput {
	return o
}

func (o LookupContainerResultOutput) Autostart() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupContainerResult) bool { return v.Autostart }).(pulumi.BoolOutput)
}

func (o LookupContainerResultOutput) CapabilitiesPolicy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.CapabilitiesPolicy }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) CapabilitiesState() pulumi.BoolMapOutput {
	return o.ApplyT(func(v LookupContainerResult) map[string]bool { return v.CapabilitiesState }).(pulumi.BoolMapOutput)
}

func (o LookupContainerResultOutput) Cpuset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Cpuset }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Dataset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Dataset }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) DefaultNetwork() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.DefaultNetwork }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupContainerResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupContainerResultOutput) Idmap() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Idmap }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Init() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Init }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Initdir() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Initdir }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Initenv() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupContainerResult) map[string]string { return v.Initenv }).(pulumi.StringMapOutput)
}

func (o LookupContainerResultOutput) Initgroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Initgroup }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Inituser() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Inituser }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Pool }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Running() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupContainerResult) bool { return v.Running }).(pulumi.BoolOutput)
}

func (o LookupContainerResultOutput) ShutdownTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupContainerResult) int { return v.ShutdownTimeout }).(pulumi.IntOutput)
}

func (o LookupContainerResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Time() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Time }).(pulumi.StringOutput)
}

func (o LookupContainerResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupContainerResultOutput{})
}
