// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudBackup(ctx *pulumi.Context, args *LookupCloudBackupArgs, opts ...pulumi.InvokeOption) (*LookupCloudBackupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCloudBackupResult
	err := ctx.Invoke("truenas:index/getCloudBackup:getCloudBackup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudBackup.
type LookupCloudBackupArgs struct {
	Description string `pulumi:"description"`
}

// A collection of values returned by getCloudBackup.
type LookupCloudBackupResult struct {
	AbsolutePaths   bool                   `pulumi:"absolutePaths"`
	Attributes      string                 `pulumi:"attributes"`
	CachePath       string                 `pulumi:"cachePath"`
	Credentials     int                    `pulumi:"credentials"`
	Description     string                 `pulumi:"description"`
	Enabled         bool                   `pulumi:"enabled"`
	Excludes        []string               `pulumi:"excludes"`
	Id              int                    `pulumi:"id"`
	Includes        []string               `pulumi:"includes"`
	KeepLast        int                    `pulumi:"keepLast"`
	Password        string                 `pulumi:"password"`
	Path            string                 `pulumi:"path"`
	PostScript      string                 `pulumi:"postScript"`
	PreScript       string                 `pulumi:"preScript"`
	RateLimit       int                    `pulumi:"rateLimit"`
	Schedule        GetCloudBackupSchedule `pulumi:"schedule"`
	Snapshot        bool                   `pulumi:"snapshot"`
	TransferSetting string                 `pulumi:"transferSetting"`
}

func LookupCloudBackupOutput(ctx *pulumi.Context, args LookupCloudBackupOutputArgs, opts ...pulumi.InvokeOption) LookupCloudBackupResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getCloudBackup:getCloudBackup", args, LookupCloudBackupResultOutput{}, options).(LookupCloudBackupResultOutput)
}

// A collection of arguments for invoking getCloudBackup.
type LookupCloudBackupOutputArgs struct {
	Description pulumi.StringInput `pulumi:"description"`
}

func (LookupCloudBackupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudBackupArgs)(nil)).Elem()
}

// A collection of values returned by getCloudBackup.
type LookupCloudBackupResultOutput struct{ *pulumi.OutputState }

func (LookupCloudBackupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudBackupResult)(nil)).Elem()
}

func (o LookupCloudBackupResultOutput) ToLookupCloudBackupResultOutput() LookupCloudBackupResultOutput {
	return o
}

func (o LookupCloudBackupResultOutput) ToLookupCloudBackupResultOutputWithContext(ctx context.Context) LookupCloudBackupResultOutput {
	return o
}

func (o LookupCloudBackupResultOutput) AbsolutePaths() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) bool { return v.AbsolutePaths }).(pulumi.BoolOutput)
}

func (o LookupCloudBackupResultOutput) Attributes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.Attributes }).(pulumi.StringOutput)
}

func (o LookupCloudBackupResultOutput) CachePath() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.CachePath }).(pulumi.StringOutput)
}

func (o LookupCloudBackupResultOutput) Credentials() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) int { return v.Credentials }).(pulumi.IntOutput)
}

func (o LookupCloudBackupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupCloudBackupResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupCloudBackupResultOutput) Excludes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) []string { return v.Excludes }).(pulumi.StringArrayOutput)
}

func (o LookupCloudBackupResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupCloudBackupResultOutput) Includes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) []string { return v.Includes }).(pulumi.StringArrayOutput)
}

func (o LookupCloudBackupResultOutput) KeepLast() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) int { return v.KeepLast }).(pulumi.IntOutput)
}

func (o LookupCloudBackupResultOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.Password }).(pulumi.StringOutput)
}

func (o LookupCloudBackupResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o LookupCloudBackupResultOutput) PostScript() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.PostScript }).(pulumi.StringOutput)
}

func (o LookupCloudBackupResultOutput) PreScript() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.PreScript }).(pulumi.StringOutput)
}

func (o LookupCloudBackupResultOutput) RateLimit() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) int { return v.RateLimit }).(pulumi.IntOutput)
}

func (o LookupCloudBackupResultOutput) Schedule() GetCloudBackupScheduleOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) GetCloudBackupSchedule { return v.Schedule }).(GetCloudBackupScheduleOutput)
}

func (o LookupCloudBackupResultOutput) Snapshot() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) bool { return v.Snapshot }).(pulumi.BoolOutput)
}

func (o LookupCloudBackupResultOutput) TransferSetting() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupResult) string { return v.TransferSetting }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudBackupResultOutput{})
}
