// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudsyncTask(ctx *pulumi.Context, args *LookupCloudsyncTaskArgs, opts ...pulumi.InvokeOption) (*LookupCloudsyncTaskResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCloudsyncTaskResult
	err := ctx.Invoke("truenas:index/getCloudsyncTask:getCloudsyncTask", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudsyncTask.
type LookupCloudsyncTaskArgs struct {
	Description string `pulumi:"description"`
}

// A collection of values returned by getCloudsyncTask.
type LookupCloudsyncTaskResult struct {
	Attributes         string                    `pulumi:"attributes"`
	Bwlimits           []GetCloudsyncTaskBwlimit `pulumi:"bwlimits"`
	CreateEmptySrcDirs bool                      `pulumi:"createEmptySrcDirs"`
	Credentials        int                       `pulumi:"credentials"`
	Description        string                    `pulumi:"description"`
	Direction          string                    `pulumi:"direction"`
	Enabled            bool                      `pulumi:"enabled"`
	Encryption         bool                      `pulumi:"encryption"`
	EncryptionPassword string                    `pulumi:"encryptionPassword"`
	EncryptionSalt     string                    `pulumi:"encryptionSalt"`
	Excludes           []string                  `pulumi:"excludes"`
	FilenameEncryption bool                      `pulumi:"filenameEncryption"`
	FollowSymlinks     bool                      `pulumi:"followSymlinks"`
	Id                 int                       `pulumi:"id"`
	Includes           []string                  `pulumi:"includes"`
	Path               string                    `pulumi:"path"`
	PostScript         string                    `pulumi:"postScript"`
	PreScript          string                    `pulumi:"preScript"`
	Schedule           GetCloudsyncTaskSchedule  `pulumi:"schedule"`
	Snapshot           bool                      `pulumi:"snapshot"`
	TransferMode       string                    `pulumi:"transferMode"`
	Transfers          int                       `pulumi:"transfers"`
}

func LookupCloudsyncTaskOutput(ctx *pulumi.Context, args LookupCloudsyncTaskOutputArgs, opts ...pulumi.InvokeOption) LookupCloudsyncTaskResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getCloudsyncTask:getCloudsyncTask", args, LookupCloudsyncTaskResultOutput{}, options).(LookupCloudsyncTaskResultOutput)
}

// A collection of arguments for invoking getCloudsyncTask.
type LookupCloudsyncTaskOutputArgs struct {
	Description pulumi.StringInput `pulumi:"description"`
}

func (LookupCloudsyncTaskOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudsyncTaskArgs)(nil)).Elem()
}

// A collection of values returned by getCloudsyncTask.
type LookupCloudsyncTaskResultOutput struct{ *pulumi.OutputState }

func (LookupCloudsyncTaskResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudsyncTaskResult)(nil)).Elem()
}

func (o LookupCloudsyncTaskResultOutput) ToLookupCloudsyncTaskResultOutput() LookupCloudsyncTaskResultOutput {
	return o
}

func (o LookupCloudsyncTaskResultOutput) ToLookupCloudsyncTaskResultOutputWithContext(ctx context.Context) LookupCloudsyncTaskResultOutput {
	return o
}

func (o LookupCloudsyncTaskResultOutput) Attributes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.Attributes }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) Bwlimits() GetCloudsyncTaskBwlimitArrayOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) []GetCloudsyncTaskBwlimit { return v.Bwlimits }).(GetCloudsyncTaskBwlimitArrayOutput)
}

func (o LookupCloudsyncTaskResultOutput) CreateEmptySrcDirs() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) bool { return v.CreateEmptySrcDirs }).(pulumi.BoolOutput)
}

func (o LookupCloudsyncTaskResultOutput) Credentials() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) int { return v.Credentials }).(pulumi.IntOutput)
}

func (o LookupCloudsyncTaskResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) Direction() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.Direction }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupCloudsyncTaskResultOutput) Encryption() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) bool { return v.Encryption }).(pulumi.BoolOutput)
}

func (o LookupCloudsyncTaskResultOutput) EncryptionPassword() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.EncryptionPassword }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) EncryptionSalt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.EncryptionSalt }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) Excludes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) []string { return v.Excludes }).(pulumi.StringArrayOutput)
}

func (o LookupCloudsyncTaskResultOutput) FilenameEncryption() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) bool { return v.FilenameEncryption }).(pulumi.BoolOutput)
}

func (o LookupCloudsyncTaskResultOutput) FollowSymlinks() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) bool { return v.FollowSymlinks }).(pulumi.BoolOutput)
}

func (o LookupCloudsyncTaskResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupCloudsyncTaskResultOutput) Includes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) []string { return v.Includes }).(pulumi.StringArrayOutput)
}

func (o LookupCloudsyncTaskResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) PostScript() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.PostScript }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) PreScript() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.PreScript }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) Schedule() GetCloudsyncTaskScheduleOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) GetCloudsyncTaskSchedule { return v.Schedule }).(GetCloudsyncTaskScheduleOutput)
}

func (o LookupCloudsyncTaskResultOutput) Snapshot() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) bool { return v.Snapshot }).(pulumi.BoolOutput)
}

func (o LookupCloudsyncTaskResultOutput) TransferMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) string { return v.TransferMode }).(pulumi.StringOutput)
}

func (o LookupCloudsyncTaskResultOutput) Transfers() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudsyncTaskResult) int { return v.Transfers }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudsyncTaskResultOutput{})
}
