// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDockerConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupDockerConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDockerConfigResult
	err := ctx.Invoke("truenas:index/getDockerConfig:getDockerConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDockerConfig.
type LookupDockerConfigResult struct {
	AddressPools       []GetDockerConfigAddressPool    `pulumi:"addressPools"`
	CidrV6             string                          `pulumi:"cidrV6"`
	Dataset            string                          `pulumi:"dataset"`
	EnableImageUpdates bool                            `pulumi:"enableImageUpdates"`
	Id                 string                          `pulumi:"id"`
	Nvidia             bool                            `pulumi:"nvidia"`
	Pool               string                          `pulumi:"pool"`
	RegistryMirrors    []GetDockerConfigRegistryMirror `pulumi:"registryMirrors"`
}

func LookupDockerConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupDockerConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getDockerConfig:getDockerConfig", nil, LookupDockerConfigResultOutput{}, options).(LookupDockerConfigResultOutput)
}

// A collection of values returned by getDockerConfig.
type LookupDockerConfigResultOutput struct{ *pulumi.OutputState }

func (LookupDockerConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDockerConfigResult)(nil)).Elem()
}

func (o LookupDockerConfigResultOutput) ToLookupDockerConfigResultOutput() LookupDockerConfigResultOutput {
	return o
}

func (o LookupDockerConfigResultOutput) ToLookupDockerConfigResultOutputWithContext(ctx context.Context) LookupDockerConfigResultOutput {
	return o
}

func (o LookupDockerConfigResultOutput) AddressPools() GetDockerConfigAddressPoolArrayOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) []GetDockerConfigAddressPool { return v.AddressPools }).(GetDockerConfigAddressPoolArrayOutput)
}

func (o LookupDockerConfigResultOutput) CidrV6() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) string { return v.CidrV6 }).(pulumi.StringOutput)
}

func (o LookupDockerConfigResultOutput) Dataset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) string { return v.Dataset }).(pulumi.StringOutput)
}

func (o LookupDockerConfigResultOutput) EnableImageUpdates() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) bool { return v.EnableImageUpdates }).(pulumi.BoolOutput)
}

func (o LookupDockerConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDockerConfigResultOutput) Nvidia() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) bool { return v.Nvidia }).(pulumi.BoolOutput)
}

func (o LookupDockerConfigResultOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) string { return v.Pool }).(pulumi.StringOutput)
}

func (o LookupDockerConfigResultOutput) RegistryMirrors() GetDockerConfigRegistryMirrorArrayOutput {
	return o.ApplyT(func(v LookupDockerConfigResult) []GetDockerConfigRegistryMirror { return v.RegistryMirrors }).(GetDockerConfigRegistryMirrorArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDockerConfigResultOutput{})
}
