// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDirectoryservices(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupDirectoryservicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDirectoryservicesResult
	err := ctx.Invoke("truenas:index/getDirectoryservices:getDirectoryservices", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDirectoryservices.
type LookupDirectoryservicesResult struct {
	ConfigurationActivedirectory GetDirectoryservicesConfigurationActivedirectory `pulumi:"configurationActivedirectory"`
	ConfigurationIpa             GetDirectoryservicesConfigurationIpa             `pulumi:"configurationIpa"`
	ConfigurationLdap            GetDirectoryservicesConfigurationLdap            `pulumi:"configurationLdap"`
	Enable                       bool                                             `pulumi:"enable"`
	EnableAccountCache           bool                                             `pulumi:"enableAccountCache"`
	EnableDnsUpdates             bool                                             `pulumi:"enableDnsUpdates"`
	Id                           string                                           `pulumi:"id"`
	KerberosRealm                string                                           `pulumi:"kerberosRealm"`
	ServiceType                  string                                           `pulumi:"serviceType"`
	Status                       string                                           `pulumi:"status"`
	StatusMsg                    string                                           `pulumi:"statusMsg"`
	Timeout                      int                                              `pulumi:"timeout"`
}

func LookupDirectoryservicesOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupDirectoryservicesResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getDirectoryservices:getDirectoryservices", nil, LookupDirectoryservicesResultOutput{}, options).(LookupDirectoryservicesResultOutput)
}

// A collection of values returned by getDirectoryservices.
type LookupDirectoryservicesResultOutput struct{ *pulumi.OutputState }

func (LookupDirectoryservicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDirectoryservicesResult)(nil)).Elem()
}

func (o LookupDirectoryservicesResultOutput) ToLookupDirectoryservicesResultOutput() LookupDirectoryservicesResultOutput {
	return o
}

func (o LookupDirectoryservicesResultOutput) ToLookupDirectoryservicesResultOutputWithContext(ctx context.Context) LookupDirectoryservicesResultOutput {
	return o
}

func (o LookupDirectoryservicesResultOutput) ConfigurationActivedirectory() GetDirectoryservicesConfigurationActivedirectoryOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) GetDirectoryservicesConfigurationActivedirectory {
		return v.ConfigurationActivedirectory
	}).(GetDirectoryservicesConfigurationActivedirectoryOutput)
}

func (o LookupDirectoryservicesResultOutput) ConfigurationIpa() GetDirectoryservicesConfigurationIpaOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) GetDirectoryservicesConfigurationIpa { return v.ConfigurationIpa }).(GetDirectoryservicesConfigurationIpaOutput)
}

func (o LookupDirectoryservicesResultOutput) ConfigurationLdap() GetDirectoryservicesConfigurationLdapOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) GetDirectoryservicesConfigurationLdap {
		return v.ConfigurationLdap
	}).(GetDirectoryservicesConfigurationLdapOutput)
}

func (o LookupDirectoryservicesResultOutput) Enable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) bool { return v.Enable }).(pulumi.BoolOutput)
}

func (o LookupDirectoryservicesResultOutput) EnableAccountCache() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) bool { return v.EnableAccountCache }).(pulumi.BoolOutput)
}

func (o LookupDirectoryservicesResultOutput) EnableDnsUpdates() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) bool { return v.EnableDnsUpdates }).(pulumi.BoolOutput)
}

func (o LookupDirectoryservicesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDirectoryservicesResultOutput) KerberosRealm() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) string { return v.KerberosRealm }).(pulumi.StringOutput)
}

func (o LookupDirectoryservicesResultOutput) ServiceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) string { return v.ServiceType }).(pulumi.StringOutput)
}

func (o LookupDirectoryservicesResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupDirectoryservicesResultOutput) StatusMsg() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) string { return v.StatusMsg }).(pulumi.StringOutput)
}

func (o LookupDirectoryservicesResultOutput) Timeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupDirectoryservicesResult) int { return v.Timeout }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDirectoryservicesResultOutput{})
}
