// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupFtpConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupFtpConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFtpConfigResult
	err := ctx.Invoke("truenas:index/getFtpConfig:getFtpConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getFtpConfig.
type LookupFtpConfigResult struct {
	Anonpath                        string `pulumi:"anonpath"`
	Anonuserbw                      int    `pulumi:"anonuserbw"`
	Anonuserdlbw                    int    `pulumi:"anonuserdlbw"`
	Banner                          string `pulumi:"banner"`
	Clients                         int    `pulumi:"clients"`
	Defaultroot                     bool   `pulumi:"defaultroot"`
	Dirmask                         string `pulumi:"dirmask"`
	Filemask                        string `pulumi:"filemask"`
	Fxp                             bool   `pulumi:"fxp"`
	Id                              string `pulumi:"id"`
	Ident                           bool   `pulumi:"ident"`
	Ipconnections                   int    `pulumi:"ipconnections"`
	Localuserbw                     int    `pulumi:"localuserbw"`
	Localuserdlbw                   int    `pulumi:"localuserdlbw"`
	Loginattempt                    int    `pulumi:"loginattempt"`
	Masqaddress                     string `pulumi:"masqaddress"`
	Onlyanonymous                   bool   `pulumi:"onlyanonymous"`
	Onlylocal                       bool   `pulumi:"onlylocal"`
	Options                         string `pulumi:"options"`
	Passiveportsmax                 int    `pulumi:"passiveportsmax"`
	Passiveportsmin                 int    `pulumi:"passiveportsmin"`
	Port                            int    `pulumi:"port"`
	Resume                          bool   `pulumi:"resume"`
	Reversedns                      bool   `pulumi:"reversedns"`
	SsltlsCertificate               int    `pulumi:"ssltlsCertificate"`
	Timeout                         int    `pulumi:"timeout"`
	TimeoutNotransfer               int    `pulumi:"timeoutNotransfer"`
	Tls                             bool   `pulumi:"tls"`
	TlsOptAllowClientRenegotiations bool   `pulumi:"tlsOptAllowClientRenegotiations"`
	TlsOptAllowDotLogin             bool   `pulumi:"tlsOptAllowDotLogin"`
	TlsOptAllowPerUser              bool   `pulumi:"tlsOptAllowPerUser"`
	TlsOptCommonNameRequired        bool   `pulumi:"tlsOptCommonNameRequired"`
	TlsOptDnsNameRequired           bool   `pulumi:"tlsOptDnsNameRequired"`
	TlsOptEnableDiags               bool   `pulumi:"tlsOptEnableDiags"`
	TlsOptExportCertData            bool   `pulumi:"tlsOptExportCertData"`
	TlsOptIpAddressRequired         bool   `pulumi:"tlsOptIpAddressRequired"`
	TlsOptNoEmptyFragments          bool   `pulumi:"tlsOptNoEmptyFragments"`
	TlsOptNoSessionReuseRequired    bool   `pulumi:"tlsOptNoSessionReuseRequired"`
	TlsOptStdenvvars                bool   `pulumi:"tlsOptStdenvvars"`
	TlsPolicy                       string `pulumi:"tlsPolicy"`
}

func LookupFtpConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupFtpConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getFtpConfig:getFtpConfig", nil, LookupFtpConfigResultOutput{}, options).(LookupFtpConfigResultOutput)
}

// A collection of values returned by getFtpConfig.
type LookupFtpConfigResultOutput struct{ *pulumi.OutputState }

func (LookupFtpConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFtpConfigResult)(nil)).Elem()
}

func (o LookupFtpConfigResultOutput) ToLookupFtpConfigResultOutput() LookupFtpConfigResultOutput {
	return o
}

func (o LookupFtpConfigResultOutput) ToLookupFtpConfigResultOutputWithContext(ctx context.Context) LookupFtpConfigResultOutput {
	return o
}

func (o LookupFtpConfigResultOutput) Anonpath() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.Anonpath }).(pulumi.StringOutput)
}

func (o LookupFtpConfigResultOutput) Anonuserbw() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Anonuserbw }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Anonuserdlbw() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Anonuserdlbw }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Banner() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.Banner }).(pulumi.StringOutput)
}

func (o LookupFtpConfigResultOutput) Clients() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Clients }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Defaultroot() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Defaultroot }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) Dirmask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.Dirmask }).(pulumi.StringOutput)
}

func (o LookupFtpConfigResultOutput) Filemask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.Filemask }).(pulumi.StringOutput)
}

func (o LookupFtpConfigResultOutput) Fxp() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Fxp }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFtpConfigResultOutput) Ident() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Ident }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) Ipconnections() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Ipconnections }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Localuserbw() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Localuserbw }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Localuserdlbw() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Localuserdlbw }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Loginattempt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Loginattempt }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Masqaddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.Masqaddress }).(pulumi.StringOutput)
}

func (o LookupFtpConfigResultOutput) Onlyanonymous() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Onlyanonymous }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) Onlylocal() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Onlylocal }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) Options() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.Options }).(pulumi.StringOutput)
}

func (o LookupFtpConfigResultOutput) Passiveportsmax() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Passiveportsmax }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Passiveportsmin() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Passiveportsmin }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Port }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Resume() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Resume }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) Reversedns() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Reversedns }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) SsltlsCertificate() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.SsltlsCertificate }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Timeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.Timeout }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) TimeoutNotransfer() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) int { return v.TimeoutNotransfer }).(pulumi.IntOutput)
}

func (o LookupFtpConfigResultOutput) Tls() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.Tls }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptAllowClientRenegotiations() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptAllowClientRenegotiations }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptAllowDotLogin() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptAllowDotLogin }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptAllowPerUser() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptAllowPerUser }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptCommonNameRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptCommonNameRequired }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptDnsNameRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptDnsNameRequired }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptEnableDiags() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptEnableDiags }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptExportCertData() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptExportCertData }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptIpAddressRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptIpAddressRequired }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptNoEmptyFragments() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptNoEmptyFragments }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptNoSessionReuseRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptNoSessionReuseRequired }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsOptStdenvvars() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) bool { return v.TlsOptStdenvvars }).(pulumi.BoolOutput)
}

func (o LookupFtpConfigResultOutput) TlsPolicy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFtpConfigResult) string { return v.TlsPolicy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFtpConfigResultOutput{})
}
