// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIpmiLan(ctx *pulumi.Context, args *LookupIpmiLanArgs, opts ...pulumi.InvokeOption) (*LookupIpmiLanResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupIpmiLanResult
	err := ctx.Invoke("truenas:index/getIpmiLan:getIpmiLan", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpmiLan.
type LookupIpmiLanArgs struct {
	Channel int `pulumi:"channel"`
}

// A collection of values returned by getIpmiLan.
type LookupIpmiLanResult struct {
	Channel      int    `pulumi:"channel"`
	Dhcp         bool   `pulumi:"dhcp"`
	Gateway      string `pulumi:"gateway"`
	Id           int    `pulumi:"id"`
	Ipaddress    string `pulumi:"ipaddress"`
	MacAddress   string `pulumi:"macAddress"`
	Netmask      string `pulumi:"netmask"`
	Vlan         int    `pulumi:"vlan"`
	VlanPriority int    `pulumi:"vlanPriority"`
}

func LookupIpmiLanOutput(ctx *pulumi.Context, args LookupIpmiLanOutputArgs, opts ...pulumi.InvokeOption) LookupIpmiLanResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getIpmiLan:getIpmiLan", args, LookupIpmiLanResultOutput{}, options).(LookupIpmiLanResultOutput)
}

// A collection of arguments for invoking getIpmiLan.
type LookupIpmiLanOutputArgs struct {
	Channel pulumi.IntInput `pulumi:"channel"`
}

func (LookupIpmiLanOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpmiLanArgs)(nil)).Elem()
}

// A collection of values returned by getIpmiLan.
type LookupIpmiLanResultOutput struct{ *pulumi.OutputState }

func (LookupIpmiLanResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIpmiLanResult)(nil)).Elem()
}

func (o LookupIpmiLanResultOutput) ToLookupIpmiLanResultOutput() LookupIpmiLanResultOutput {
	return o
}

func (o LookupIpmiLanResultOutput) ToLookupIpmiLanResultOutputWithContext(ctx context.Context) LookupIpmiLanResultOutput {
	return o
}

func (o LookupIpmiLanResultOutput) Channel() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) int { return v.Channel }).(pulumi.IntOutput)
}

func (o LookupIpmiLanResultOutput) Dhcp() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) bool { return v.Dhcp }).(pulumi.BoolOutput)
}

func (o LookupIpmiLanResultOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) string { return v.Gateway }).(pulumi.StringOutput)
}

func (o LookupIpmiLanResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupIpmiLanResultOutput) Ipaddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) string { return v.Ipaddress }).(pulumi.StringOutput)
}

func (o LookupIpmiLanResultOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) string { return v.MacAddress }).(pulumi.StringOutput)
}

func (o LookupIpmiLanResultOutput) Netmask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) string { return v.Netmask }).(pulumi.StringOutput)
}

func (o LookupIpmiLanResultOutput) Vlan() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) int { return v.Vlan }).(pulumi.IntOutput)
}

func (o LookupIpmiLanResultOutput) VlanPriority() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIpmiLanResult) int { return v.VlanPriority }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIpmiLanResultOutput{})
}
