// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupIscsiTarget(ctx *pulumi.Context, args *LookupIscsiTargetArgs, opts ...pulumi.InvokeOption) (*LookupIscsiTargetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupIscsiTargetResult
	err := ctx.Invoke("truenas:index/getIscsiTarget:getIscsiTarget", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIscsiTarget.
type LookupIscsiTargetArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getIscsiTarget.
type LookupIscsiTargetResult struct {
	Alias           string                        `pulumi:"alias"`
	AuthNetworks    []string                      `pulumi:"authNetworks"`
	Groups          []GetIscsiTargetGroup         `pulumi:"groups"`
	Id              int                           `pulumi:"id"`
	IscsiParameters GetIscsiTargetIscsiParameters `pulumi:"iscsiParameters"`
	Mode            string                        `pulumi:"mode"`
	Name            string                        `pulumi:"name"`
	RelTgtId        int                           `pulumi:"relTgtId"`
}

func LookupIscsiTargetOutput(ctx *pulumi.Context, args LookupIscsiTargetOutputArgs, opts ...pulumi.InvokeOption) LookupIscsiTargetResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getIscsiTarget:getIscsiTarget", args, LookupIscsiTargetResultOutput{}, options).(LookupIscsiTargetResultOutput)
}

// A collection of arguments for invoking getIscsiTarget.
type LookupIscsiTargetOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupIscsiTargetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIscsiTargetArgs)(nil)).Elem()
}

// A collection of values returned by getIscsiTarget.
type LookupIscsiTargetResultOutput struct{ *pulumi.OutputState }

func (LookupIscsiTargetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIscsiTargetResult)(nil)).Elem()
}

func (o LookupIscsiTargetResultOutput) ToLookupIscsiTargetResultOutput() LookupIscsiTargetResultOutput {
	return o
}

func (o LookupIscsiTargetResultOutput) ToLookupIscsiTargetResultOutputWithContext(ctx context.Context) LookupIscsiTargetResultOutput {
	return o
}

func (o LookupIscsiTargetResultOutput) Alias() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) string { return v.Alias }).(pulumi.StringOutput)
}

func (o LookupIscsiTargetResultOutput) AuthNetworks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) []string { return v.AuthNetworks }).(pulumi.StringArrayOutput)
}

func (o LookupIscsiTargetResultOutput) Groups() GetIscsiTargetGroupArrayOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) []GetIscsiTargetGroup { return v.Groups }).(GetIscsiTargetGroupArrayOutput)
}

func (o LookupIscsiTargetResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupIscsiTargetResultOutput) IscsiParameters() GetIscsiTargetIscsiParametersOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) GetIscsiTargetIscsiParameters { return v.IscsiParameters }).(GetIscsiTargetIscsiParametersOutput)
}

func (o LookupIscsiTargetResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) string { return v.Mode }).(pulumi.StringOutput)
}

func (o LookupIscsiTargetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupIscsiTargetResultOutput) RelTgtId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupIscsiTargetResult) int { return v.RelTgtId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIscsiTargetResultOutput{})
}
