// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupKerberosRealm(ctx *pulumi.Context, args *LookupKerberosRealmArgs, opts ...pulumi.InvokeOption) (*LookupKerberosRealmResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupKerberosRealmResult
	err := ctx.Invoke("truenas:index/getKerberosRealm:getKerberosRealm", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKerberosRealm.
type LookupKerberosRealmArgs struct {
	Realm string `pulumi:"realm"`
}

// A collection of values returned by getKerberosRealm.
type LookupKerberosRealmResult struct {
	AdminServers   []string `pulumi:"adminServers"`
	Id             int      `pulumi:"id"`
	Kdcs           []string `pulumi:"kdcs"`
	KpasswdServers []string `pulumi:"kpasswdServers"`
	PrimaryKdc     string   `pulumi:"primaryKdc"`
	Realm          string   `pulumi:"realm"`
}

func LookupKerberosRealmOutput(ctx *pulumi.Context, args LookupKerberosRealmOutputArgs, opts ...pulumi.InvokeOption) LookupKerberosRealmResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getKerberosRealm:getKerberosRealm", args, LookupKerberosRealmResultOutput{}, options).(LookupKerberosRealmResultOutput)
}

// A collection of arguments for invoking getKerberosRealm.
type LookupKerberosRealmOutputArgs struct {
	Realm pulumi.StringInput `pulumi:"realm"`
}

func (LookupKerberosRealmOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKerberosRealmArgs)(nil)).Elem()
}

// A collection of values returned by getKerberosRealm.
type LookupKerberosRealmResultOutput struct{ *pulumi.OutputState }

func (LookupKerberosRealmResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKerberosRealmResult)(nil)).Elem()
}

func (o LookupKerberosRealmResultOutput) ToLookupKerberosRealmResultOutput() LookupKerberosRealmResultOutput {
	return o
}

func (o LookupKerberosRealmResultOutput) ToLookupKerberosRealmResultOutputWithContext(ctx context.Context) LookupKerberosRealmResultOutput {
	return o
}

func (o LookupKerberosRealmResultOutput) AdminServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupKerberosRealmResult) []string { return v.AdminServers }).(pulumi.StringArrayOutput)
}

func (o LookupKerberosRealmResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKerberosRealmResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupKerberosRealmResultOutput) Kdcs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupKerberosRealmResult) []string { return v.Kdcs }).(pulumi.StringArrayOutput)
}

func (o LookupKerberosRealmResultOutput) KpasswdServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupKerberosRealmResult) []string { return v.KpasswdServers }).(pulumi.StringArrayOutput)
}

func (o LookupKerberosRealmResultOutput) PrimaryKdc() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKerberosRealmResult) string { return v.PrimaryKdc }).(pulumi.StringOutput)
}

func (o LookupKerberosRealmResultOutput) Realm() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKerberosRealmResult) string { return v.Realm }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKerberosRealmResultOutput{})
}
