// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupKeychainSshConnection(ctx *pulumi.Context, args *LookupKeychainSshConnectionArgs, opts ...pulumi.InvokeOption) (*LookupKeychainSshConnectionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupKeychainSshConnectionResult
	err := ctx.Invoke("truenas:index/getKeychainSshConnection:getKeychainSshConnection", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKeychainSshConnection.
type LookupKeychainSshConnectionArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getKeychainSshConnection.
type LookupKeychainSshConnectionResult struct {
	ConnectTimeout int    `pulumi:"connectTimeout"`
	Host           string `pulumi:"host"`
	Id             int    `pulumi:"id"`
	Name           string `pulumi:"name"`
	Port           int    `pulumi:"port"`
	PrivateKeyId   int    `pulumi:"privateKeyId"`
	RemoteHostKey  string `pulumi:"remoteHostKey"`
	Username       string `pulumi:"username"`
}

func LookupKeychainSshConnectionOutput(ctx *pulumi.Context, args LookupKeychainSshConnectionOutputArgs, opts ...pulumi.InvokeOption) LookupKeychainSshConnectionResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getKeychainSshConnection:getKeychainSshConnection", args, LookupKeychainSshConnectionResultOutput{}, options).(LookupKeychainSshConnectionResultOutput)
}

// A collection of arguments for invoking getKeychainSshConnection.
type LookupKeychainSshConnectionOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupKeychainSshConnectionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeychainSshConnectionArgs)(nil)).Elem()
}

// A collection of values returned by getKeychainSshConnection.
type LookupKeychainSshConnectionResultOutput struct{ *pulumi.OutputState }

func (LookupKeychainSshConnectionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeychainSshConnectionResult)(nil)).Elem()
}

func (o LookupKeychainSshConnectionResultOutput) ToLookupKeychainSshConnectionResultOutput() LookupKeychainSshConnectionResultOutput {
	return o
}

func (o LookupKeychainSshConnectionResultOutput) ToLookupKeychainSshConnectionResultOutputWithContext(ctx context.Context) LookupKeychainSshConnectionResultOutput {
	return o
}

func (o LookupKeychainSshConnectionResultOutput) ConnectTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) int { return v.ConnectTimeout }).(pulumi.IntOutput)
}

func (o LookupKeychainSshConnectionResultOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) string { return v.Host }).(pulumi.StringOutput)
}

func (o LookupKeychainSshConnectionResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupKeychainSshConnectionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupKeychainSshConnectionResultOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) int { return v.Port }).(pulumi.IntOutput)
}

func (o LookupKeychainSshConnectionResultOutput) PrivateKeyId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) int { return v.PrivateKeyId }).(pulumi.IntOutput)
}

func (o LookupKeychainSshConnectionResultOutput) RemoteHostKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) string { return v.RemoteHostKey }).(pulumi.StringOutput)
}

func (o LookupKeychainSshConnectionResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeychainSshConnectionResult) string { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKeychainSshConnectionResultOutput{})
}
