// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupLxcConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupLxcConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupLxcConfigResult
	err := ctx.Invoke("truenas:index/getLxcConfig:getLxcConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getLxcConfig.
type LookupLxcConfigResult struct {
	Bridge        string `pulumi:"bridge"`
	Id            string `pulumi:"id"`
	PreferredPool string `pulumi:"preferredPool"`
	V4Network     string `pulumi:"v4Network"`
	V6Network     string `pulumi:"v6Network"`
}

func LookupLxcConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupLxcConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getLxcConfig:getLxcConfig", nil, LookupLxcConfigResultOutput{}, options).(LookupLxcConfigResultOutput)
}

// A collection of values returned by getLxcConfig.
type LookupLxcConfigResultOutput struct{ *pulumi.OutputState }

func (LookupLxcConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLxcConfigResult)(nil)).Elem()
}

func (o LookupLxcConfigResultOutput) ToLookupLxcConfigResultOutput() LookupLxcConfigResultOutput {
	return o
}

func (o LookupLxcConfigResultOutput) ToLookupLxcConfigResultOutputWithContext(ctx context.Context) LookupLxcConfigResultOutput {
	return o
}

func (o LookupLxcConfigResultOutput) Bridge() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLxcConfigResult) string { return v.Bridge }).(pulumi.StringOutput)
}

func (o LookupLxcConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLxcConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupLxcConfigResultOutput) PreferredPool() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLxcConfigResult) string { return v.PreferredPool }).(pulumi.StringOutput)
}

func (o LookupLxcConfigResultOutput) V4Network() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLxcConfigResult) string { return v.V4Network }).(pulumi.StringOutput)
}

func (o LookupLxcConfigResultOutput) V6Network() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLxcConfigResult) string { return v.V6Network }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLxcConfigResultOutput{})
}
