// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupMail(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupMailResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupMailResult
	err := ctx.Invoke("truenas:index/getMail:getMail", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getMail.
type LookupMailResult struct {
	Fromemail      string `pulumi:"fromemail"`
	Fromname       string `pulumi:"fromname"`
	Id             string `pulumi:"id"`
	Outgoingserver string `pulumi:"outgoingserver"`
	Port           int    `pulumi:"port"`
	Security       string `pulumi:"security"`
	Smtp           bool   `pulumi:"smtp"`
	User           string `pulumi:"user"`
}

func LookupMailOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupMailResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getMail:getMail", nil, LookupMailResultOutput{}, options).(LookupMailResultOutput)
}

// A collection of values returned by getMail.
type LookupMailResultOutput struct{ *pulumi.OutputState }

func (LookupMailResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMailResult)(nil)).Elem()
}

func (o LookupMailResultOutput) ToLookupMailResultOutput() LookupMailResultOutput {
	return o
}

func (o LookupMailResultOutput) ToLookupMailResultOutputWithContext(ctx context.Context) LookupMailResultOutput {
	return o
}

func (o LookupMailResultOutput) Fromemail() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMailResult) string { return v.Fromemail }).(pulumi.StringOutput)
}

func (o LookupMailResultOutput) Fromname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMailResult) string { return v.Fromname }).(pulumi.StringOutput)
}

func (o LookupMailResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMailResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupMailResultOutput) Outgoingserver() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMailResult) string { return v.Outgoingserver }).(pulumi.StringOutput)
}

func (o LookupMailResultOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v LookupMailResult) int { return v.Port }).(pulumi.IntOutput)
}

func (o LookupMailResultOutput) Security() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMailResult) string { return v.Security }).(pulumi.StringOutput)
}

func (o LookupMailResultOutput) Smtp() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupMailResult) bool { return v.Smtp }).(pulumi.BoolOutput)
}

func (o LookupMailResultOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMailResult) string { return v.User }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMailResultOutput{})
}
