// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupNetworkConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNetworkConfigResult
	err := ctx.Invoke("truenas:index/getNetworkConfig:getNetworkConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getNetworkConfig.
type LookupNetworkConfigResult struct {
	Domain              string                              `pulumi:"domain"`
	Domains             []string                            `pulumi:"domains"`
	Hostname            string                              `pulumi:"hostname"`
	Hosts               []string                            `pulumi:"hosts"`
	Httpproxy           string                              `pulumi:"httpproxy"`
	Id                  string                              `pulumi:"id"`
	Ipv4gateway         string                              `pulumi:"ipv4gateway"`
	Ipv6gateway         string                              `pulumi:"ipv6gateway"`
	Nameserver1         string                              `pulumi:"nameserver1"`
	Nameserver2         string                              `pulumi:"nameserver2"`
	Nameserver3         string                              `pulumi:"nameserver3"`
	ServiceAnnouncement GetNetworkConfigServiceAnnouncement `pulumi:"serviceAnnouncement"`
}

func LookupNetworkConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupNetworkConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getNetworkConfig:getNetworkConfig", nil, LookupNetworkConfigResultOutput{}, options).(LookupNetworkConfigResultOutput)
}

// A collection of values returned by getNetworkConfig.
type LookupNetworkConfigResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkConfigResult)(nil)).Elem()
}

func (o LookupNetworkConfigResultOutput) ToLookupNetworkConfigResultOutput() LookupNetworkConfigResultOutput {
	return o
}

func (o LookupNetworkConfigResultOutput) ToLookupNetworkConfigResultOutputWithContext(ctx context.Context) LookupNetworkConfigResultOutput {
	return o
}

func (o LookupNetworkConfigResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Domains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) []string { return v.Domains }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkConfigResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Hostname }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Hosts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) []string { return v.Hosts }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkConfigResultOutput) Httpproxy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Httpproxy }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Ipv4gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Ipv4gateway }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Ipv6gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Ipv6gateway }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Nameserver1() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Nameserver1 }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Nameserver2() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Nameserver2 }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) Nameserver3() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) string { return v.Nameserver3 }).(pulumi.StringOutput)
}

func (o LookupNetworkConfigResultOutput) ServiceAnnouncement() GetNetworkConfigServiceAnnouncementOutput {
	return o.ApplyT(func(v LookupNetworkConfigResult) GetNetworkConfigServiceAnnouncement { return v.ServiceAnnouncement }).(GetNetworkConfigServiceAnnouncementOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkConfigResultOutput{})
}
