// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNvmetPortSubsys(ctx *pulumi.Context, args *LookupNvmetPortSubsysArgs, opts ...pulumi.InvokeOption) (*LookupNvmetPortSubsysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNvmetPortSubsysResult
	err := ctx.Invoke("truenas:index/getNvmetPortSubsys:getNvmetPortSubsys", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNvmetPortSubsys.
type LookupNvmetPortSubsysArgs struct {
	Id int `pulumi:"id"`
}

// A collection of values returned by getNvmetPortSubsys.
type LookupNvmetPortSubsysResult struct {
	Id       int `pulumi:"id"`
	PortId   int `pulumi:"portId"`
	SubsysId int `pulumi:"subsysId"`
}

func LookupNvmetPortSubsysOutput(ctx *pulumi.Context, args LookupNvmetPortSubsysOutputArgs, opts ...pulumi.InvokeOption) LookupNvmetPortSubsysResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getNvmetPortSubsys:getNvmetPortSubsys", args, LookupNvmetPortSubsysResultOutput{}, options).(LookupNvmetPortSubsysResultOutput)
}

// A collection of arguments for invoking getNvmetPortSubsys.
type LookupNvmetPortSubsysOutputArgs struct {
	Id pulumi.IntInput `pulumi:"id"`
}

func (LookupNvmetPortSubsysOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNvmetPortSubsysArgs)(nil)).Elem()
}

// A collection of values returned by getNvmetPortSubsys.
type LookupNvmetPortSubsysResultOutput struct{ *pulumi.OutputState }

func (LookupNvmetPortSubsysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNvmetPortSubsysResult)(nil)).Elem()
}

func (o LookupNvmetPortSubsysResultOutput) ToLookupNvmetPortSubsysResultOutput() LookupNvmetPortSubsysResultOutput {
	return o
}

func (o LookupNvmetPortSubsysResultOutput) ToLookupNvmetPortSubsysResultOutputWithContext(ctx context.Context) LookupNvmetPortSubsysResultOutput {
	return o
}

func (o LookupNvmetPortSubsysResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNvmetPortSubsysResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupNvmetPortSubsysResultOutput) PortId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNvmetPortSubsysResult) int { return v.PortId }).(pulumi.IntOutput)
}

func (o LookupNvmetPortSubsysResultOutput) SubsysId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNvmetPortSubsysResult) int { return v.SubsysId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNvmetPortSubsysResultOutput{})
}
