// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkInterface(ctx *pulumi.Context, args *LookupNetworkInterfaceArgs, opts ...pulumi.InvokeOption) (*LookupNetworkInterfaceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNetworkInterfaceResult
	err := ctx.Invoke("truenas:index/getNetworkInterface:getNetworkInterface", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkInterface.
type LookupNetworkInterfaceArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getNetworkInterface.
type LookupNetworkInterfaceResult struct {
	Aliases             []GetNetworkInterfaceAlias `pulumi:"aliases"`
	BridgeMembers       []string                   `pulumi:"bridgeMembers"`
	Description         string                     `pulumi:"description"`
	EnableLearning      bool                       `pulumi:"enableLearning"`
	Id                  string                     `pulumi:"id"`
	Ipv4Dhcp            bool                       `pulumi:"ipv4Dhcp"`
	Ipv6Auto            bool                       `pulumi:"ipv6Auto"`
	LacpduRate          string                     `pulumi:"lacpduRate"`
	LagPorts            []string                   `pulumi:"lagPorts"`
	LagProtocol         string                     `pulumi:"lagProtocol"`
	Mtu                 int                        `pulumi:"mtu"`
	Name                string                     `pulumi:"name"`
	Stp                 bool                       `pulumi:"stp"`
	Type                string                     `pulumi:"type"`
	VlanParentInterface string                     `pulumi:"vlanParentInterface"`
	VlanPcp             int                        `pulumi:"vlanPcp"`
	VlanTag             int                        `pulumi:"vlanTag"`
	XmitHashPolicy      string                     `pulumi:"xmitHashPolicy"`
}

func LookupNetworkInterfaceOutput(ctx *pulumi.Context, args LookupNetworkInterfaceOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkInterfaceResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getNetworkInterface:getNetworkInterface", args, LookupNetworkInterfaceResultOutput{}, options).(LookupNetworkInterfaceResultOutput)
}

// A collection of arguments for invoking getNetworkInterface.
type LookupNetworkInterfaceOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupNetworkInterfaceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkInterfaceArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkInterface.
type LookupNetworkInterfaceResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkInterfaceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkInterfaceResult)(nil)).Elem()
}

func (o LookupNetworkInterfaceResultOutput) ToLookupNetworkInterfaceResultOutput() LookupNetworkInterfaceResultOutput {
	return o
}

func (o LookupNetworkInterfaceResultOutput) ToLookupNetworkInterfaceResultOutputWithContext(ctx context.Context) LookupNetworkInterfaceResultOutput {
	return o
}

func (o LookupNetworkInterfaceResultOutput) Aliases() GetNetworkInterfaceAliasArrayOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) []GetNetworkInterfaceAlias { return v.Aliases }).(GetNetworkInterfaceAliasArrayOutput)
}

func (o LookupNetworkInterfaceResultOutput) BridgeMembers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) []string { return v.BridgeMembers }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkInterfaceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) EnableLearning() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) bool { return v.EnableLearning }).(pulumi.BoolOutput)
}

func (o LookupNetworkInterfaceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Ipv4Dhcp() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) bool { return v.Ipv4Dhcp }).(pulumi.BoolOutput)
}

func (o LookupNetworkInterfaceResultOutput) Ipv6Auto() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) bool { return v.Ipv6Auto }).(pulumi.BoolOutput)
}

func (o LookupNetworkInterfaceResultOutput) LacpduRate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.LacpduRate }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) LagPorts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) []string { return v.LagPorts }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkInterfaceResultOutput) LagProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.LagProtocol }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Mtu() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) int { return v.Mtu }).(pulumi.IntOutput)
}

func (o LookupNetworkInterfaceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Stp() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) bool { return v.Stp }).(pulumi.BoolOutput)
}

func (o LookupNetworkInterfaceResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) VlanParentInterface() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.VlanParentInterface }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) VlanPcp() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) int { return v.VlanPcp }).(pulumi.IntOutput)
}

func (o LookupNetworkInterfaceResultOutput) VlanTag() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) int { return v.VlanTag }).(pulumi.IntOutput)
}

func (o LookupNetworkInterfaceResultOutput) XmitHashPolicy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.XmitHashPolicy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkInterfaceResultOutput{})
}
