// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupPool(ctx *pulumi.Context, args *LookupPoolArgs, opts ...pulumi.InvokeOption) (*LookupPoolResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupPoolResult
	err := ctx.Invoke("truenas:index/getPool:getPool", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPool.
type LookupPoolArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getPool.
type LookupPoolResult struct {
	Allocated     int             `pulumi:"allocated"`
	Autotrim      bool            `pulumi:"autotrim"`
	Checksum      string          `pulumi:"checksum"`
	Deduplication string          `pulumi:"deduplication"`
	Free          int             `pulumi:"free"`
	Guid          string          `pulumi:"guid"`
	Healthy       bool            `pulumi:"healthy"`
	Id            int             `pulumi:"id"`
	Name          string          `pulumi:"name"`
	Path          string          `pulumi:"path"`
	Size          int             `pulumi:"size"`
	Status        string          `pulumi:"status"`
	Topology      GetPoolTopology `pulumi:"topology"`
}

func LookupPoolOutput(ctx *pulumi.Context, args LookupPoolOutputArgs, opts ...pulumi.InvokeOption) LookupPoolResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getPool:getPool", args, LookupPoolResultOutput{}, options).(LookupPoolResultOutput)
}

// A collection of arguments for invoking getPool.
type LookupPoolOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupPoolOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPoolArgs)(nil)).Elem()
}

// A collection of values returned by getPool.
type LookupPoolResultOutput struct{ *pulumi.OutputState }

func (LookupPoolResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPoolResult)(nil)).Elem()
}

func (o LookupPoolResultOutput) ToLookupPoolResultOutput() LookupPoolResultOutput {
	return o
}

func (o LookupPoolResultOutput) ToLookupPoolResultOutputWithContext(ctx context.Context) LookupPoolResultOutput {
	return o
}

func (o LookupPoolResultOutput) Allocated() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPoolResult) int { return v.Allocated }).(pulumi.IntOutput)
}

func (o LookupPoolResultOutput) Autotrim() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupPoolResult) bool { return v.Autotrim }).(pulumi.BoolOutput)
}

func (o LookupPoolResultOutput) Checksum() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPoolResult) string { return v.Checksum }).(pulumi.StringOutput)
}

func (o LookupPoolResultOutput) Deduplication() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPoolResult) string { return v.Deduplication }).(pulumi.StringOutput)
}

func (o LookupPoolResultOutput) Free() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPoolResult) int { return v.Free }).(pulumi.IntOutput)
}

func (o LookupPoolResultOutput) Guid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPoolResult) string { return v.Guid }).(pulumi.StringOutput)
}

func (o LookupPoolResultOutput) Healthy() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupPoolResult) bool { return v.Healthy }).(pulumi.BoolOutput)
}

func (o LookupPoolResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPoolResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupPoolResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPoolResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupPoolResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPoolResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o LookupPoolResultOutput) Size() pulumi.IntOutput {
	return o.ApplyT(func(v LookupPoolResult) int { return v.Size }).(pulumi.IntOutput)
}

func (o LookupPoolResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPoolResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupPoolResultOutput) Topology() GetPoolTopologyOutput {
	return o.ApplyT(func(v LookupPoolResult) GetPoolTopology { return v.Topology }).(GetPoolTopologyOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPoolResultOutput{})
}
