// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupResilverConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupResilverConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupResilverConfigResult
	err := ctx.Invoke("truenas:index/getResilverConfig:getResilverConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getResilverConfig.
type LookupResilverConfigResult struct {
	Begin    string `pulumi:"begin"`
	Enabled  bool   `pulumi:"enabled"`
	End      string `pulumi:"end"`
	Id       string `pulumi:"id"`
	Weekdays []int  `pulumi:"weekdays"`
}

func LookupResilverConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupResilverConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getResilverConfig:getResilverConfig", nil, LookupResilverConfigResultOutput{}, options).(LookupResilverConfigResultOutput)
}

// A collection of values returned by getResilverConfig.
type LookupResilverConfigResultOutput struct{ *pulumi.OutputState }

func (LookupResilverConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupResilverConfigResult)(nil)).Elem()
}

func (o LookupResilverConfigResultOutput) ToLookupResilverConfigResultOutput() LookupResilverConfigResultOutput {
	return o
}

func (o LookupResilverConfigResultOutput) ToLookupResilverConfigResultOutputWithContext(ctx context.Context) LookupResilverConfigResultOutput {
	return o
}

func (o LookupResilverConfigResultOutput) Begin() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResilverConfigResult) string { return v.Begin }).(pulumi.StringOutput)
}

func (o LookupResilverConfigResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupResilverConfigResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupResilverConfigResultOutput) End() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResilverConfigResult) string { return v.End }).(pulumi.StringOutput)
}

func (o LookupResilverConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResilverConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupResilverConfigResultOutput) Weekdays() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupResilverConfigResult) []int { return v.Weekdays }).(pulumi.IntArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupResilverConfigResultOutput{})
}
