// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSmbConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupSmbConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSmbConfigResult
	err := ctx.Invoke("truenas:index/getSmbConfig:getSmbConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getSmbConfig.
type LookupSmbConfigResult struct {
	AaplExtensions   bool     `pulumi:"aaplExtensions"`
	AdminGroup       string   `pulumi:"adminGroup"`
	Bindips          []string `pulumi:"bindips"`
	Debug            bool     `pulumi:"debug"`
	Description      string   `pulumi:"description"`
	Dirmask          string   `pulumi:"dirmask"`
	Encryption       string   `pulumi:"encryption"`
	Filemask         string   `pulumi:"filemask"`
	Guest            string   `pulumi:"guest"`
	Id               string   `pulumi:"id"`
	Localmaster      bool     `pulumi:"localmaster"`
	MinimumProtocol  string   `pulumi:"minimumProtocol"`
	Multichannel     bool     `pulumi:"multichannel"`
	Netbiosaliases   []string `pulumi:"netbiosaliases"`
	Netbiosname      string   `pulumi:"netbiosname"`
	Ntlmv1Auth       bool     `pulumi:"ntlmv1Auth"`
	SearchProtocols  []string `pulumi:"searchProtocols"`
	ServerSid        string   `pulumi:"serverSid"`
	SmbOptions       string   `pulumi:"smbOptions"`
	StatefulFailover bool     `pulumi:"statefulFailover"`
	Syslog           bool     `pulumi:"syslog"`
	Unixcharset      string   `pulumi:"unixcharset"`
	Workgroup        string   `pulumi:"workgroup"`
}

func LookupSmbConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupSmbConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getSmbConfig:getSmbConfig", nil, LookupSmbConfigResultOutput{}, options).(LookupSmbConfigResultOutput)
}

// A collection of values returned by getSmbConfig.
type LookupSmbConfigResultOutput struct{ *pulumi.OutputState }

func (LookupSmbConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSmbConfigResult)(nil)).Elem()
}

func (o LookupSmbConfigResultOutput) ToLookupSmbConfigResultOutput() LookupSmbConfigResultOutput {
	return o
}

func (o LookupSmbConfigResultOutput) ToLookupSmbConfigResultOutputWithContext(ctx context.Context) LookupSmbConfigResultOutput {
	return o
}

func (o LookupSmbConfigResultOutput) AaplExtensions() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) bool { return v.AaplExtensions }).(pulumi.BoolOutput)
}

func (o LookupSmbConfigResultOutput) AdminGroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.AdminGroup }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Bindips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) []string { return v.Bindips }).(pulumi.StringArrayOutput)
}

func (o LookupSmbConfigResultOutput) Debug() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) bool { return v.Debug }).(pulumi.BoolOutput)
}

func (o LookupSmbConfigResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Dirmask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Dirmask }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Encryption() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Encryption }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Filemask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Filemask }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Guest() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Guest }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Localmaster() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) bool { return v.Localmaster }).(pulumi.BoolOutput)
}

func (o LookupSmbConfigResultOutput) MinimumProtocol() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.MinimumProtocol }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Multichannel() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) bool { return v.Multichannel }).(pulumi.BoolOutput)
}

func (o LookupSmbConfigResultOutput) Netbiosaliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) []string { return v.Netbiosaliases }).(pulumi.StringArrayOutput)
}

func (o LookupSmbConfigResultOutput) Netbiosname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Netbiosname }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Ntlmv1Auth() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) bool { return v.Ntlmv1Auth }).(pulumi.BoolOutput)
}

func (o LookupSmbConfigResultOutput) SearchProtocols() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) []string { return v.SearchProtocols }).(pulumi.StringArrayOutput)
}

func (o LookupSmbConfigResultOutput) ServerSid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.ServerSid }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) SmbOptions() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.SmbOptions }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) StatefulFailover() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) bool { return v.StatefulFailover }).(pulumi.BoolOutput)
}

func (o LookupSmbConfigResultOutput) Syslog() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) bool { return v.Syslog }).(pulumi.BoolOutput)
}

func (o LookupSmbConfigResultOutput) Unixcharset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Unixcharset }).(pulumi.StringOutput)
}

func (o LookupSmbConfigResultOutput) Workgroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbConfigResult) string { return v.Workgroup }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSmbConfigResultOutput{})
}
