// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSmbShare(ctx *pulumi.Context, args *LookupSmbShareArgs, opts ...pulumi.InvokeOption) (*LookupSmbShareResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSmbShareResult
	err := ctx.Invoke("truenas:index/getSmbShare:getSmbShare", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSmbShare.
type LookupSmbShareArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getSmbShare.
type LookupSmbShareResult struct {
	Abe              bool               `pulumi:"abe"`
	Acl              bool               `pulumi:"acl"`
	Audit            GetSmbShareAudit   `pulumi:"audit"`
	Browsable        bool               `pulumi:"browsable"`
	Comment          string             `pulumi:"comment"`
	Durablehandle    bool               `pulumi:"durablehandle"`
	Enabled          bool               `pulumi:"enabled"`
	Guestok          bool               `pulumi:"guestok"`
	Home             bool               `pulumi:"home"`
	Hostsallows      []string           `pulumi:"hostsallows"`
	Hostsdenies      []string           `pulumi:"hostsdenies"`
	Id               int                `pulumi:"id"`
	Locked           bool               `pulumi:"locked"`
	Name             string             `pulumi:"name"`
	Options          GetSmbShareOptions `pulumi:"options"`
	Path             string             `pulumi:"path"`
	Purpose          string             `pulumi:"purpose"`
	Recyclebin       bool               `pulumi:"recyclebin"`
	Ro               bool               `pulumi:"ro"`
	Streams          bool               `pulumi:"streams"`
	Timemachine      bool               `pulumi:"timemachine"`
	TimemachineQuota int                `pulumi:"timemachineQuota"`
	Vuid             string             `pulumi:"vuid"`
}

func LookupSmbShareOutput(ctx *pulumi.Context, args LookupSmbShareOutputArgs, opts ...pulumi.InvokeOption) LookupSmbShareResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getSmbShare:getSmbShare", args, LookupSmbShareResultOutput{}, options).(LookupSmbShareResultOutput)
}

// A collection of arguments for invoking getSmbShare.
type LookupSmbShareOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupSmbShareOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSmbShareArgs)(nil)).Elem()
}

// A collection of values returned by getSmbShare.
type LookupSmbShareResultOutput struct{ *pulumi.OutputState }

func (LookupSmbShareResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSmbShareResult)(nil)).Elem()
}

func (o LookupSmbShareResultOutput) ToLookupSmbShareResultOutput() LookupSmbShareResultOutput {
	return o
}

func (o LookupSmbShareResultOutput) ToLookupSmbShareResultOutputWithContext(ctx context.Context) LookupSmbShareResultOutput {
	return o
}

func (o LookupSmbShareResultOutput) Abe() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Abe }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Acl() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Acl }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Audit() GetSmbShareAuditOutput {
	return o.ApplyT(func(v LookupSmbShareResult) GetSmbShareAudit { return v.Audit }).(GetSmbShareAuditOutput)
}

func (o LookupSmbShareResultOutput) Browsable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Browsable }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbShareResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupSmbShareResultOutput) Durablehandle() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Durablehandle }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Guestok() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Guestok }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Home() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Home }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Hostsallows() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSmbShareResult) []string { return v.Hostsallows }).(pulumi.StringArrayOutput)
}

func (o LookupSmbShareResultOutput) Hostsdenies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSmbShareResult) []string { return v.Hostsdenies }).(pulumi.StringArrayOutput)
}

func (o LookupSmbShareResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSmbShareResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupSmbShareResultOutput) Locked() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Locked }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbShareResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSmbShareResultOutput) Options() GetSmbShareOptionsOutput {
	return o.ApplyT(func(v LookupSmbShareResult) GetSmbShareOptions { return v.Options }).(GetSmbShareOptionsOutput)
}

func (o LookupSmbShareResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbShareResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o LookupSmbShareResultOutput) Purpose() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbShareResult) string { return v.Purpose }).(pulumi.StringOutput)
}

func (o LookupSmbShareResultOutput) Recyclebin() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Recyclebin }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Ro() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Ro }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Streams() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Streams }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) Timemachine() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSmbShareResult) bool { return v.Timemachine }).(pulumi.BoolOutput)
}

func (o LookupSmbShareResultOutput) TimemachineQuota() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSmbShareResult) int { return v.TimemachineQuota }).(pulumi.IntOutput)
}

func (o LookupSmbShareResultOutput) Vuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSmbShareResult) string { return v.Vuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSmbShareResultOutput{})
}
