// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSystemGeneral(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupSystemGeneralResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSystemGeneralResult
	err := ctx.Invoke("truenas:index/getSystemGeneral:getSystemGeneral", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getSystemGeneral.
type LookupSystemGeneralResult struct {
	DsAuth               bool     `pulumi:"dsAuth"`
	Id                   string   `pulumi:"id"`
	Kbdmap               string   `pulumi:"kbdmap"`
	Timezone             string   `pulumi:"timezone"`
	UiAddresses          []string `pulumi:"uiAddresses"`
	UiAllowlists         []string `pulumi:"uiAllowlists"`
	UiCertificate        int      `pulumi:"uiCertificate"`
	UiCertificateName    string   `pulumi:"uiCertificateName"`
	UiConsolemsg         bool     `pulumi:"uiConsolemsg"`
	UiHttpsport          int      `pulumi:"uiHttpsport"`
	UiHttpsprotocols     []string `pulumi:"uiHttpsprotocols"`
	UiHttpsredirect      bool     `pulumi:"uiHttpsredirect"`
	UiPort               int      `pulumi:"uiPort"`
	UiV6addresses        []string `pulumi:"uiV6addresses"`
	UiXFrameOptions      string   `pulumi:"uiXFrameOptions"`
	UsageCollection      bool     `pulumi:"usageCollection"`
	UsageCollectionIsSet bool     `pulumi:"usageCollectionIsSet"`
	Wizardshown          bool     `pulumi:"wizardshown"`
}

func LookupSystemGeneralOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupSystemGeneralResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getSystemGeneral:getSystemGeneral", nil, LookupSystemGeneralResultOutput{}, options).(LookupSystemGeneralResultOutput)
}

// A collection of values returned by getSystemGeneral.
type LookupSystemGeneralResultOutput struct{ *pulumi.OutputState }

func (LookupSystemGeneralResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSystemGeneralResult)(nil)).Elem()
}

func (o LookupSystemGeneralResultOutput) ToLookupSystemGeneralResultOutput() LookupSystemGeneralResultOutput {
	return o
}

func (o LookupSystemGeneralResultOutput) ToLookupSystemGeneralResultOutputWithContext(ctx context.Context) LookupSystemGeneralResultOutput {
	return o
}

func (o LookupSystemGeneralResultOutput) DsAuth() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) bool { return v.DsAuth }).(pulumi.BoolOutput)
}

func (o LookupSystemGeneralResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSystemGeneralResultOutput) Kbdmap() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) string { return v.Kbdmap }).(pulumi.StringOutput)
}

func (o LookupSystemGeneralResultOutput) Timezone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) string { return v.Timezone }).(pulumi.StringOutput)
}

func (o LookupSystemGeneralResultOutput) UiAddresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) []string { return v.UiAddresses }).(pulumi.StringArrayOutput)
}

func (o LookupSystemGeneralResultOutput) UiAllowlists() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) []string { return v.UiAllowlists }).(pulumi.StringArrayOutput)
}

func (o LookupSystemGeneralResultOutput) UiCertificate() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) int { return v.UiCertificate }).(pulumi.IntOutput)
}

func (o LookupSystemGeneralResultOutput) UiCertificateName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) string { return v.UiCertificateName }).(pulumi.StringOutput)
}

func (o LookupSystemGeneralResultOutput) UiConsolemsg() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) bool { return v.UiConsolemsg }).(pulumi.BoolOutput)
}

func (o LookupSystemGeneralResultOutput) UiHttpsport() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) int { return v.UiHttpsport }).(pulumi.IntOutput)
}

func (o LookupSystemGeneralResultOutput) UiHttpsprotocols() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) []string { return v.UiHttpsprotocols }).(pulumi.StringArrayOutput)
}

func (o LookupSystemGeneralResultOutput) UiHttpsredirect() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) bool { return v.UiHttpsredirect }).(pulumi.BoolOutput)
}

func (o LookupSystemGeneralResultOutput) UiPort() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) int { return v.UiPort }).(pulumi.IntOutput)
}

func (o LookupSystemGeneralResultOutput) UiV6addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) []string { return v.UiV6addresses }).(pulumi.StringArrayOutput)
}

func (o LookupSystemGeneralResultOutput) UiXFrameOptions() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) string { return v.UiXFrameOptions }).(pulumi.StringOutput)
}

func (o LookupSystemGeneralResultOutput) UsageCollection() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) bool { return v.UsageCollection }).(pulumi.BoolOutput)
}

func (o LookupSystemGeneralResultOutput) UsageCollectionIsSet() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) bool { return v.UsageCollectionIsSet }).(pulumi.BoolOutput)
}

func (o LookupSystemGeneralResultOutput) Wizardshown() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemGeneralResult) bool { return v.Wizardshown }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSystemGeneralResultOutput{})
}
