// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupTruecommandConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupTruecommandConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTruecommandConfigResult
	err := ctx.Invoke("truenas:index/getTruecommandConfig:getTruecommandConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getTruecommandConfig.
type LookupTruecommandConfigResult struct {
	ApiKey          string `pulumi:"apiKey"`
	Enabled         bool   `pulumi:"enabled"`
	Id              string `pulumi:"id"`
	RemoteIpAddress string `pulumi:"remoteIpAddress"`
	RemoteUrl       string `pulumi:"remoteUrl"`
	Status          string `pulumi:"status"`
	StatusReason    string `pulumi:"statusReason"`
}

func LookupTruecommandConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupTruecommandConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getTruecommandConfig:getTruecommandConfig", nil, LookupTruecommandConfigResultOutput{}, options).(LookupTruecommandConfigResultOutput)
}

// A collection of values returned by getTruecommandConfig.
type LookupTruecommandConfigResultOutput struct{ *pulumi.OutputState }

func (LookupTruecommandConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTruecommandConfigResult)(nil)).Elem()
}

func (o LookupTruecommandConfigResultOutput) ToLookupTruecommandConfigResultOutput() LookupTruecommandConfigResultOutput {
	return o
}

func (o LookupTruecommandConfigResultOutput) ToLookupTruecommandConfigResultOutputWithContext(ctx context.Context) LookupTruecommandConfigResultOutput {
	return o
}

func (o LookupTruecommandConfigResultOutput) ApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTruecommandConfigResult) string { return v.ApiKey }).(pulumi.StringOutput)
}

func (o LookupTruecommandConfigResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTruecommandConfigResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupTruecommandConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTruecommandConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupTruecommandConfigResultOutput) RemoteIpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTruecommandConfigResult) string { return v.RemoteIpAddress }).(pulumi.StringOutput)
}

func (o LookupTruecommandConfigResultOutput) RemoteUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTruecommandConfigResult) string { return v.RemoteUrl }).(pulumi.StringOutput)
}

func (o LookupTruecommandConfigResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTruecommandConfigResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupTruecommandConfigResultOutput) StatusReason() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTruecommandConfigResult) string { return v.StatusReason }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTruecommandConfigResultOutput{})
}
