// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupUpsConfig(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupUpsConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupUpsConfigResult
	err := ctx.Invoke("truenas:index/getUpsConfig:getUpsConfig", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getUpsConfig.
type LookupUpsConfigResult struct {
	CompleteIdentifier string `pulumi:"completeIdentifier"`
	Description        string `pulumi:"description"`
	Driver             string `pulumi:"driver"`
	Extrausers         string `pulumi:"extrausers"`
	Hostsync           int    `pulumi:"hostsync"`
	Id                 string `pulumi:"id"`
	Identifier         string `pulumi:"identifier"`
	Mode               string `pulumi:"mode"`
	Monuser            string `pulumi:"monuser"`
	Nocommwarntime     int    `pulumi:"nocommwarntime"`
	Options            string `pulumi:"options"`
	Optionsupsd        string `pulumi:"optionsupsd"`
	Port               string `pulumi:"port"`
	Powerdown          bool   `pulumi:"powerdown"`
	Remotehost         string `pulumi:"remotehost"`
	Remoteport         int    `pulumi:"remoteport"`
	Rmonitor           bool   `pulumi:"rmonitor"`
	Shutdown           string `pulumi:"shutdown"`
	Shutdowncmd        string `pulumi:"shutdowncmd"`
	Shutdowntimer      int    `pulumi:"shutdowntimer"`
}

func LookupUpsConfigOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupUpsConfigResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getUpsConfig:getUpsConfig", nil, LookupUpsConfigResultOutput{}, options).(LookupUpsConfigResultOutput)
}

// A collection of values returned by getUpsConfig.
type LookupUpsConfigResultOutput struct{ *pulumi.OutputState }

func (LookupUpsConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUpsConfigResult)(nil)).Elem()
}

func (o LookupUpsConfigResultOutput) ToLookupUpsConfigResultOutput() LookupUpsConfigResultOutput {
	return o
}

func (o LookupUpsConfigResultOutput) ToLookupUpsConfigResultOutputWithContext(ctx context.Context) LookupUpsConfigResultOutput {
	return o
}

func (o LookupUpsConfigResultOutput) CompleteIdentifier() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.CompleteIdentifier }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Driver() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Driver }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Extrausers() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Extrausers }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Hostsync() pulumi.IntOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) int { return v.Hostsync }).(pulumi.IntOutput)
}

func (o LookupUpsConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Identifier() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Identifier }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Mode }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Monuser() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Monuser }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Nocommwarntime() pulumi.IntOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) int { return v.Nocommwarntime }).(pulumi.IntOutput)
}

func (o LookupUpsConfigResultOutput) Options() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Options }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Optionsupsd() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Optionsupsd }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Port() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Port }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Powerdown() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) bool { return v.Powerdown }).(pulumi.BoolOutput)
}

func (o LookupUpsConfigResultOutput) Remotehost() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Remotehost }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Remoteport() pulumi.IntOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) int { return v.Remoteport }).(pulumi.IntOutput)
}

func (o LookupUpsConfigResultOutput) Rmonitor() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) bool { return v.Rmonitor }).(pulumi.BoolOutput)
}

func (o LookupUpsConfigResultOutput) Shutdown() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Shutdown }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Shutdowncmd() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) string { return v.Shutdowncmd }).(pulumi.StringOutput)
}

func (o LookupUpsConfigResultOutput) Shutdowntimer() pulumi.IntOutput {
	return o.ApplyT(func(v LookupUpsConfigResult) int { return v.Shutdowntimer }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUpsConfigResultOutput{})
}
