// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupVm(ctx *pulumi.Context, args *LookupVmArgs, opts ...pulumi.InvokeOption) (*LookupVmResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVmResult
	err := ctx.Invoke("truenas:index/getVm:getVm", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVm.
type LookupVmArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getVm.
type LookupVmResult struct {
	ArchType                   string `pulumi:"archType"`
	Autostart                  bool   `pulumi:"autostart"`
	Bootloader                 string `pulumi:"bootloader"`
	BootloaderOvmf             string `pulumi:"bootloaderOvmf"`
	CommandLineArgs            string `pulumi:"commandLineArgs"`
	Cores                      int    `pulumi:"cores"`
	CpuMode                    string `pulumi:"cpuMode"`
	CpuModel                   string `pulumi:"cpuModel"`
	Cpuset                     string `pulumi:"cpuset"`
	Description                string `pulumi:"description"`
	EnableCpuTopologyExtension bool   `pulumi:"enableCpuTopologyExtension"`
	EnableSecureBoot           bool   `pulumi:"enableSecureBoot"`
	HideFromMsr                bool   `pulumi:"hideFromMsr"`
	HypervEnlightenments       bool   `pulumi:"hypervEnlightenments"`
	Id                         int    `pulumi:"id"`
	MachineType                string `pulumi:"machineType"`
	Memory                     int    `pulumi:"memory"`
	MinMemory                  int    `pulumi:"minMemory"`
	Name                       string `pulumi:"name"`
	Nodeset                    string `pulumi:"nodeset"`
	PinVcpus                   bool   `pulumi:"pinVcpus"`
	Running                    bool   `pulumi:"running"`
	ShutdownTimeout            int    `pulumi:"shutdownTimeout"`
	Status                     string `pulumi:"status"`
	SuspendOnSnapshot          bool   `pulumi:"suspendOnSnapshot"`
	Threads                    int    `pulumi:"threads"`
	Time                       string `pulumi:"time"`
	TrustedPlatformModule      bool   `pulumi:"trustedPlatformModule"`
	Vcpus                      int    `pulumi:"vcpus"`
}

func LookupVmOutput(ctx *pulumi.Context, args LookupVmOutputArgs, opts ...pulumi.InvokeOption) LookupVmResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getVm:getVm", args, LookupVmResultOutput{}, options).(LookupVmResultOutput)
}

// A collection of arguments for invoking getVm.
type LookupVmOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupVmOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVmArgs)(nil)).Elem()
}

// A collection of values returned by getVm.
type LookupVmResultOutput struct{ *pulumi.OutputState }

func (LookupVmResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVmResult)(nil)).Elem()
}

func (o LookupVmResultOutput) ToLookupVmResultOutput() LookupVmResultOutput {
	return o
}

func (o LookupVmResultOutput) ToLookupVmResultOutputWithContext(ctx context.Context) LookupVmResultOutput {
	return o
}

func (o LookupVmResultOutput) ArchType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.ArchType }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Autostart() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.Autostart }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) Bootloader() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Bootloader }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) BootloaderOvmf() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.BootloaderOvmf }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) CommandLineArgs() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.CommandLineArgs }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Cores() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.Cores }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) CpuMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.CpuMode }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) CpuModel() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.CpuModel }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Cpuset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Cpuset }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) EnableCpuTopologyExtension() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.EnableCpuTopologyExtension }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) EnableSecureBoot() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.EnableSecureBoot }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) HideFromMsr() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.HideFromMsr }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) HypervEnlightenments() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.HypervEnlightenments }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) MachineType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.MachineType }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Memory() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.Memory }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) MinMemory() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.MinMemory }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) Nodeset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Nodeset }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) PinVcpus() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.PinVcpus }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) Running() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.Running }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) ShutdownTimeout() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.ShutdownTimeout }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) SuspendOnSnapshot() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.SuspendOnSnapshot }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) Threads() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.Threads }).(pulumi.IntOutput)
}

func (o LookupVmResultOutput) Time() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmResult) string { return v.Time }).(pulumi.StringOutput)
}

func (o LookupVmResultOutput) TrustedPlatformModule() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupVmResult) bool { return v.TrustedPlatformModule }).(pulumi.BoolOutput)
}

func (o LookupVmResultOutput) Vcpus() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmResult) int { return v.Vcpus }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVmResultOutput{})
}
