// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupVmDevice(ctx *pulumi.Context, args *LookupVmDeviceArgs, opts ...pulumi.InvokeOption) (*LookupVmDeviceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVmDeviceResult
	err := ctx.Invoke("truenas:index/getVmDevice:getVmDevice", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVmDevice.
type LookupVmDeviceArgs struct {
	Id int `pulumi:"id"`
}

// A collection of values returned by getVmDevice.
type LookupVmDeviceResult struct {
	Attributes string `pulumi:"attributes"`
	Id         int    `pulumi:"id"`
	Order      int    `pulumi:"order"`
	Vm         int    `pulumi:"vm"`
}

func LookupVmDeviceOutput(ctx *pulumi.Context, args LookupVmDeviceOutputArgs, opts ...pulumi.InvokeOption) LookupVmDeviceResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getVmDevice:getVmDevice", args, LookupVmDeviceResultOutput{}, options).(LookupVmDeviceResultOutput)
}

// A collection of arguments for invoking getVmDevice.
type LookupVmDeviceOutputArgs struct {
	Id pulumi.IntInput `pulumi:"id"`
}

func (LookupVmDeviceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVmDeviceArgs)(nil)).Elem()
}

// A collection of values returned by getVmDevice.
type LookupVmDeviceResultOutput struct{ *pulumi.OutputState }

func (LookupVmDeviceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVmDeviceResult)(nil)).Elem()
}

func (o LookupVmDeviceResultOutput) ToLookupVmDeviceResultOutput() LookupVmDeviceResultOutput {
	return o
}

func (o LookupVmDeviceResultOutput) ToLookupVmDeviceResultOutputWithContext(ctx context.Context) LookupVmDeviceResultOutput {
	return o
}

func (o LookupVmDeviceResultOutput) Attributes() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVmDeviceResult) string { return v.Attributes }).(pulumi.StringOutput)
}

func (o LookupVmDeviceResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmDeviceResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupVmDeviceResultOutput) Order() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmDeviceResult) int { return v.Order }).(pulumi.IntOutput)
}

func (o LookupVmDeviceResultOutput) Vm() pulumi.IntOutput {
	return o.ApplyT(func(v LookupVmDeviceResult) int { return v.Vm }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVmDeviceResultOutput{})
}
