// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupWebshare(ctx *pulumi.Context, args *LookupWebshareArgs, opts ...pulumi.InvokeOption) (*LookupWebshareResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupWebshareResult
	err := ctx.Invoke("truenas:index/getWebshare:getWebshare", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getWebshare.
type LookupWebshareArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getWebshare.
type LookupWebshareResult struct {
	Dataset      string `pulumi:"dataset"`
	Enabled      bool   `pulumi:"enabled"`
	Id           int    `pulumi:"id"`
	IsHomeBase   bool   `pulumi:"isHomeBase"`
	Locked       bool   `pulumi:"locked"`
	Name         string `pulumi:"name"`
	Path         string `pulumi:"path"`
	RelativePath string `pulumi:"relativePath"`
}

func LookupWebshareOutput(ctx *pulumi.Context, args LookupWebshareOutputArgs, opts ...pulumi.InvokeOption) LookupWebshareResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getWebshare:getWebshare", args, LookupWebshareResultOutput{}, options).(LookupWebshareResultOutput)
}

// A collection of arguments for invoking getWebshare.
type LookupWebshareOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupWebshareOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupWebshareArgs)(nil)).Elem()
}

// A collection of values returned by getWebshare.
type LookupWebshareResultOutput struct{ *pulumi.OutputState }

func (LookupWebshareResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupWebshareResult)(nil)).Elem()
}

func (o LookupWebshareResultOutput) ToLookupWebshareResultOutput() LookupWebshareResultOutput {
	return o
}

func (o LookupWebshareResultOutput) ToLookupWebshareResultOutputWithContext(ctx context.Context) LookupWebshareResultOutput {
	return o
}

func (o LookupWebshareResultOutput) Dataset() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebshareResult) string { return v.Dataset }).(pulumi.StringOutput)
}

func (o LookupWebshareResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupWebshareResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupWebshareResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v LookupWebshareResult) int { return v.Id }).(pulumi.IntOutput)
}

func (o LookupWebshareResultOutput) IsHomeBase() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupWebshareResult) bool { return v.IsHomeBase }).(pulumi.BoolOutput)
}

func (o LookupWebshareResultOutput) Locked() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupWebshareResult) bool { return v.Locked }).(pulumi.BoolOutput)
}

func (o LookupWebshareResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebshareResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupWebshareResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebshareResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o LookupWebshareResultOutput) RelativePath() pulumi.StringOutput {
	return o.ApplyT(func(v LookupWebshareResult) string { return v.RelativePath }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupWebshareResultOutput{})
}
