// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupZvol(ctx *pulumi.Context, args *LookupZvolArgs, opts ...pulumi.InvokeOption) (*LookupZvolResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupZvolResult
	err := ctx.Invoke("truenas:index/getZvol:getZvol", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZvol.
type LookupZvolArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getZvol.
type LookupZvolResult struct {
	Checksum              string `pulumi:"checksum"`
	Comments              string `pulumi:"comments"`
	Compression           string `pulumi:"compression"`
	Copies                int    `pulumi:"copies"`
	Dedup                 string `pulumi:"dedup"`
	Encrypted             bool   `pulumi:"encrypted"`
	Encryption            bool   `pulumi:"encryption"`
	EncryptionAlgorithm   string `pulumi:"encryptionAlgorithm"`
	EncryptionGenerateKey bool   `pulumi:"encryptionGenerateKey"`
	EncryptionKey         string `pulumi:"encryptionKey"`
	EncryptionPassphrase  string `pulumi:"encryptionPassphrase"`
	Id                    string `pulumi:"id"`
	InheritEncryption     bool   `pulumi:"inheritEncryption"`
	KeyFormat             string `pulumi:"keyFormat"`
	Locked                bool   `pulumi:"locked"`
	Name                  string `pulumi:"name"`
	Pool                  string `pulumi:"pool"`
	Readonly              string `pulumi:"readonly"`
	Refreservation        int    `pulumi:"refreservation"`
	Reservation           int    `pulumi:"reservation"`
	Snapdev               string `pulumi:"snapdev"`
	Sparse                bool   `pulumi:"sparse"`
	Sync                  string `pulumi:"sync"`
	Volblocksize          int    `pulumi:"volblocksize"`
	Volsize               int    `pulumi:"volsize"`
}

func LookupZvolOutput(ctx *pulumi.Context, args LookupZvolOutputArgs, opts ...pulumi.InvokeOption) LookupZvolResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("truenas:index/getZvol:getZvol", args, LookupZvolResultOutput{}, options).(LookupZvolResultOutput)
}

// A collection of arguments for invoking getZvol.
type LookupZvolOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupZvolOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZvolArgs)(nil)).Elem()
}

// A collection of values returned by getZvol.
type LookupZvolResultOutput struct{ *pulumi.OutputState }

func (LookupZvolResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZvolResult)(nil)).Elem()
}

func (o LookupZvolResultOutput) ToLookupZvolResultOutput() LookupZvolResultOutput {
	return o
}

func (o LookupZvolResultOutput) ToLookupZvolResultOutputWithContext(ctx context.Context) LookupZvolResultOutput {
	return o
}

func (o LookupZvolResultOutput) Checksum() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Checksum }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Comments() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Comments }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Compression() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Compression }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Copies() pulumi.IntOutput {
	return o.ApplyT(func(v LookupZvolResult) int { return v.Copies }).(pulumi.IntOutput)
}

func (o LookupZvolResultOutput) Dedup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Dedup }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Encrypted() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZvolResult) bool { return v.Encrypted }).(pulumi.BoolOutput)
}

func (o LookupZvolResultOutput) Encryption() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZvolResult) bool { return v.Encryption }).(pulumi.BoolOutput)
}

func (o LookupZvolResultOutput) EncryptionAlgorithm() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.EncryptionAlgorithm }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) EncryptionGenerateKey() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZvolResult) bool { return v.EncryptionGenerateKey }).(pulumi.BoolOutput)
}

func (o LookupZvolResultOutput) EncryptionKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.EncryptionKey }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) EncryptionPassphrase() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.EncryptionPassphrase }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) InheritEncryption() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZvolResult) bool { return v.InheritEncryption }).(pulumi.BoolOutput)
}

func (o LookupZvolResultOutput) KeyFormat() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.KeyFormat }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Locked() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZvolResult) bool { return v.Locked }).(pulumi.BoolOutput)
}

func (o LookupZvolResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Pool }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Readonly() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Readonly }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Refreservation() pulumi.IntOutput {
	return o.ApplyT(func(v LookupZvolResult) int { return v.Refreservation }).(pulumi.IntOutput)
}

func (o LookupZvolResultOutput) Reservation() pulumi.IntOutput {
	return o.ApplyT(func(v LookupZvolResult) int { return v.Reservation }).(pulumi.IntOutput)
}

func (o LookupZvolResultOutput) Snapdev() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Snapdev }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Sparse() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupZvolResult) bool { return v.Sparse }).(pulumi.BoolOutput)
}

func (o LookupZvolResultOutput) Sync() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZvolResult) string { return v.Sync }).(pulumi.StringOutput)
}

func (o LookupZvolResultOutput) Volblocksize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupZvolResult) int { return v.Volblocksize }).(pulumi.IntOutput)
}

func (o LookupZvolResultOutput) Volsize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupZvolResult) int { return v.Volsize }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupZvolResultOutput{})
}
