// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type IscsiGlobal struct {
	pulumi.CustomResourceState

	// Whether Asymmetric Logical Unit Access (ALUA) is enabled.
	Alua pulumi.BoolOutput `pulumi:"alua"`
	// Base name (iSCSI Qualified Name prefix) used when generating target names.
	Basename pulumi.StringOutput `pulumi:"basename"`
	// Whether iSER (iSCSI Extensions for RDMA) is enabled.
	Iser pulumi.BoolOutput `pulumi:"iser"`
	// List of iSNS server hostnames or IP addresses.
	IsnsServers pulumi.StringArrayOutput `pulumi:"isnsServers"`
	// TCP port the iSCSI service listens on.
	ListenPort pulumi.IntOutput `pulumi:"listenPort"`
	// Percentage of pool free space remaining that triggers a warning alert. A value of 0 clears the threshold (disabled).
	PoolAvailThreshold pulumi.IntOutput `pulumi:"poolAvailThreshold"`
}

// NewIscsiGlobal registers a new resource with the given unique name, arguments, and options.
func NewIscsiGlobal(ctx *pulumi.Context,
	name string, args *IscsiGlobalArgs, opts ...pulumi.ResourceOption) (*IscsiGlobal, error) {
	if args == nil {
		args = &IscsiGlobalArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource IscsiGlobal
	err := ctx.RegisterResource("truenas:index/iscsiGlobal:IscsiGlobal", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIscsiGlobal gets an existing IscsiGlobal resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIscsiGlobal(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IscsiGlobalState, opts ...pulumi.ResourceOption) (*IscsiGlobal, error) {
	var resource IscsiGlobal
	err := ctx.ReadResource("truenas:index/iscsiGlobal:IscsiGlobal", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IscsiGlobal resources.
type iscsiGlobalState struct {
	// Whether Asymmetric Logical Unit Access (ALUA) is enabled.
	Alua *bool `pulumi:"alua"`
	// Base name (iSCSI Qualified Name prefix) used when generating target names.
	Basename *string `pulumi:"basename"`
	// Whether iSER (iSCSI Extensions for RDMA) is enabled.
	Iser *bool `pulumi:"iser"`
	// List of iSNS server hostnames or IP addresses.
	IsnsServers []string `pulumi:"isnsServers"`
	// TCP port the iSCSI service listens on.
	ListenPort *int `pulumi:"listenPort"`
	// Percentage of pool free space remaining that triggers a warning alert. A value of 0 clears the threshold (disabled).
	PoolAvailThreshold *int `pulumi:"poolAvailThreshold"`
}

type IscsiGlobalState struct {
	// Whether Asymmetric Logical Unit Access (ALUA) is enabled.
	Alua pulumi.BoolPtrInput
	// Base name (iSCSI Qualified Name prefix) used when generating target names.
	Basename pulumi.StringPtrInput
	// Whether iSER (iSCSI Extensions for RDMA) is enabled.
	Iser pulumi.BoolPtrInput
	// List of iSNS server hostnames or IP addresses.
	IsnsServers pulumi.StringArrayInput
	// TCP port the iSCSI service listens on.
	ListenPort pulumi.IntPtrInput
	// Percentage of pool free space remaining that triggers a warning alert. A value of 0 clears the threshold (disabled).
	PoolAvailThreshold pulumi.IntPtrInput
}

func (IscsiGlobalState) ElementType() reflect.Type {
	return reflect.TypeOf((*iscsiGlobalState)(nil)).Elem()
}

type iscsiGlobalArgs struct {
	// Whether Asymmetric Logical Unit Access (ALUA) is enabled.
	Alua *bool `pulumi:"alua"`
	// Base name (iSCSI Qualified Name prefix) used when generating target names.
	Basename *string `pulumi:"basename"`
	// Whether iSER (iSCSI Extensions for RDMA) is enabled.
	Iser *bool `pulumi:"iser"`
	// List of iSNS server hostnames or IP addresses.
	IsnsServers []string `pulumi:"isnsServers"`
	// TCP port the iSCSI service listens on.
	ListenPort *int `pulumi:"listenPort"`
	// Percentage of pool free space remaining that triggers a warning alert. A value of 0 clears the threshold (disabled).
	PoolAvailThreshold *int `pulumi:"poolAvailThreshold"`
}

// The set of arguments for constructing a IscsiGlobal resource.
type IscsiGlobalArgs struct {
	// Whether Asymmetric Logical Unit Access (ALUA) is enabled.
	Alua pulumi.BoolPtrInput
	// Base name (iSCSI Qualified Name prefix) used when generating target names.
	Basename pulumi.StringPtrInput
	// Whether iSER (iSCSI Extensions for RDMA) is enabled.
	Iser pulumi.BoolPtrInput
	// List of iSNS server hostnames or IP addresses.
	IsnsServers pulumi.StringArrayInput
	// TCP port the iSCSI service listens on.
	ListenPort pulumi.IntPtrInput
	// Percentage of pool free space remaining that triggers a warning alert. A value of 0 clears the threshold (disabled).
	PoolAvailThreshold pulumi.IntPtrInput
}

func (IscsiGlobalArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*iscsiGlobalArgs)(nil)).Elem()
}

type IscsiGlobalInput interface {
	pulumi.Input

	ToIscsiGlobalOutput() IscsiGlobalOutput
	ToIscsiGlobalOutputWithContext(ctx context.Context) IscsiGlobalOutput
}

func (*IscsiGlobal) ElementType() reflect.Type {
	return reflect.TypeOf((**IscsiGlobal)(nil)).Elem()
}

func (i *IscsiGlobal) ToIscsiGlobalOutput() IscsiGlobalOutput {
	return i.ToIscsiGlobalOutputWithContext(context.Background())
}

func (i *IscsiGlobal) ToIscsiGlobalOutputWithContext(ctx context.Context) IscsiGlobalOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IscsiGlobalOutput)
}

// IscsiGlobalArrayInput is an input type that accepts IscsiGlobalArray and IscsiGlobalArrayOutput values.
// You can construct a concrete instance of `IscsiGlobalArrayInput` via:
//
//	IscsiGlobalArray{ IscsiGlobalArgs{...} }
type IscsiGlobalArrayInput interface {
	pulumi.Input

	ToIscsiGlobalArrayOutput() IscsiGlobalArrayOutput
	ToIscsiGlobalArrayOutputWithContext(context.Context) IscsiGlobalArrayOutput
}

type IscsiGlobalArray []IscsiGlobalInput

func (IscsiGlobalArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IscsiGlobal)(nil)).Elem()
}

func (i IscsiGlobalArray) ToIscsiGlobalArrayOutput() IscsiGlobalArrayOutput {
	return i.ToIscsiGlobalArrayOutputWithContext(context.Background())
}

func (i IscsiGlobalArray) ToIscsiGlobalArrayOutputWithContext(ctx context.Context) IscsiGlobalArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IscsiGlobalArrayOutput)
}

// IscsiGlobalMapInput is an input type that accepts IscsiGlobalMap and IscsiGlobalMapOutput values.
// You can construct a concrete instance of `IscsiGlobalMapInput` via:
//
//	IscsiGlobalMap{ "key": IscsiGlobalArgs{...} }
type IscsiGlobalMapInput interface {
	pulumi.Input

	ToIscsiGlobalMapOutput() IscsiGlobalMapOutput
	ToIscsiGlobalMapOutputWithContext(context.Context) IscsiGlobalMapOutput
}

type IscsiGlobalMap map[string]IscsiGlobalInput

func (IscsiGlobalMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IscsiGlobal)(nil)).Elem()
}

func (i IscsiGlobalMap) ToIscsiGlobalMapOutput() IscsiGlobalMapOutput {
	return i.ToIscsiGlobalMapOutputWithContext(context.Background())
}

func (i IscsiGlobalMap) ToIscsiGlobalMapOutputWithContext(ctx context.Context) IscsiGlobalMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IscsiGlobalMapOutput)
}

type IscsiGlobalOutput struct{ *pulumi.OutputState }

func (IscsiGlobalOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IscsiGlobal)(nil)).Elem()
}

func (o IscsiGlobalOutput) ToIscsiGlobalOutput() IscsiGlobalOutput {
	return o
}

func (o IscsiGlobalOutput) ToIscsiGlobalOutputWithContext(ctx context.Context) IscsiGlobalOutput {
	return o
}

// Whether Asymmetric Logical Unit Access (ALUA) is enabled.
func (o IscsiGlobalOutput) Alua() pulumi.BoolOutput {
	return o.ApplyT(func(v *IscsiGlobal) pulumi.BoolOutput { return v.Alua }).(pulumi.BoolOutput)
}

// Base name (iSCSI Qualified Name prefix) used when generating target names.
func (o IscsiGlobalOutput) Basename() pulumi.StringOutput {
	return o.ApplyT(func(v *IscsiGlobal) pulumi.StringOutput { return v.Basename }).(pulumi.StringOutput)
}

// Whether iSER (iSCSI Extensions for RDMA) is enabled.
func (o IscsiGlobalOutput) Iser() pulumi.BoolOutput {
	return o.ApplyT(func(v *IscsiGlobal) pulumi.BoolOutput { return v.Iser }).(pulumi.BoolOutput)
}

// List of iSNS server hostnames or IP addresses.
func (o IscsiGlobalOutput) IsnsServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *IscsiGlobal) pulumi.StringArrayOutput { return v.IsnsServers }).(pulumi.StringArrayOutput)
}

// TCP port the iSCSI service listens on.
func (o IscsiGlobalOutput) ListenPort() pulumi.IntOutput {
	return o.ApplyT(func(v *IscsiGlobal) pulumi.IntOutput { return v.ListenPort }).(pulumi.IntOutput)
}

// Percentage of pool free space remaining that triggers a warning alert. A value of 0 clears the threshold (disabled).
func (o IscsiGlobalOutput) PoolAvailThreshold() pulumi.IntOutput {
	return o.ApplyT(func(v *IscsiGlobal) pulumi.IntOutput { return v.PoolAvailThreshold }).(pulumi.IntOutput)
}

type IscsiGlobalArrayOutput struct{ *pulumi.OutputState }

func (IscsiGlobalArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IscsiGlobal)(nil)).Elem()
}

func (o IscsiGlobalArrayOutput) ToIscsiGlobalArrayOutput() IscsiGlobalArrayOutput {
	return o
}

func (o IscsiGlobalArrayOutput) ToIscsiGlobalArrayOutputWithContext(ctx context.Context) IscsiGlobalArrayOutput {
	return o
}

func (o IscsiGlobalArrayOutput) Index(i pulumi.IntInput) IscsiGlobalOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IscsiGlobal {
		return vs[0].([]*IscsiGlobal)[vs[1].(int)]
	}).(IscsiGlobalOutput)
}

type IscsiGlobalMapOutput struct{ *pulumi.OutputState }

func (IscsiGlobalMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IscsiGlobal)(nil)).Elem()
}

func (o IscsiGlobalMapOutput) ToIscsiGlobalMapOutput() IscsiGlobalMapOutput {
	return o
}

func (o IscsiGlobalMapOutput) ToIscsiGlobalMapOutputWithContext(ctx context.Context) IscsiGlobalMapOutput {
	return o
}

func (o IscsiGlobalMapOutput) MapIndex(k pulumi.StringInput) IscsiGlobalOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IscsiGlobal {
		return vs[0].(map[string]*IscsiGlobal)[vs[1].(string)]
	}).(IscsiGlobalOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IscsiGlobalInput)(nil)).Elem(), &IscsiGlobal{})
	pulumi.RegisterInputType(reflect.TypeOf((*IscsiGlobalArrayInput)(nil)).Elem(), IscsiGlobalArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IscsiGlobalMapInput)(nil)).Elem(), IscsiGlobalMap{})
	pulumi.RegisterOutputType(IscsiGlobalOutput{})
	pulumi.RegisterOutputType(IscsiGlobalArrayOutput{})
	pulumi.RegisterOutputType(IscsiGlobalMapOutput{})
}
