// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type KerberosRealm struct {
	pulumi.CustomResourceState

	// List of Kerberos admin servers for this realm. If empty (the default), the Kerberos libraries use DNS to look them up.
	AdminServers pulumi.StringArrayOutput `pulumi:"adminServers"`
	// List of Kerberos domain controllers for this realm. If empty (the default), the Kerberos libraries use DNS to look up KDCs.
	Kdcs pulumi.StringArrayOutput `pulumi:"kdcs"`
	// List of Kerberos kpasswd servers for this realm. If empty (the default), DNS is used to look them up if needed.
	KpasswdServers pulumi.StringArrayOutput `pulumi:"kpasswdServers"`
	// The master Kerberos domain controller for this realm, used as a fallback when TrueNAS cannot get credentials because of an invalid password (helpful in hub-and-spoke topologies). Null (the default) if unset.
	PrimaryKdc pulumi.StringOutput `pulumi:"primaryKdc"`
	// Kerberos realm name. External to TrueNAS and case-sensitive; convention is upper-case (e.g. "EXAMPLE.COM"). Updatable in place.
	Realm pulumi.StringOutput `pulumi:"realm"`
}

// NewKerberosRealm registers a new resource with the given unique name, arguments, and options.
func NewKerberosRealm(ctx *pulumi.Context,
	name string, args *KerberosRealmArgs, opts ...pulumi.ResourceOption) (*KerberosRealm, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Realm == nil {
		return nil, errors.New("invalid value for required argument 'Realm'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource KerberosRealm
	err := ctx.RegisterResource("truenas:index/kerberosRealm:KerberosRealm", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKerberosRealm gets an existing KerberosRealm resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKerberosRealm(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KerberosRealmState, opts ...pulumi.ResourceOption) (*KerberosRealm, error) {
	var resource KerberosRealm
	err := ctx.ReadResource("truenas:index/kerberosRealm:KerberosRealm", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering KerberosRealm resources.
type kerberosRealmState struct {
	// List of Kerberos admin servers for this realm. If empty (the default), the Kerberos libraries use DNS to look them up.
	AdminServers []string `pulumi:"adminServers"`
	// List of Kerberos domain controllers for this realm. If empty (the default), the Kerberos libraries use DNS to look up KDCs.
	Kdcs []string `pulumi:"kdcs"`
	// List of Kerberos kpasswd servers for this realm. If empty (the default), DNS is used to look them up if needed.
	KpasswdServers []string `pulumi:"kpasswdServers"`
	// The master Kerberos domain controller for this realm, used as a fallback when TrueNAS cannot get credentials because of an invalid password (helpful in hub-and-spoke topologies). Null (the default) if unset.
	PrimaryKdc *string `pulumi:"primaryKdc"`
	// Kerberos realm name. External to TrueNAS and case-sensitive; convention is upper-case (e.g. "EXAMPLE.COM"). Updatable in place.
	Realm *string `pulumi:"realm"`
}

type KerberosRealmState struct {
	// List of Kerberos admin servers for this realm. If empty (the default), the Kerberos libraries use DNS to look them up.
	AdminServers pulumi.StringArrayInput
	// List of Kerberos domain controllers for this realm. If empty (the default), the Kerberos libraries use DNS to look up KDCs.
	Kdcs pulumi.StringArrayInput
	// List of Kerberos kpasswd servers for this realm. If empty (the default), DNS is used to look them up if needed.
	KpasswdServers pulumi.StringArrayInput
	// The master Kerberos domain controller for this realm, used as a fallback when TrueNAS cannot get credentials because of an invalid password (helpful in hub-and-spoke topologies). Null (the default) if unset.
	PrimaryKdc pulumi.StringPtrInput
	// Kerberos realm name. External to TrueNAS and case-sensitive; convention is upper-case (e.g. "EXAMPLE.COM"). Updatable in place.
	Realm pulumi.StringPtrInput
}

func (KerberosRealmState) ElementType() reflect.Type {
	return reflect.TypeOf((*kerberosRealmState)(nil)).Elem()
}

type kerberosRealmArgs struct {
	// List of Kerberos admin servers for this realm. If empty (the default), the Kerberos libraries use DNS to look them up.
	AdminServers []string `pulumi:"adminServers"`
	// List of Kerberos domain controllers for this realm. If empty (the default), the Kerberos libraries use DNS to look up KDCs.
	Kdcs []string `pulumi:"kdcs"`
	// List of Kerberos kpasswd servers for this realm. If empty (the default), DNS is used to look them up if needed.
	KpasswdServers []string `pulumi:"kpasswdServers"`
	// The master Kerberos domain controller for this realm, used as a fallback when TrueNAS cannot get credentials because of an invalid password (helpful in hub-and-spoke topologies). Null (the default) if unset.
	PrimaryKdc *string `pulumi:"primaryKdc"`
	// Kerberos realm name. External to TrueNAS and case-sensitive; convention is upper-case (e.g. "EXAMPLE.COM"). Updatable in place.
	Realm string `pulumi:"realm"`
}

// The set of arguments for constructing a KerberosRealm resource.
type KerberosRealmArgs struct {
	// List of Kerberos admin servers for this realm. If empty (the default), the Kerberos libraries use DNS to look them up.
	AdminServers pulumi.StringArrayInput
	// List of Kerberos domain controllers for this realm. If empty (the default), the Kerberos libraries use DNS to look up KDCs.
	Kdcs pulumi.StringArrayInput
	// List of Kerberos kpasswd servers for this realm. If empty (the default), DNS is used to look them up if needed.
	KpasswdServers pulumi.StringArrayInput
	// The master Kerberos domain controller for this realm, used as a fallback when TrueNAS cannot get credentials because of an invalid password (helpful in hub-and-spoke topologies). Null (the default) if unset.
	PrimaryKdc pulumi.StringPtrInput
	// Kerberos realm name. External to TrueNAS and case-sensitive; convention is upper-case (e.g. "EXAMPLE.COM"). Updatable in place.
	Realm pulumi.StringInput
}

func (KerberosRealmArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*kerberosRealmArgs)(nil)).Elem()
}

type KerberosRealmInput interface {
	pulumi.Input

	ToKerberosRealmOutput() KerberosRealmOutput
	ToKerberosRealmOutputWithContext(ctx context.Context) KerberosRealmOutput
}

func (*KerberosRealm) ElementType() reflect.Type {
	return reflect.TypeOf((**KerberosRealm)(nil)).Elem()
}

func (i *KerberosRealm) ToKerberosRealmOutput() KerberosRealmOutput {
	return i.ToKerberosRealmOutputWithContext(context.Background())
}

func (i *KerberosRealm) ToKerberosRealmOutputWithContext(ctx context.Context) KerberosRealmOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KerberosRealmOutput)
}

// KerberosRealmArrayInput is an input type that accepts KerberosRealmArray and KerberosRealmArrayOutput values.
// You can construct a concrete instance of `KerberosRealmArrayInput` via:
//
//	KerberosRealmArray{ KerberosRealmArgs{...} }
type KerberosRealmArrayInput interface {
	pulumi.Input

	ToKerberosRealmArrayOutput() KerberosRealmArrayOutput
	ToKerberosRealmArrayOutputWithContext(context.Context) KerberosRealmArrayOutput
}

type KerberosRealmArray []KerberosRealmInput

func (KerberosRealmArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KerberosRealm)(nil)).Elem()
}

func (i KerberosRealmArray) ToKerberosRealmArrayOutput() KerberosRealmArrayOutput {
	return i.ToKerberosRealmArrayOutputWithContext(context.Background())
}

func (i KerberosRealmArray) ToKerberosRealmArrayOutputWithContext(ctx context.Context) KerberosRealmArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KerberosRealmArrayOutput)
}

// KerberosRealmMapInput is an input type that accepts KerberosRealmMap and KerberosRealmMapOutput values.
// You can construct a concrete instance of `KerberosRealmMapInput` via:
//
//	KerberosRealmMap{ "key": KerberosRealmArgs{...} }
type KerberosRealmMapInput interface {
	pulumi.Input

	ToKerberosRealmMapOutput() KerberosRealmMapOutput
	ToKerberosRealmMapOutputWithContext(context.Context) KerberosRealmMapOutput
}

type KerberosRealmMap map[string]KerberosRealmInput

func (KerberosRealmMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KerberosRealm)(nil)).Elem()
}

func (i KerberosRealmMap) ToKerberosRealmMapOutput() KerberosRealmMapOutput {
	return i.ToKerberosRealmMapOutputWithContext(context.Background())
}

func (i KerberosRealmMap) ToKerberosRealmMapOutputWithContext(ctx context.Context) KerberosRealmMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KerberosRealmMapOutput)
}

type KerberosRealmOutput struct{ *pulumi.OutputState }

func (KerberosRealmOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KerberosRealm)(nil)).Elem()
}

func (o KerberosRealmOutput) ToKerberosRealmOutput() KerberosRealmOutput {
	return o
}

func (o KerberosRealmOutput) ToKerberosRealmOutputWithContext(ctx context.Context) KerberosRealmOutput {
	return o
}

// List of Kerberos admin servers for this realm. If empty (the default), the Kerberos libraries use DNS to look them up.
func (o KerberosRealmOutput) AdminServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *KerberosRealm) pulumi.StringArrayOutput { return v.AdminServers }).(pulumi.StringArrayOutput)
}

// List of Kerberos domain controllers for this realm. If empty (the default), the Kerberos libraries use DNS to look up KDCs.
func (o KerberosRealmOutput) Kdcs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *KerberosRealm) pulumi.StringArrayOutput { return v.Kdcs }).(pulumi.StringArrayOutput)
}

// List of Kerberos kpasswd servers for this realm. If empty (the default), DNS is used to look them up if needed.
func (o KerberosRealmOutput) KpasswdServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *KerberosRealm) pulumi.StringArrayOutput { return v.KpasswdServers }).(pulumi.StringArrayOutput)
}

// The master Kerberos domain controller for this realm, used as a fallback when TrueNAS cannot get credentials because of an invalid password (helpful in hub-and-spoke topologies). Null (the default) if unset.
func (o KerberosRealmOutput) PrimaryKdc() pulumi.StringOutput {
	return o.ApplyT(func(v *KerberosRealm) pulumi.StringOutput { return v.PrimaryKdc }).(pulumi.StringOutput)
}

// Kerberos realm name. External to TrueNAS and case-sensitive; convention is upper-case (e.g. "EXAMPLE.COM"). Updatable in place.
func (o KerberosRealmOutput) Realm() pulumi.StringOutput {
	return o.ApplyT(func(v *KerberosRealm) pulumi.StringOutput { return v.Realm }).(pulumi.StringOutput)
}

type KerberosRealmArrayOutput struct{ *pulumi.OutputState }

func (KerberosRealmArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KerberosRealm)(nil)).Elem()
}

func (o KerberosRealmArrayOutput) ToKerberosRealmArrayOutput() KerberosRealmArrayOutput {
	return o
}

func (o KerberosRealmArrayOutput) ToKerberosRealmArrayOutputWithContext(ctx context.Context) KerberosRealmArrayOutput {
	return o
}

func (o KerberosRealmArrayOutput) Index(i pulumi.IntInput) KerberosRealmOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *KerberosRealm {
		return vs[0].([]*KerberosRealm)[vs[1].(int)]
	}).(KerberosRealmOutput)
}

type KerberosRealmMapOutput struct{ *pulumi.OutputState }

func (KerberosRealmMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KerberosRealm)(nil)).Elem()
}

func (o KerberosRealmMapOutput) ToKerberosRealmMapOutput() KerberosRealmMapOutput {
	return o
}

func (o KerberosRealmMapOutput) ToKerberosRealmMapOutputWithContext(ctx context.Context) KerberosRealmMapOutput {
	return o
}

func (o KerberosRealmMapOutput) MapIndex(k pulumi.StringInput) KerberosRealmOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *KerberosRealm {
		return vs[0].(map[string]*KerberosRealm)[vs[1].(string)]
	}).(KerberosRealmOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KerberosRealmInput)(nil)).Elem(), &KerberosRealm{})
	pulumi.RegisterInputType(reflect.TypeOf((*KerberosRealmArrayInput)(nil)).Elem(), KerberosRealmArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KerberosRealmMapInput)(nil)).Elem(), KerberosRealmMap{})
	pulumi.RegisterOutputType(KerberosRealmOutput{})
	pulumi.RegisterOutputType(KerberosRealmArrayOutput{})
	pulumi.RegisterOutputType(KerberosRealmMapOutput{})
}
