// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type KerberosKeytab struct {
	pulumi.CustomResourceState

	// Base64-encoded Kerberos keytab data to merge into the system keytab. Passed through as-is — do not base64-encode it again. Marked Sensitive (kept out of plan/apply output and logs), but — unlike a WriteOnly attribute — it IS stored in Terraform state and IS read back on refresh/import: a live create ><span pulumi-lang-nodejs=" getInstance " pulumi-lang-dotnet=" GetInstance " pulumi-lang-go=" getInstance " pulumi-lang-python=" get_instance " pulumi-lang-yaml=" getInstance " pulumi-lang-java=" getInstance " pulumi-lang-hcl=" get_instance "> getInstance </span>> query > update round trip (using a real keytab exported from a Samba AD domain controller via `samba-tool domain exportkeytab`) showed kerberos.keytab.query/get_instance returning this value byte-for-byte intact, never redacted or omitted, so the normal Sensitive+Computed-free modeling applies rather than the WriteOnly pattern used for genuinely one-way secrets (e.g. truenas_user's password).
	File pulumi.StringOutput `pulumi:"file"`
	// Name of the Kerberos keytab entry. This identifies the keytab entry itself, not the name of any file — it is unrelated to the principal names inside the keytab data. Some names are reserved for internal use (e.g. AD_MACHINE_ACCOUNT, IPA_MACHINE_ACCOUNT). Updatable in place (renaming does not replace the resource).
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewKerberosKeytab registers a new resource with the given unique name, arguments, and options.
func NewKerberosKeytab(ctx *pulumi.Context,
	name string, args *KerberosKeytabArgs, opts ...pulumi.ResourceOption) (*KerberosKeytab, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.File == nil {
		return nil, errors.New("invalid value for required argument 'File'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.File != nil {
		args.File = pulumi.ToSecret(args.File).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"file",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource KerberosKeytab
	err := ctx.RegisterResource("truenas:index/kerberosKeytab:KerberosKeytab", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKerberosKeytab gets an existing KerberosKeytab resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKerberosKeytab(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KerberosKeytabState, opts ...pulumi.ResourceOption) (*KerberosKeytab, error) {
	var resource KerberosKeytab
	err := ctx.ReadResource("truenas:index/kerberosKeytab:KerberosKeytab", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering KerberosKeytab resources.
type kerberosKeytabState struct {
	// Base64-encoded Kerberos keytab data to merge into the system keytab. Passed through as-is — do not base64-encode it again. Marked Sensitive (kept out of plan/apply output and logs), but — unlike a WriteOnly attribute — it IS stored in Terraform state and IS read back on refresh/import: a live create ><span pulumi-lang-nodejs=" getInstance " pulumi-lang-dotnet=" GetInstance " pulumi-lang-go=" getInstance " pulumi-lang-python=" get_instance " pulumi-lang-yaml=" getInstance " pulumi-lang-java=" getInstance " pulumi-lang-hcl=" get_instance "> getInstance </span>> query > update round trip (using a real keytab exported from a Samba AD domain controller via `samba-tool domain exportkeytab`) showed kerberos.keytab.query/get_instance returning this value byte-for-byte intact, never redacted or omitted, so the normal Sensitive+Computed-free modeling applies rather than the WriteOnly pattern used for genuinely one-way secrets (e.g. truenas_user's password).
	File *string `pulumi:"file"`
	// Name of the Kerberos keytab entry. This identifies the keytab entry itself, not the name of any file — it is unrelated to the principal names inside the keytab data. Some names are reserved for internal use (e.g. AD_MACHINE_ACCOUNT, IPA_MACHINE_ACCOUNT). Updatable in place (renaming does not replace the resource).
	Name *string `pulumi:"name"`
}

type KerberosKeytabState struct {
	// Base64-encoded Kerberos keytab data to merge into the system keytab. Passed through as-is — do not base64-encode it again. Marked Sensitive (kept out of plan/apply output and logs), but — unlike a WriteOnly attribute — it IS stored in Terraform state and IS read back on refresh/import: a live create ><span pulumi-lang-nodejs=" getInstance " pulumi-lang-dotnet=" GetInstance " pulumi-lang-go=" getInstance " pulumi-lang-python=" get_instance " pulumi-lang-yaml=" getInstance " pulumi-lang-java=" getInstance " pulumi-lang-hcl=" get_instance "> getInstance </span>> query > update round trip (using a real keytab exported from a Samba AD domain controller via `samba-tool domain exportkeytab`) showed kerberos.keytab.query/get_instance returning this value byte-for-byte intact, never redacted or omitted, so the normal Sensitive+Computed-free modeling applies rather than the WriteOnly pattern used for genuinely one-way secrets (e.g. truenas_user's password).
	File pulumi.StringPtrInput
	// Name of the Kerberos keytab entry. This identifies the keytab entry itself, not the name of any file — it is unrelated to the principal names inside the keytab data. Some names are reserved for internal use (e.g. AD_MACHINE_ACCOUNT, IPA_MACHINE_ACCOUNT). Updatable in place (renaming does not replace the resource).
	Name pulumi.StringPtrInput
}

func (KerberosKeytabState) ElementType() reflect.Type {
	return reflect.TypeOf((*kerberosKeytabState)(nil)).Elem()
}

type kerberosKeytabArgs struct {
	// Base64-encoded Kerberos keytab data to merge into the system keytab. Passed through as-is — do not base64-encode it again. Marked Sensitive (kept out of plan/apply output and logs), but — unlike a WriteOnly attribute — it IS stored in Terraform state and IS read back on refresh/import: a live create ><span pulumi-lang-nodejs=" getInstance " pulumi-lang-dotnet=" GetInstance " pulumi-lang-go=" getInstance " pulumi-lang-python=" get_instance " pulumi-lang-yaml=" getInstance " pulumi-lang-java=" getInstance " pulumi-lang-hcl=" get_instance "> getInstance </span>> query > update round trip (using a real keytab exported from a Samba AD domain controller via `samba-tool domain exportkeytab`) showed kerberos.keytab.query/get_instance returning this value byte-for-byte intact, never redacted or omitted, so the normal Sensitive+Computed-free modeling applies rather than the WriteOnly pattern used for genuinely one-way secrets (e.g. truenas_user's password).
	File string `pulumi:"file"`
	// Name of the Kerberos keytab entry. This identifies the keytab entry itself, not the name of any file — it is unrelated to the principal names inside the keytab data. Some names are reserved for internal use (e.g. AD_MACHINE_ACCOUNT, IPA_MACHINE_ACCOUNT). Updatable in place (renaming does not replace the resource).
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a KerberosKeytab resource.
type KerberosKeytabArgs struct {
	// Base64-encoded Kerberos keytab data to merge into the system keytab. Passed through as-is — do not base64-encode it again. Marked Sensitive (kept out of plan/apply output and logs), but — unlike a WriteOnly attribute — it IS stored in Terraform state and IS read back on refresh/import: a live create ><span pulumi-lang-nodejs=" getInstance " pulumi-lang-dotnet=" GetInstance " pulumi-lang-go=" getInstance " pulumi-lang-python=" get_instance " pulumi-lang-yaml=" getInstance " pulumi-lang-java=" getInstance " pulumi-lang-hcl=" get_instance "> getInstance </span>> query > update round trip (using a real keytab exported from a Samba AD domain controller via `samba-tool domain exportkeytab`) showed kerberos.keytab.query/get_instance returning this value byte-for-byte intact, never redacted or omitted, so the normal Sensitive+Computed-free modeling applies rather than the WriteOnly pattern used for genuinely one-way secrets (e.g. truenas_user's password).
	File pulumi.StringInput
	// Name of the Kerberos keytab entry. This identifies the keytab entry itself, not the name of any file — it is unrelated to the principal names inside the keytab data. Some names are reserved for internal use (e.g. AD_MACHINE_ACCOUNT, IPA_MACHINE_ACCOUNT). Updatable in place (renaming does not replace the resource).
	Name pulumi.StringInput
}

func (KerberosKeytabArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*kerberosKeytabArgs)(nil)).Elem()
}

type KerberosKeytabInput interface {
	pulumi.Input

	ToKerberosKeytabOutput() KerberosKeytabOutput
	ToKerberosKeytabOutputWithContext(ctx context.Context) KerberosKeytabOutput
}

func (*KerberosKeytab) ElementType() reflect.Type {
	return reflect.TypeOf((**KerberosKeytab)(nil)).Elem()
}

func (i *KerberosKeytab) ToKerberosKeytabOutput() KerberosKeytabOutput {
	return i.ToKerberosKeytabOutputWithContext(context.Background())
}

func (i *KerberosKeytab) ToKerberosKeytabOutputWithContext(ctx context.Context) KerberosKeytabOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KerberosKeytabOutput)
}

// KerberosKeytabArrayInput is an input type that accepts KerberosKeytabArray and KerberosKeytabArrayOutput values.
// You can construct a concrete instance of `KerberosKeytabArrayInput` via:
//
//	KerberosKeytabArray{ KerberosKeytabArgs{...} }
type KerberosKeytabArrayInput interface {
	pulumi.Input

	ToKerberosKeytabArrayOutput() KerberosKeytabArrayOutput
	ToKerberosKeytabArrayOutputWithContext(context.Context) KerberosKeytabArrayOutput
}

type KerberosKeytabArray []KerberosKeytabInput

func (KerberosKeytabArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KerberosKeytab)(nil)).Elem()
}

func (i KerberosKeytabArray) ToKerberosKeytabArrayOutput() KerberosKeytabArrayOutput {
	return i.ToKerberosKeytabArrayOutputWithContext(context.Background())
}

func (i KerberosKeytabArray) ToKerberosKeytabArrayOutputWithContext(ctx context.Context) KerberosKeytabArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KerberosKeytabArrayOutput)
}

// KerberosKeytabMapInput is an input type that accepts KerberosKeytabMap and KerberosKeytabMapOutput values.
// You can construct a concrete instance of `KerberosKeytabMapInput` via:
//
//	KerberosKeytabMap{ "key": KerberosKeytabArgs{...} }
type KerberosKeytabMapInput interface {
	pulumi.Input

	ToKerberosKeytabMapOutput() KerberosKeytabMapOutput
	ToKerberosKeytabMapOutputWithContext(context.Context) KerberosKeytabMapOutput
}

type KerberosKeytabMap map[string]KerberosKeytabInput

func (KerberosKeytabMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KerberosKeytab)(nil)).Elem()
}

func (i KerberosKeytabMap) ToKerberosKeytabMapOutput() KerberosKeytabMapOutput {
	return i.ToKerberosKeytabMapOutputWithContext(context.Background())
}

func (i KerberosKeytabMap) ToKerberosKeytabMapOutputWithContext(ctx context.Context) KerberosKeytabMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KerberosKeytabMapOutput)
}

type KerberosKeytabOutput struct{ *pulumi.OutputState }

func (KerberosKeytabOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KerberosKeytab)(nil)).Elem()
}

func (o KerberosKeytabOutput) ToKerberosKeytabOutput() KerberosKeytabOutput {
	return o
}

func (o KerberosKeytabOutput) ToKerberosKeytabOutputWithContext(ctx context.Context) KerberosKeytabOutput {
	return o
}

// Base64-encoded Kerberos keytab data to merge into the system keytab. Passed through as-is — do not base64-encode it again. Marked Sensitive (kept out of plan/apply output and logs), but — unlike a WriteOnly attribute — it IS stored in Terraform state and IS read back on refresh/import: a live create ><span pulumi-lang-nodejs=" getInstance " pulumi-lang-dotnet=" GetInstance " pulumi-lang-go=" getInstance " pulumi-lang-python=" get_instance " pulumi-lang-yaml=" getInstance " pulumi-lang-java=" getInstance " pulumi-lang-hcl=" get_instance "> getInstance </span>> query > update round trip (using a real keytab exported from a Samba AD domain controller via `samba-tool domain exportkeytab`) showed kerberos.keytab.query/get_instance returning this value byte-for-byte intact, never redacted or omitted, so the normal Sensitive+Computed-free modeling applies rather than the WriteOnly pattern used for genuinely one-way secrets (e.g. truenas_user's password).
func (o KerberosKeytabOutput) File() pulumi.StringOutput {
	return o.ApplyT(func(v *KerberosKeytab) pulumi.StringOutput { return v.File }).(pulumi.StringOutput)
}

// Name of the Kerberos keytab entry. This identifies the keytab entry itself, not the name of any file — it is unrelated to the principal names inside the keytab data. Some names are reserved for internal use (e.g. AD_MACHINE_ACCOUNT, IPA_MACHINE_ACCOUNT). Updatable in place (renaming does not replace the resource).
func (o KerberosKeytabOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *KerberosKeytab) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type KerberosKeytabArrayOutput struct{ *pulumi.OutputState }

func (KerberosKeytabArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KerberosKeytab)(nil)).Elem()
}

func (o KerberosKeytabArrayOutput) ToKerberosKeytabArrayOutput() KerberosKeytabArrayOutput {
	return o
}

func (o KerberosKeytabArrayOutput) ToKerberosKeytabArrayOutputWithContext(ctx context.Context) KerberosKeytabArrayOutput {
	return o
}

func (o KerberosKeytabArrayOutput) Index(i pulumi.IntInput) KerberosKeytabOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *KerberosKeytab {
		return vs[0].([]*KerberosKeytab)[vs[1].(int)]
	}).(KerberosKeytabOutput)
}

type KerberosKeytabMapOutput struct{ *pulumi.OutputState }

func (KerberosKeytabMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KerberosKeytab)(nil)).Elem()
}

func (o KerberosKeytabMapOutput) ToKerberosKeytabMapOutput() KerberosKeytabMapOutput {
	return o
}

func (o KerberosKeytabMapOutput) ToKerberosKeytabMapOutputWithContext(ctx context.Context) KerberosKeytabMapOutput {
	return o
}

func (o KerberosKeytabMapOutput) MapIndex(k pulumi.StringInput) KerberosKeytabOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *KerberosKeytab {
		return vs[0].(map[string]*KerberosKeytab)[vs[1].(string)]
	}).(KerberosKeytabOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KerberosKeytabInput)(nil)).Elem(), &KerberosKeytab{})
	pulumi.RegisterInputType(reflect.TypeOf((*KerberosKeytabArrayInput)(nil)).Elem(), KerberosKeytabArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KerberosKeytabMapInput)(nil)).Elem(), KerberosKeytabMap{})
	pulumi.RegisterOutputType(KerberosKeytabOutput{})
	pulumi.RegisterOutputType(KerberosKeytabArrayOutput{})
	pulumi.RegisterOutputType(KerberosKeytabMapOutput{})
}
