// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Mail struct {
	pulumi.CustomResourceState

	// "From" address used on outgoing mail.
	Fromemail pulumi.StringOutput `pulumi:"fromemail"`
	// "From" display name used on outgoing mail.
	Fromname pulumi.StringOutput `pulumi:"fromname"`
	// Outgoing SMTP server hostname.
	Outgoingserver pulumi.StringOutput `pulumi:"outgoingserver"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// SMTP authentication password (never read back from TrueNAS). Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Pass pulumi.StringPtrOutput `pulumi:"pass"`
	// Outgoing SMTP server port.
	Port pulumi.IntOutput `pulumi:"port"`
	// SMTP transport security: one of PLAIN, SSL, TLS.
	Security pulumi.StringOutput `pulumi:"security"`
	// Whether SMTP authentication is enabled.
	Smtp pulumi.BoolOutput `pulumi:"smtp"`
	// SMTP authentication username.
	User pulumi.StringOutput `pulumi:"user"`
}

// NewMail registers a new resource with the given unique name, arguments, and options.
func NewMail(ctx *pulumi.Context,
	name string, args *MailArgs, opts ...pulumi.ResourceOption) (*Mail, error) {
	if args == nil {
		args = &MailArgs{}
	}

	if args.Pass != nil {
		args.Pass = pulumi.ToSecret(args.Pass).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"pass",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Mail
	err := ctx.RegisterResource("truenas:index/mail:Mail", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMail gets an existing Mail resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMail(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MailState, opts ...pulumi.ResourceOption) (*Mail, error) {
	var resource Mail
	err := ctx.ReadResource("truenas:index/mail:Mail", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Mail resources.
type mailState struct {
	// "From" address used on outgoing mail.
	Fromemail *string `pulumi:"fromemail"`
	// "From" display name used on outgoing mail.
	Fromname *string `pulumi:"fromname"`
	// Outgoing SMTP server hostname.
	Outgoingserver *string `pulumi:"outgoingserver"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// SMTP authentication password (never read back from TrueNAS). Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Pass *string `pulumi:"pass"`
	// Outgoing SMTP server port.
	Port *int `pulumi:"port"`
	// SMTP transport security: one of PLAIN, SSL, TLS.
	Security *string `pulumi:"security"`
	// Whether SMTP authentication is enabled.
	Smtp *bool `pulumi:"smtp"`
	// SMTP authentication username.
	User *string `pulumi:"user"`
}

type MailState struct {
	// "From" address used on outgoing mail.
	Fromemail pulumi.StringPtrInput
	// "From" display name used on outgoing mail.
	Fromname pulumi.StringPtrInput
	// Outgoing SMTP server hostname.
	Outgoingserver pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// SMTP authentication password (never read back from TrueNAS). Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Pass pulumi.StringPtrInput
	// Outgoing SMTP server port.
	Port pulumi.IntPtrInput
	// SMTP transport security: one of PLAIN, SSL, TLS.
	Security pulumi.StringPtrInput
	// Whether SMTP authentication is enabled.
	Smtp pulumi.BoolPtrInput
	// SMTP authentication username.
	User pulumi.StringPtrInput
}

func (MailState) ElementType() reflect.Type {
	return reflect.TypeOf((*mailState)(nil)).Elem()
}

type mailArgs struct {
	// "From" address used on outgoing mail.
	Fromemail *string `pulumi:"fromemail"`
	// "From" display name used on outgoing mail.
	Fromname *string `pulumi:"fromname"`
	// Outgoing SMTP server hostname.
	Outgoingserver *string `pulumi:"outgoingserver"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// SMTP authentication password (never read back from TrueNAS). Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Pass *string `pulumi:"pass"`
	// Outgoing SMTP server port.
	Port *int `pulumi:"port"`
	// SMTP transport security: one of PLAIN, SSL, TLS.
	Security *string `pulumi:"security"`
	// Whether SMTP authentication is enabled.
	Smtp *bool `pulumi:"smtp"`
	// SMTP authentication username.
	User *string `pulumi:"user"`
}

// The set of arguments for constructing a Mail resource.
type MailArgs struct {
	// "From" address used on outgoing mail.
	Fromemail pulumi.StringPtrInput
	// "From" display name used on outgoing mail.
	Fromname pulumi.StringPtrInput
	// Outgoing SMTP server hostname.
	Outgoingserver pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// SMTP authentication password (never read back from TrueNAS). Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Pass pulumi.StringPtrInput
	// Outgoing SMTP server port.
	Port pulumi.IntPtrInput
	// SMTP transport security: one of PLAIN, SSL, TLS.
	Security pulumi.StringPtrInput
	// Whether SMTP authentication is enabled.
	Smtp pulumi.BoolPtrInput
	// SMTP authentication username.
	User pulumi.StringPtrInput
}

func (MailArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*mailArgs)(nil)).Elem()
}

type MailInput interface {
	pulumi.Input

	ToMailOutput() MailOutput
	ToMailOutputWithContext(ctx context.Context) MailOutput
}

func (*Mail) ElementType() reflect.Type {
	return reflect.TypeOf((**Mail)(nil)).Elem()
}

func (i *Mail) ToMailOutput() MailOutput {
	return i.ToMailOutputWithContext(context.Background())
}

func (i *Mail) ToMailOutputWithContext(ctx context.Context) MailOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MailOutput)
}

// MailArrayInput is an input type that accepts MailArray and MailArrayOutput values.
// You can construct a concrete instance of `MailArrayInput` via:
//
//	MailArray{ MailArgs{...} }
type MailArrayInput interface {
	pulumi.Input

	ToMailArrayOutput() MailArrayOutput
	ToMailArrayOutputWithContext(context.Context) MailArrayOutput
}

type MailArray []MailInput

func (MailArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Mail)(nil)).Elem()
}

func (i MailArray) ToMailArrayOutput() MailArrayOutput {
	return i.ToMailArrayOutputWithContext(context.Background())
}

func (i MailArray) ToMailArrayOutputWithContext(ctx context.Context) MailArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MailArrayOutput)
}

// MailMapInput is an input type that accepts MailMap and MailMapOutput values.
// You can construct a concrete instance of `MailMapInput` via:
//
//	MailMap{ "key": MailArgs{...} }
type MailMapInput interface {
	pulumi.Input

	ToMailMapOutput() MailMapOutput
	ToMailMapOutputWithContext(context.Context) MailMapOutput
}

type MailMap map[string]MailInput

func (MailMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Mail)(nil)).Elem()
}

func (i MailMap) ToMailMapOutput() MailMapOutput {
	return i.ToMailMapOutputWithContext(context.Background())
}

func (i MailMap) ToMailMapOutputWithContext(ctx context.Context) MailMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MailMapOutput)
}

type MailOutput struct{ *pulumi.OutputState }

func (MailOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Mail)(nil)).Elem()
}

func (o MailOutput) ToMailOutput() MailOutput {
	return o
}

func (o MailOutput) ToMailOutputWithContext(ctx context.Context) MailOutput {
	return o
}

// "From" address used on outgoing mail.
func (o MailOutput) Fromemail() pulumi.StringOutput {
	return o.ApplyT(func(v *Mail) pulumi.StringOutput { return v.Fromemail }).(pulumi.StringOutput)
}

// "From" display name used on outgoing mail.
func (o MailOutput) Fromname() pulumi.StringOutput {
	return o.ApplyT(func(v *Mail) pulumi.StringOutput { return v.Fromname }).(pulumi.StringOutput)
}

// Outgoing SMTP server hostname.
func (o MailOutput) Outgoingserver() pulumi.StringOutput {
	return o.ApplyT(func(v *Mail) pulumi.StringOutput { return v.Outgoingserver }).(pulumi.StringOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// SMTP authentication password (never read back from TrueNAS). Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
func (o MailOutput) Pass() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Mail) pulumi.StringPtrOutput { return v.Pass }).(pulumi.StringPtrOutput)
}

// Outgoing SMTP server port.
func (o MailOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v *Mail) pulumi.IntOutput { return v.Port }).(pulumi.IntOutput)
}

// SMTP transport security: one of PLAIN, SSL, TLS.
func (o MailOutput) Security() pulumi.StringOutput {
	return o.ApplyT(func(v *Mail) pulumi.StringOutput { return v.Security }).(pulumi.StringOutput)
}

// Whether SMTP authentication is enabled.
func (o MailOutput) Smtp() pulumi.BoolOutput {
	return o.ApplyT(func(v *Mail) pulumi.BoolOutput { return v.Smtp }).(pulumi.BoolOutput)
}

// SMTP authentication username.
func (o MailOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v *Mail) pulumi.StringOutput { return v.User }).(pulumi.StringOutput)
}

type MailArrayOutput struct{ *pulumi.OutputState }

func (MailArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Mail)(nil)).Elem()
}

func (o MailArrayOutput) ToMailArrayOutput() MailArrayOutput {
	return o
}

func (o MailArrayOutput) ToMailArrayOutputWithContext(ctx context.Context) MailArrayOutput {
	return o
}

func (o MailArrayOutput) Index(i pulumi.IntInput) MailOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Mail {
		return vs[0].([]*Mail)[vs[1].(int)]
	}).(MailOutput)
}

type MailMapOutput struct{ *pulumi.OutputState }

func (MailMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Mail)(nil)).Elem()
}

func (o MailMapOutput) ToMailMapOutput() MailMapOutput {
	return o
}

func (o MailMapOutput) ToMailMapOutputWithContext(ctx context.Context) MailMapOutput {
	return o
}

func (o MailMapOutput) MapIndex(k pulumi.StringInput) MailOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Mail {
		return vs[0].(map[string]*Mail)[vs[1].(string)]
	}).(MailOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MailInput)(nil)).Elem(), &Mail{})
	pulumi.RegisterInputType(reflect.TypeOf((*MailArrayInput)(nil)).Elem(), MailArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MailMapInput)(nil)).Elem(), MailMap{})
	pulumi.RegisterOutputType(MailOutput{})
	pulumi.RegisterOutputType(MailArrayOutput{})
	pulumi.RegisterOutputType(MailMapOutput{})
}
