// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NtpServer struct {
	pulumi.CustomResourceState

	// Hostname or IP address of the NTP server.
	Address pulumi.StringOutput `pulumi:"address"`
	// Send a burst of packets when the server is reachable, improving initial synchronization.
	Burst pulumi.BoolOutput `pulumi:"burst"`
	// Bypass validation that checks whether the server is reachable. Write-only: not stored, not read back.
	Force pulumi.BoolPtrOutput `pulumi:"force"`
	// Send a burst of packets when the server is unreachable, speeding up initial synchronization.
	Iburst pulumi.BoolOutput `pulumi:"iburst"`
	// Maximum polling interval, as a power of 2 in seconds.
	Maxpoll pulumi.IntOutput `pulumi:"maxpoll"`
	// Minimum polling interval, as a power of 2 in seconds.
	Minpoll pulumi.IntOutput `pulumi:"minpoll"`
	// Prefer this server over other configured NTP servers.
	Prefer pulumi.BoolOutput `pulumi:"prefer"`
}

// NewNtpServer registers a new resource with the given unique name, arguments, and options.
func NewNtpServer(ctx *pulumi.Context,
	name string, args *NtpServerArgs, opts ...pulumi.ResourceOption) (*NtpServer, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NtpServer
	err := ctx.RegisterResource("truenas:index/ntpServer:NtpServer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNtpServer gets an existing NtpServer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNtpServer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NtpServerState, opts ...pulumi.ResourceOption) (*NtpServer, error) {
	var resource NtpServer
	err := ctx.ReadResource("truenas:index/ntpServer:NtpServer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NtpServer resources.
type ntpServerState struct {
	// Hostname or IP address of the NTP server.
	Address *string `pulumi:"address"`
	// Send a burst of packets when the server is reachable, improving initial synchronization.
	Burst *bool `pulumi:"burst"`
	// Bypass validation that checks whether the server is reachable. Write-only: not stored, not read back.
	Force *bool `pulumi:"force"`
	// Send a burst of packets when the server is unreachable, speeding up initial synchronization.
	Iburst *bool `pulumi:"iburst"`
	// Maximum polling interval, as a power of 2 in seconds.
	Maxpoll *int `pulumi:"maxpoll"`
	// Minimum polling interval, as a power of 2 in seconds.
	Minpoll *int `pulumi:"minpoll"`
	// Prefer this server over other configured NTP servers.
	Prefer *bool `pulumi:"prefer"`
}

type NtpServerState struct {
	// Hostname or IP address of the NTP server.
	Address pulumi.StringPtrInput
	// Send a burst of packets when the server is reachable, improving initial synchronization.
	Burst pulumi.BoolPtrInput
	// Bypass validation that checks whether the server is reachable. Write-only: not stored, not read back.
	Force pulumi.BoolPtrInput
	// Send a burst of packets when the server is unreachable, speeding up initial synchronization.
	Iburst pulumi.BoolPtrInput
	// Maximum polling interval, as a power of 2 in seconds.
	Maxpoll pulumi.IntPtrInput
	// Minimum polling interval, as a power of 2 in seconds.
	Minpoll pulumi.IntPtrInput
	// Prefer this server over other configured NTP servers.
	Prefer pulumi.BoolPtrInput
}

func (NtpServerState) ElementType() reflect.Type {
	return reflect.TypeOf((*ntpServerState)(nil)).Elem()
}

type ntpServerArgs struct {
	// Hostname or IP address of the NTP server.
	Address string `pulumi:"address"`
	// Send a burst of packets when the server is reachable, improving initial synchronization.
	Burst *bool `pulumi:"burst"`
	// Bypass validation that checks whether the server is reachable. Write-only: not stored, not read back.
	Force *bool `pulumi:"force"`
	// Send a burst of packets when the server is unreachable, speeding up initial synchronization.
	Iburst *bool `pulumi:"iburst"`
	// Maximum polling interval, as a power of 2 in seconds.
	Maxpoll *int `pulumi:"maxpoll"`
	// Minimum polling interval, as a power of 2 in seconds.
	Minpoll *int `pulumi:"minpoll"`
	// Prefer this server over other configured NTP servers.
	Prefer *bool `pulumi:"prefer"`
}

// The set of arguments for constructing a NtpServer resource.
type NtpServerArgs struct {
	// Hostname or IP address of the NTP server.
	Address pulumi.StringInput
	// Send a burst of packets when the server is reachable, improving initial synchronization.
	Burst pulumi.BoolPtrInput
	// Bypass validation that checks whether the server is reachable. Write-only: not stored, not read back.
	Force pulumi.BoolPtrInput
	// Send a burst of packets when the server is unreachable, speeding up initial synchronization.
	Iburst pulumi.BoolPtrInput
	// Maximum polling interval, as a power of 2 in seconds.
	Maxpoll pulumi.IntPtrInput
	// Minimum polling interval, as a power of 2 in seconds.
	Minpoll pulumi.IntPtrInput
	// Prefer this server over other configured NTP servers.
	Prefer pulumi.BoolPtrInput
}

func (NtpServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ntpServerArgs)(nil)).Elem()
}

type NtpServerInput interface {
	pulumi.Input

	ToNtpServerOutput() NtpServerOutput
	ToNtpServerOutputWithContext(ctx context.Context) NtpServerOutput
}

func (*NtpServer) ElementType() reflect.Type {
	return reflect.TypeOf((**NtpServer)(nil)).Elem()
}

func (i *NtpServer) ToNtpServerOutput() NtpServerOutput {
	return i.ToNtpServerOutputWithContext(context.Background())
}

func (i *NtpServer) ToNtpServerOutputWithContext(ctx context.Context) NtpServerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NtpServerOutput)
}

// NtpServerArrayInput is an input type that accepts NtpServerArray and NtpServerArrayOutput values.
// You can construct a concrete instance of `NtpServerArrayInput` via:
//
//	NtpServerArray{ NtpServerArgs{...} }
type NtpServerArrayInput interface {
	pulumi.Input

	ToNtpServerArrayOutput() NtpServerArrayOutput
	ToNtpServerArrayOutputWithContext(context.Context) NtpServerArrayOutput
}

type NtpServerArray []NtpServerInput

func (NtpServerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NtpServer)(nil)).Elem()
}

func (i NtpServerArray) ToNtpServerArrayOutput() NtpServerArrayOutput {
	return i.ToNtpServerArrayOutputWithContext(context.Background())
}

func (i NtpServerArray) ToNtpServerArrayOutputWithContext(ctx context.Context) NtpServerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NtpServerArrayOutput)
}

// NtpServerMapInput is an input type that accepts NtpServerMap and NtpServerMapOutput values.
// You can construct a concrete instance of `NtpServerMapInput` via:
//
//	NtpServerMap{ "key": NtpServerArgs{...} }
type NtpServerMapInput interface {
	pulumi.Input

	ToNtpServerMapOutput() NtpServerMapOutput
	ToNtpServerMapOutputWithContext(context.Context) NtpServerMapOutput
}

type NtpServerMap map[string]NtpServerInput

func (NtpServerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NtpServer)(nil)).Elem()
}

func (i NtpServerMap) ToNtpServerMapOutput() NtpServerMapOutput {
	return i.ToNtpServerMapOutputWithContext(context.Background())
}

func (i NtpServerMap) ToNtpServerMapOutputWithContext(ctx context.Context) NtpServerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NtpServerMapOutput)
}

type NtpServerOutput struct{ *pulumi.OutputState }

func (NtpServerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NtpServer)(nil)).Elem()
}

func (o NtpServerOutput) ToNtpServerOutput() NtpServerOutput {
	return o
}

func (o NtpServerOutput) ToNtpServerOutputWithContext(ctx context.Context) NtpServerOutput {
	return o
}

// Hostname or IP address of the NTP server.
func (o NtpServerOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *NtpServer) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// Send a burst of packets when the server is reachable, improving initial synchronization.
func (o NtpServerOutput) Burst() pulumi.BoolOutput {
	return o.ApplyT(func(v *NtpServer) pulumi.BoolOutput { return v.Burst }).(pulumi.BoolOutput)
}

// Bypass validation that checks whether the server is reachable. Write-only: not stored, not read back.
func (o NtpServerOutput) Force() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NtpServer) pulumi.BoolPtrOutput { return v.Force }).(pulumi.BoolPtrOutput)
}

// Send a burst of packets when the server is unreachable, speeding up initial synchronization.
func (o NtpServerOutput) Iburst() pulumi.BoolOutput {
	return o.ApplyT(func(v *NtpServer) pulumi.BoolOutput { return v.Iburst }).(pulumi.BoolOutput)
}

// Maximum polling interval, as a power of 2 in seconds.
func (o NtpServerOutput) Maxpoll() pulumi.IntOutput {
	return o.ApplyT(func(v *NtpServer) pulumi.IntOutput { return v.Maxpoll }).(pulumi.IntOutput)
}

// Minimum polling interval, as a power of 2 in seconds.
func (o NtpServerOutput) Minpoll() pulumi.IntOutput {
	return o.ApplyT(func(v *NtpServer) pulumi.IntOutput { return v.Minpoll }).(pulumi.IntOutput)
}

// Prefer this server over other configured NTP servers.
func (o NtpServerOutput) Prefer() pulumi.BoolOutput {
	return o.ApplyT(func(v *NtpServer) pulumi.BoolOutput { return v.Prefer }).(pulumi.BoolOutput)
}

type NtpServerArrayOutput struct{ *pulumi.OutputState }

func (NtpServerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NtpServer)(nil)).Elem()
}

func (o NtpServerArrayOutput) ToNtpServerArrayOutput() NtpServerArrayOutput {
	return o
}

func (o NtpServerArrayOutput) ToNtpServerArrayOutputWithContext(ctx context.Context) NtpServerArrayOutput {
	return o
}

func (o NtpServerArrayOutput) Index(i pulumi.IntInput) NtpServerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NtpServer {
		return vs[0].([]*NtpServer)[vs[1].(int)]
	}).(NtpServerOutput)
}

type NtpServerMapOutput struct{ *pulumi.OutputState }

func (NtpServerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NtpServer)(nil)).Elem()
}

func (o NtpServerMapOutput) ToNtpServerMapOutput() NtpServerMapOutput {
	return o
}

func (o NtpServerMapOutput) ToNtpServerMapOutputWithContext(ctx context.Context) NtpServerMapOutput {
	return o
}

func (o NtpServerMapOutput) MapIndex(k pulumi.StringInput) NtpServerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NtpServer {
		return vs[0].(map[string]*NtpServer)[vs[1].(string)]
	}).(NtpServerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NtpServerInput)(nil)).Elem(), &NtpServer{})
	pulumi.RegisterInputType(reflect.TypeOf((*NtpServerArrayInput)(nil)).Elem(), NtpServerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NtpServerMapInput)(nil)).Elem(), NtpServerMap{})
	pulumi.RegisterOutputType(NtpServerOutput{})
	pulumi.RegisterOutputType(NtpServerArrayOutput{})
	pulumi.RegisterOutputType(NtpServerMapOutput{})
}
