// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NvmetSubsys struct {
	pulumi.CustomResourceState

	// Allow any host to connect to this subsystem without an explicit host mapping.
	AllowAnyHost pulumi.BoolOutput `pulumi:"allowAnyHost"`
	// Enable Asymmetric Namespace Access (ANA) for this subsystem.
	Ana pulumi.BoolOutput `pulumi:"ana"`
	// IEEE Organizationally Unique Identifier used when generating namespace identifiers.
	IeeeOui pulumi.StringOutput `pulumi:"ieeeOui"`
	// Name of the NVMe-oF subsystem.
	Name pulumi.StringOutput `pulumi:"name"`
	// Enable end-to-end data protection (PI) for this subsystem.
	PiEnable pulumi.BoolOutput `pulumi:"piEnable"`
	// Maximum number of queues supported by this subsystem.
	QidMax pulumi.IntOutput `pulumi:"qidMax"`
	// Serial number assigned by TrueNAS.
	Serial pulumi.StringOutput `pulumi:"serial"`
	// NVMe Qualified Name (NQN) for the subsystem. Derived by TrueNAS when unset.
	Subnqn pulumi.StringOutput `pulumi:"subnqn"`
}

// NewNvmetSubsys registers a new resource with the given unique name, arguments, and options.
func NewNvmetSubsys(ctx *pulumi.Context,
	name string, args *NvmetSubsysArgs, opts ...pulumi.ResourceOption) (*NvmetSubsys, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NvmetSubsys
	err := ctx.RegisterResource("truenas:index/nvmetSubsys:NvmetSubsys", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNvmetSubsys gets an existing NvmetSubsys resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNvmetSubsys(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NvmetSubsysState, opts ...pulumi.ResourceOption) (*NvmetSubsys, error) {
	var resource NvmetSubsys
	err := ctx.ReadResource("truenas:index/nvmetSubsys:NvmetSubsys", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NvmetSubsys resources.
type nvmetSubsysState struct {
	// Allow any host to connect to this subsystem without an explicit host mapping.
	AllowAnyHost *bool `pulumi:"allowAnyHost"`
	// Enable Asymmetric Namespace Access (ANA) for this subsystem.
	Ana *bool `pulumi:"ana"`
	// IEEE Organizationally Unique Identifier used when generating namespace identifiers.
	IeeeOui *string `pulumi:"ieeeOui"`
	// Name of the NVMe-oF subsystem.
	Name *string `pulumi:"name"`
	// Enable end-to-end data protection (PI) for this subsystem.
	PiEnable *bool `pulumi:"piEnable"`
	// Maximum number of queues supported by this subsystem.
	QidMax *int `pulumi:"qidMax"`
	// Serial number assigned by TrueNAS.
	Serial *string `pulumi:"serial"`
	// NVMe Qualified Name (NQN) for the subsystem. Derived by TrueNAS when unset.
	Subnqn *string `pulumi:"subnqn"`
}

type NvmetSubsysState struct {
	// Allow any host to connect to this subsystem without an explicit host mapping.
	AllowAnyHost pulumi.BoolPtrInput
	// Enable Asymmetric Namespace Access (ANA) for this subsystem.
	Ana pulumi.BoolPtrInput
	// IEEE Organizationally Unique Identifier used when generating namespace identifiers.
	IeeeOui pulumi.StringPtrInput
	// Name of the NVMe-oF subsystem.
	Name pulumi.StringPtrInput
	// Enable end-to-end data protection (PI) for this subsystem.
	PiEnable pulumi.BoolPtrInput
	// Maximum number of queues supported by this subsystem.
	QidMax pulumi.IntPtrInput
	// Serial number assigned by TrueNAS.
	Serial pulumi.StringPtrInput
	// NVMe Qualified Name (NQN) for the subsystem. Derived by TrueNAS when unset.
	Subnqn pulumi.StringPtrInput
}

func (NvmetSubsysState) ElementType() reflect.Type {
	return reflect.TypeOf((*nvmetSubsysState)(nil)).Elem()
}

type nvmetSubsysArgs struct {
	// Allow any host to connect to this subsystem without an explicit host mapping.
	AllowAnyHost *bool `pulumi:"allowAnyHost"`
	// Enable Asymmetric Namespace Access (ANA) for this subsystem.
	Ana *bool `pulumi:"ana"`
	// IEEE Organizationally Unique Identifier used when generating namespace identifiers.
	IeeeOui *string `pulumi:"ieeeOui"`
	// Name of the NVMe-oF subsystem.
	Name string `pulumi:"name"`
	// Enable end-to-end data protection (PI) for this subsystem.
	PiEnable *bool `pulumi:"piEnable"`
	// Maximum number of queues supported by this subsystem.
	QidMax *int `pulumi:"qidMax"`
	// NVMe Qualified Name (NQN) for the subsystem. Derived by TrueNAS when unset.
	Subnqn *string `pulumi:"subnqn"`
}

// The set of arguments for constructing a NvmetSubsys resource.
type NvmetSubsysArgs struct {
	// Allow any host to connect to this subsystem without an explicit host mapping.
	AllowAnyHost pulumi.BoolPtrInput
	// Enable Asymmetric Namespace Access (ANA) for this subsystem.
	Ana pulumi.BoolPtrInput
	// IEEE Organizationally Unique Identifier used when generating namespace identifiers.
	IeeeOui pulumi.StringPtrInput
	// Name of the NVMe-oF subsystem.
	Name pulumi.StringInput
	// Enable end-to-end data protection (PI) for this subsystem.
	PiEnable pulumi.BoolPtrInput
	// Maximum number of queues supported by this subsystem.
	QidMax pulumi.IntPtrInput
	// NVMe Qualified Name (NQN) for the subsystem. Derived by TrueNAS when unset.
	Subnqn pulumi.StringPtrInput
}

func (NvmetSubsysArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nvmetSubsysArgs)(nil)).Elem()
}

type NvmetSubsysInput interface {
	pulumi.Input

	ToNvmetSubsysOutput() NvmetSubsysOutput
	ToNvmetSubsysOutputWithContext(ctx context.Context) NvmetSubsysOutput
}

func (*NvmetSubsys) ElementType() reflect.Type {
	return reflect.TypeOf((**NvmetSubsys)(nil)).Elem()
}

func (i *NvmetSubsys) ToNvmetSubsysOutput() NvmetSubsysOutput {
	return i.ToNvmetSubsysOutputWithContext(context.Background())
}

func (i *NvmetSubsys) ToNvmetSubsysOutputWithContext(ctx context.Context) NvmetSubsysOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NvmetSubsysOutput)
}

// NvmetSubsysArrayInput is an input type that accepts NvmetSubsysArray and NvmetSubsysArrayOutput values.
// You can construct a concrete instance of `NvmetSubsysArrayInput` via:
//
//	NvmetSubsysArray{ NvmetSubsysArgs{...} }
type NvmetSubsysArrayInput interface {
	pulumi.Input

	ToNvmetSubsysArrayOutput() NvmetSubsysArrayOutput
	ToNvmetSubsysArrayOutputWithContext(context.Context) NvmetSubsysArrayOutput
}

type NvmetSubsysArray []NvmetSubsysInput

func (NvmetSubsysArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NvmetSubsys)(nil)).Elem()
}

func (i NvmetSubsysArray) ToNvmetSubsysArrayOutput() NvmetSubsysArrayOutput {
	return i.ToNvmetSubsysArrayOutputWithContext(context.Background())
}

func (i NvmetSubsysArray) ToNvmetSubsysArrayOutputWithContext(ctx context.Context) NvmetSubsysArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NvmetSubsysArrayOutput)
}

// NvmetSubsysMapInput is an input type that accepts NvmetSubsysMap and NvmetSubsysMapOutput values.
// You can construct a concrete instance of `NvmetSubsysMapInput` via:
//
//	NvmetSubsysMap{ "key": NvmetSubsysArgs{...} }
type NvmetSubsysMapInput interface {
	pulumi.Input

	ToNvmetSubsysMapOutput() NvmetSubsysMapOutput
	ToNvmetSubsysMapOutputWithContext(context.Context) NvmetSubsysMapOutput
}

type NvmetSubsysMap map[string]NvmetSubsysInput

func (NvmetSubsysMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NvmetSubsys)(nil)).Elem()
}

func (i NvmetSubsysMap) ToNvmetSubsysMapOutput() NvmetSubsysMapOutput {
	return i.ToNvmetSubsysMapOutputWithContext(context.Background())
}

func (i NvmetSubsysMap) ToNvmetSubsysMapOutputWithContext(ctx context.Context) NvmetSubsysMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NvmetSubsysMapOutput)
}

type NvmetSubsysOutput struct{ *pulumi.OutputState }

func (NvmetSubsysOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NvmetSubsys)(nil)).Elem()
}

func (o NvmetSubsysOutput) ToNvmetSubsysOutput() NvmetSubsysOutput {
	return o
}

func (o NvmetSubsysOutput) ToNvmetSubsysOutputWithContext(ctx context.Context) NvmetSubsysOutput {
	return o
}

// Allow any host to connect to this subsystem without an explicit host mapping.
func (o NvmetSubsysOutput) AllowAnyHost() pulumi.BoolOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.BoolOutput { return v.AllowAnyHost }).(pulumi.BoolOutput)
}

// Enable Asymmetric Namespace Access (ANA) for this subsystem.
func (o NvmetSubsysOutput) Ana() pulumi.BoolOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.BoolOutput { return v.Ana }).(pulumi.BoolOutput)
}

// IEEE Organizationally Unique Identifier used when generating namespace identifiers.
func (o NvmetSubsysOutput) IeeeOui() pulumi.StringOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.StringOutput { return v.IeeeOui }).(pulumi.StringOutput)
}

// Name of the NVMe-oF subsystem.
func (o NvmetSubsysOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Enable end-to-end data protection (PI) for this subsystem.
func (o NvmetSubsysOutput) PiEnable() pulumi.BoolOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.BoolOutput { return v.PiEnable }).(pulumi.BoolOutput)
}

// Maximum number of queues supported by this subsystem.
func (o NvmetSubsysOutput) QidMax() pulumi.IntOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.IntOutput { return v.QidMax }).(pulumi.IntOutput)
}

// Serial number assigned by TrueNAS.
func (o NvmetSubsysOutput) Serial() pulumi.StringOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.StringOutput { return v.Serial }).(pulumi.StringOutput)
}

// NVMe Qualified Name (NQN) for the subsystem. Derived by TrueNAS when unset.
func (o NvmetSubsysOutput) Subnqn() pulumi.StringOutput {
	return o.ApplyT(func(v *NvmetSubsys) pulumi.StringOutput { return v.Subnqn }).(pulumi.StringOutput)
}

type NvmetSubsysArrayOutput struct{ *pulumi.OutputState }

func (NvmetSubsysArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NvmetSubsys)(nil)).Elem()
}

func (o NvmetSubsysArrayOutput) ToNvmetSubsysArrayOutput() NvmetSubsysArrayOutput {
	return o
}

func (o NvmetSubsysArrayOutput) ToNvmetSubsysArrayOutputWithContext(ctx context.Context) NvmetSubsysArrayOutput {
	return o
}

func (o NvmetSubsysArrayOutput) Index(i pulumi.IntInput) NvmetSubsysOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NvmetSubsys {
		return vs[0].([]*NvmetSubsys)[vs[1].(int)]
	}).(NvmetSubsysOutput)
}

type NvmetSubsysMapOutput struct{ *pulumi.OutputState }

func (NvmetSubsysMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NvmetSubsys)(nil)).Elem()
}

func (o NvmetSubsysMapOutput) ToNvmetSubsysMapOutput() NvmetSubsysMapOutput {
	return o
}

func (o NvmetSubsysMapOutput) ToNvmetSubsysMapOutputWithContext(ctx context.Context) NvmetSubsysMapOutput {
	return o
}

func (o NvmetSubsysMapOutput) MapIndex(k pulumi.StringInput) NvmetSubsysOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NvmetSubsys {
		return vs[0].(map[string]*NvmetSubsys)[vs[1].(string)]
	}).(NvmetSubsysOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NvmetSubsysInput)(nil)).Elem(), &NvmetSubsys{})
	pulumi.RegisterInputType(reflect.TypeOf((*NvmetSubsysArrayInput)(nil)).Elem(), NvmetSubsysArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NvmetSubsysMapInput)(nil)).Elem(), NvmetSubsysMap{})
	pulumi.RegisterOutputType(NvmetSubsysOutput{})
	pulumi.RegisterOutputType(NvmetSubsysArrayOutput{})
	pulumi.RegisterOutputType(NvmetSubsysMapOutput{})
}
