// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the truenas package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// TrueNAS API key. Mutually exclusive with password auth. On TrueNAS 26.0+, also set username (the key owner) to authenticate via SCRAM-SHA-512 so the raw key never crosses the wire. Env: TRUENAS_API_KEY
	ApiKey pulumi.StringPtrOutput `pulumi:"apiKey"`
	// Path to a PEM-encoded CA certificate file. Mutually exclusive with insecure.
	CaCert pulumi.StringPtrOutput `pulumi:"caCert"`
	// TrueNAS WebSocket endpoint, e.g. wss://truenas.example.com/api/current (legacy /websocket paths are rewritten to /api/current automatically). Env: TRUENAS_ENDPOINT
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
	// TrueNAS password. Requires username. Env: TRUENAS_PASSWORD
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// TrueNAS username. With password: password authentication. With api_key: names the key owner and enables SCRAM-SHA-512 on TrueNAS 26.0+. Env: TRUENAS_USERNAME
	Username pulumi.StringPtrOutput `pulumi:"username"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiKey != nil {
		args.ApiKey = pulumi.ToSecret(args.ApiKey).(pulumi.StringPtrInput)
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:truenas", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// TrueNAS API key. Mutually exclusive with password auth. On TrueNAS 26.0+, also set username (the key owner) to authenticate via SCRAM-SHA-512 so the raw key never crosses the wire. Env: TRUENAS_API_KEY
	ApiKey *string `pulumi:"apiKey"`
	// Path to a PEM-encoded CA certificate file. Mutually exclusive with insecure.
	CaCert *string `pulumi:"caCert"`
	// TrueNAS WebSocket endpoint, e.g. wss://truenas.example.com/api/current (legacy /websocket paths are rewritten to /api/current automatically). Env: TRUENAS_ENDPOINT
	Endpoint *string `pulumi:"endpoint"`
	// Skip TLS certificate verification. Mutually exclusive with ca_cert.
	Insecure *bool `pulumi:"insecure"`
	// TrueNAS password. Requires username. Env: TRUENAS_PASSWORD
	Password *string `pulumi:"password"`
	// TrueNAS username. With password: password authentication. With api_key: names the key owner and enables SCRAM-SHA-512 on TrueNAS 26.0+. Env: TRUENAS_USERNAME
	Username *string `pulumi:"username"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// TrueNAS API key. Mutually exclusive with password auth. On TrueNAS 26.0+, also set username (the key owner) to authenticate via SCRAM-SHA-512 so the raw key never crosses the wire. Env: TRUENAS_API_KEY
	ApiKey pulumi.StringPtrInput
	// Path to a PEM-encoded CA certificate file. Mutually exclusive with insecure.
	CaCert pulumi.StringPtrInput
	// TrueNAS WebSocket endpoint, e.g. wss://truenas.example.com/api/current (legacy /websocket paths are rewritten to /api/current automatically). Env: TRUENAS_ENDPOINT
	Endpoint pulumi.StringPtrInput
	// Skip TLS certificate verification. Mutually exclusive with ca_cert.
	Insecure pulumi.BoolPtrInput
	// TrueNAS password. Requires username. Env: TRUENAS_PASSWORD
	Password pulumi.StringPtrInput
	// TrueNAS username. With password: password authentication. With api_key: names the key owner and enables SCRAM-SHA-512 on TrueNAS 26.0+. Env: TRUENAS_USERNAME
	Username pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (ProviderTerraformConfigResultOutput, error) {
	out, err := ctx.Call("pulumi:providers:truenas/terraformConfig", nil, ProviderTerraformConfigResultOutput{}, r)
	if err != nil {
		return ProviderTerraformConfigResultOutput{}, err
	}
	return out.(ProviderTerraformConfigResultOutput), nil
}

type ProviderTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type ProviderTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (ProviderTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderTerraformConfigResult)(nil)).Elem()
}

func (o ProviderTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v ProviderTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// TrueNAS API key. Mutually exclusive with password auth. On TrueNAS 26.0+, also set username (the key owner) to authenticate via SCRAM-SHA-512 so the raw key never crosses the wire. Env: TRUENAS_API_KEY
func (o ProviderOutput) ApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiKey }).(pulumi.StringPtrOutput)
}

// Path to a PEM-encoded CA certificate file. Mutually exclusive with insecure.
func (o ProviderOutput) CaCert() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.CaCert }).(pulumi.StringPtrOutput)
}

// TrueNAS WebSocket endpoint, e.g. wss://truenas.example.com/api/current (legacy /websocket paths are rewritten to /api/current automatically). Env: TRUENAS_ENDPOINT
func (o ProviderOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

// TrueNAS password. Requires username. Env: TRUENAS_PASSWORD
func (o ProviderOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// TrueNAS username. With password: password authentication. With api_key: names the key owner and enables SCRAM-SHA-512 on TrueNAS 26.0+. Env: TRUENAS_USERNAME
func (o ProviderOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Username }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(ProviderTerraformConfigResultOutput{})
}
