// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type RsyncTask struct {
	pulumi.CustomResourceState

	// Make rsync run recursively, preserving symlinks, permissions, modification times, group, and special files. Defaults to false.
	Archive pulumi.BoolOutput `pulumi:"archive"`
	// Reduce the size of the data to be transmitted. Defaults to true.
	Compress pulumi.BoolOutput `pulumi:"compress"`
	// Delay updating destination files until all transfers are complete. Defaults to true.
	Delayupdates pulumi.BoolOutput `pulumi:"delayupdates"`
	// Delete files in the destination directory that do not exist in the source directory. Defaults to false.
	Delete pulumi.BoolOutput `pulumi:"delete"`
	// Description of the rsync task.
	Desc pulumi.StringOutput `pulumi:"desc"`
	// Whether data is PUSHed to or PULLed from the remote system. Defaults to PUSH.
	Direction pulumi.StringOutput `pulumi:"direction"`
	// Whether this rsync task is enabled. Defaults to true.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Additional rsync command-line options. Defaults to an empty list.
	Extras pulumi.StringArrayOutput `pulumi:"extras"`
	// Operating mechanism for rsync: MODULE (rsync module/daemon protocol) or SSH. Defaults to MODULE.
	Mode pulumi.StringOutput `pulumi:"mode"`
	// Local filesystem path to synchronize.
	Path pulumi.StringOutput `pulumi:"path"`
	// Preserve extended attributes of files. Defaults to false.
	Preserveattr pulumi.BoolOutput `pulumi:"preserveattr"`
	// Preserve original file permissions. Defaults to false.
	Preserveperm pulumi.BoolOutput `pulumi:"preserveperm"`
	// Suppress informational messages from rsync. Defaults to false.
	Quiet pulumi.BoolOutput `pulumi:"quiet"`
	// Recursively transfer subdirectories. Defaults to true.
	Recursive pulumi.BoolOutput `pulumi:"recursive"`
	// IP address or hostname of the remote system. If the username differs on the remote host, use "username@remote_host" format. Null when unset.
	Remotehost pulumi.StringOutput `pulumi:"remotehost"`
	// Name of the remote rsync module. Should be set when mode is MODULE. Null when unset.
	Remotemodule pulumi.StringOutput `pulumi:"remotemodule"`
	// Path on the remote system to synchronize with.
	Remotepath pulumi.StringOutput `pulumi:"remotepath"`
	// Port number for the SSH connection. Only applies when mode is SSH. Null when unset.
	Remoteport pulumi.IntOutput `pulumi:"remoteport"`
	// Cron schedule for when the rsync task should run.
	Schedule RsyncTaskScheduleOutput `pulumi:"schedule"`
	// Keychain credential ID (of type SSH_CREDENTIALS) used to connect to the remote host in SSH mode. Null (the default) means the run-as user's own SSH keys are used.
	SshCredentials pulumi.IntOutput `pulumi:"sshCredentials"`
	// Automatically add the remote host key to the run-as user's<span pulumi-lang-nodejs=" knownHosts " pulumi-lang-dotnet=" KnownHosts " pulumi-lang-go=" knownHosts " pulumi-lang-python=" known_hosts " pulumi-lang-yaml=" knownHosts " pulumi-lang-java=" knownHosts " pulumi-lang-hcl=" known_hosts "> knownHosts </span>file at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	SshKeyscan pulumi.BoolPtrOutput `pulumi:"sshKeyscan"`
	// Preserve modification times of files. Defaults to true.
	Times pulumi.BoolOutput `pulumi:"times"`
	// Username to run the rsync task as.
	User pulumi.StringOutput `pulumi:"user"`
	// Validate the existence of the remote path at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	ValidateRpath pulumi.BoolPtrOutput `pulumi:"validateRpath"`
}

// NewRsyncTask registers a new resource with the given unique name, arguments, and options.
func NewRsyncTask(ctx *pulumi.Context,
	name string, args *RsyncTaskArgs, opts ...pulumi.ResourceOption) (*RsyncTask, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Path == nil {
		return nil, errors.New("invalid value for required argument 'Path'")
	}
	if args.User == nil {
		return nil, errors.New("invalid value for required argument 'User'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RsyncTask
	err := ctx.RegisterResource("truenas:index/rsyncTask:RsyncTask", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRsyncTask gets an existing RsyncTask resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRsyncTask(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RsyncTaskState, opts ...pulumi.ResourceOption) (*RsyncTask, error) {
	var resource RsyncTask
	err := ctx.ReadResource("truenas:index/rsyncTask:RsyncTask", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RsyncTask resources.
type rsyncTaskState struct {
	// Make rsync run recursively, preserving symlinks, permissions, modification times, group, and special files. Defaults to false.
	Archive *bool `pulumi:"archive"`
	// Reduce the size of the data to be transmitted. Defaults to true.
	Compress *bool `pulumi:"compress"`
	// Delay updating destination files until all transfers are complete. Defaults to true.
	Delayupdates *bool `pulumi:"delayupdates"`
	// Delete files in the destination directory that do not exist in the source directory. Defaults to false.
	Delete *bool `pulumi:"delete"`
	// Description of the rsync task.
	Desc *string `pulumi:"desc"`
	// Whether data is PUSHed to or PULLed from the remote system. Defaults to PUSH.
	Direction *string `pulumi:"direction"`
	// Whether this rsync task is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// Additional rsync command-line options. Defaults to an empty list.
	Extras []string `pulumi:"extras"`
	// Operating mechanism for rsync: MODULE (rsync module/daemon protocol) or SSH. Defaults to MODULE.
	Mode *string `pulumi:"mode"`
	// Local filesystem path to synchronize.
	Path *string `pulumi:"path"`
	// Preserve extended attributes of files. Defaults to false.
	Preserveattr *bool `pulumi:"preserveattr"`
	// Preserve original file permissions. Defaults to false.
	Preserveperm *bool `pulumi:"preserveperm"`
	// Suppress informational messages from rsync. Defaults to false.
	Quiet *bool `pulumi:"quiet"`
	// Recursively transfer subdirectories. Defaults to true.
	Recursive *bool `pulumi:"recursive"`
	// IP address or hostname of the remote system. If the username differs on the remote host, use "username@remote_host" format. Null when unset.
	Remotehost *string `pulumi:"remotehost"`
	// Name of the remote rsync module. Should be set when mode is MODULE. Null when unset.
	Remotemodule *string `pulumi:"remotemodule"`
	// Path on the remote system to synchronize with.
	Remotepath *string `pulumi:"remotepath"`
	// Port number for the SSH connection. Only applies when mode is SSH. Null when unset.
	Remoteport *int `pulumi:"remoteport"`
	// Cron schedule for when the rsync task should run.
	Schedule *RsyncTaskSchedule `pulumi:"schedule"`
	// Keychain credential ID (of type SSH_CREDENTIALS) used to connect to the remote host in SSH mode. Null (the default) means the run-as user's own SSH keys are used.
	SshCredentials *int `pulumi:"sshCredentials"`
	// Automatically add the remote host key to the run-as user's<span pulumi-lang-nodejs=" knownHosts " pulumi-lang-dotnet=" KnownHosts " pulumi-lang-go=" knownHosts " pulumi-lang-python=" known_hosts " pulumi-lang-yaml=" knownHosts " pulumi-lang-java=" knownHosts " pulumi-lang-hcl=" known_hosts "> knownHosts </span>file at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	SshKeyscan *bool `pulumi:"sshKeyscan"`
	// Preserve modification times of files. Defaults to true.
	Times *bool `pulumi:"times"`
	// Username to run the rsync task as.
	User *string `pulumi:"user"`
	// Validate the existence of the remote path at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	ValidateRpath *bool `pulumi:"validateRpath"`
}

type RsyncTaskState struct {
	// Make rsync run recursively, preserving symlinks, permissions, modification times, group, and special files. Defaults to false.
	Archive pulumi.BoolPtrInput
	// Reduce the size of the data to be transmitted. Defaults to true.
	Compress pulumi.BoolPtrInput
	// Delay updating destination files until all transfers are complete. Defaults to true.
	Delayupdates pulumi.BoolPtrInput
	// Delete files in the destination directory that do not exist in the source directory. Defaults to false.
	Delete pulumi.BoolPtrInput
	// Description of the rsync task.
	Desc pulumi.StringPtrInput
	// Whether data is PUSHed to or PULLed from the remote system. Defaults to PUSH.
	Direction pulumi.StringPtrInput
	// Whether this rsync task is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// Additional rsync command-line options. Defaults to an empty list.
	Extras pulumi.StringArrayInput
	// Operating mechanism for rsync: MODULE (rsync module/daemon protocol) or SSH. Defaults to MODULE.
	Mode pulumi.StringPtrInput
	// Local filesystem path to synchronize.
	Path pulumi.StringPtrInput
	// Preserve extended attributes of files. Defaults to false.
	Preserveattr pulumi.BoolPtrInput
	// Preserve original file permissions. Defaults to false.
	Preserveperm pulumi.BoolPtrInput
	// Suppress informational messages from rsync. Defaults to false.
	Quiet pulumi.BoolPtrInput
	// Recursively transfer subdirectories. Defaults to true.
	Recursive pulumi.BoolPtrInput
	// IP address or hostname of the remote system. If the username differs on the remote host, use "username@remote_host" format. Null when unset.
	Remotehost pulumi.StringPtrInput
	// Name of the remote rsync module. Should be set when mode is MODULE. Null when unset.
	Remotemodule pulumi.StringPtrInput
	// Path on the remote system to synchronize with.
	Remotepath pulumi.StringPtrInput
	// Port number for the SSH connection. Only applies when mode is SSH. Null when unset.
	Remoteport pulumi.IntPtrInput
	// Cron schedule for when the rsync task should run.
	Schedule RsyncTaskSchedulePtrInput
	// Keychain credential ID (of type SSH_CREDENTIALS) used to connect to the remote host in SSH mode. Null (the default) means the run-as user's own SSH keys are used.
	SshCredentials pulumi.IntPtrInput
	// Automatically add the remote host key to the run-as user's<span pulumi-lang-nodejs=" knownHosts " pulumi-lang-dotnet=" KnownHosts " pulumi-lang-go=" knownHosts " pulumi-lang-python=" known_hosts " pulumi-lang-yaml=" knownHosts " pulumi-lang-java=" knownHosts " pulumi-lang-hcl=" known_hosts "> knownHosts </span>file at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	SshKeyscan pulumi.BoolPtrInput
	// Preserve modification times of files. Defaults to true.
	Times pulumi.BoolPtrInput
	// Username to run the rsync task as.
	User pulumi.StringPtrInput
	// Validate the existence of the remote path at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	ValidateRpath pulumi.BoolPtrInput
}

func (RsyncTaskState) ElementType() reflect.Type {
	return reflect.TypeOf((*rsyncTaskState)(nil)).Elem()
}

type rsyncTaskArgs struct {
	// Make rsync run recursively, preserving symlinks, permissions, modification times, group, and special files. Defaults to false.
	Archive *bool `pulumi:"archive"`
	// Reduce the size of the data to be transmitted. Defaults to true.
	Compress *bool `pulumi:"compress"`
	// Delay updating destination files until all transfers are complete. Defaults to true.
	Delayupdates *bool `pulumi:"delayupdates"`
	// Delete files in the destination directory that do not exist in the source directory. Defaults to false.
	Delete *bool `pulumi:"delete"`
	// Description of the rsync task.
	Desc *string `pulumi:"desc"`
	// Whether data is PUSHed to or PULLed from the remote system. Defaults to PUSH.
	Direction *string `pulumi:"direction"`
	// Whether this rsync task is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// Additional rsync command-line options. Defaults to an empty list.
	Extras []string `pulumi:"extras"`
	// Operating mechanism for rsync: MODULE (rsync module/daemon protocol) or SSH. Defaults to MODULE.
	Mode *string `pulumi:"mode"`
	// Local filesystem path to synchronize.
	Path string `pulumi:"path"`
	// Preserve extended attributes of files. Defaults to false.
	Preserveattr *bool `pulumi:"preserveattr"`
	// Preserve original file permissions. Defaults to false.
	Preserveperm *bool `pulumi:"preserveperm"`
	// Suppress informational messages from rsync. Defaults to false.
	Quiet *bool `pulumi:"quiet"`
	// Recursively transfer subdirectories. Defaults to true.
	Recursive *bool `pulumi:"recursive"`
	// IP address or hostname of the remote system. If the username differs on the remote host, use "username@remote_host" format. Null when unset.
	Remotehost *string `pulumi:"remotehost"`
	// Name of the remote rsync module. Should be set when mode is MODULE. Null when unset.
	Remotemodule *string `pulumi:"remotemodule"`
	// Path on the remote system to synchronize with.
	Remotepath *string `pulumi:"remotepath"`
	// Port number for the SSH connection. Only applies when mode is SSH. Null when unset.
	Remoteport *int `pulumi:"remoteport"`
	// Cron schedule for when the rsync task should run.
	Schedule *RsyncTaskSchedule `pulumi:"schedule"`
	// Keychain credential ID (of type SSH_CREDENTIALS) used to connect to the remote host in SSH mode. Null (the default) means the run-as user's own SSH keys are used.
	SshCredentials *int `pulumi:"sshCredentials"`
	// Automatically add the remote host key to the run-as user's<span pulumi-lang-nodejs=" knownHosts " pulumi-lang-dotnet=" KnownHosts " pulumi-lang-go=" knownHosts " pulumi-lang-python=" known_hosts " pulumi-lang-yaml=" knownHosts " pulumi-lang-java=" knownHosts " pulumi-lang-hcl=" known_hosts "> knownHosts </span>file at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	SshKeyscan *bool `pulumi:"sshKeyscan"`
	// Preserve modification times of files. Defaults to true.
	Times *bool `pulumi:"times"`
	// Username to run the rsync task as.
	User string `pulumi:"user"`
	// Validate the existence of the remote path at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	ValidateRpath *bool `pulumi:"validateRpath"`
}

// The set of arguments for constructing a RsyncTask resource.
type RsyncTaskArgs struct {
	// Make rsync run recursively, preserving symlinks, permissions, modification times, group, and special files. Defaults to false.
	Archive pulumi.BoolPtrInput
	// Reduce the size of the data to be transmitted. Defaults to true.
	Compress pulumi.BoolPtrInput
	// Delay updating destination files until all transfers are complete. Defaults to true.
	Delayupdates pulumi.BoolPtrInput
	// Delete files in the destination directory that do not exist in the source directory. Defaults to false.
	Delete pulumi.BoolPtrInput
	// Description of the rsync task.
	Desc pulumi.StringPtrInput
	// Whether data is PUSHed to or PULLed from the remote system. Defaults to PUSH.
	Direction pulumi.StringPtrInput
	// Whether this rsync task is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// Additional rsync command-line options. Defaults to an empty list.
	Extras pulumi.StringArrayInput
	// Operating mechanism for rsync: MODULE (rsync module/daemon protocol) or SSH. Defaults to MODULE.
	Mode pulumi.StringPtrInput
	// Local filesystem path to synchronize.
	Path pulumi.StringInput
	// Preserve extended attributes of files. Defaults to false.
	Preserveattr pulumi.BoolPtrInput
	// Preserve original file permissions. Defaults to false.
	Preserveperm pulumi.BoolPtrInput
	// Suppress informational messages from rsync. Defaults to false.
	Quiet pulumi.BoolPtrInput
	// Recursively transfer subdirectories. Defaults to true.
	Recursive pulumi.BoolPtrInput
	// IP address or hostname of the remote system. If the username differs on the remote host, use "username@remote_host" format. Null when unset.
	Remotehost pulumi.StringPtrInput
	// Name of the remote rsync module. Should be set when mode is MODULE. Null when unset.
	Remotemodule pulumi.StringPtrInput
	// Path on the remote system to synchronize with.
	Remotepath pulumi.StringPtrInput
	// Port number for the SSH connection. Only applies when mode is SSH. Null when unset.
	Remoteport pulumi.IntPtrInput
	// Cron schedule for when the rsync task should run.
	Schedule RsyncTaskSchedulePtrInput
	// Keychain credential ID (of type SSH_CREDENTIALS) used to connect to the remote host in SSH mode. Null (the default) means the run-as user's own SSH keys are used.
	SshCredentials pulumi.IntPtrInput
	// Automatically add the remote host key to the run-as user's<span pulumi-lang-nodejs=" knownHosts " pulumi-lang-dotnet=" KnownHosts " pulumi-lang-go=" knownHosts " pulumi-lang-python=" known_hosts " pulumi-lang-yaml=" knownHosts " pulumi-lang-java=" knownHosts " pulumi-lang-hcl=" known_hosts "> knownHosts </span>file at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	SshKeyscan pulumi.BoolPtrInput
	// Preserve modification times of files. Defaults to true.
	Times pulumi.BoolPtrInput
	// Username to run the rsync task as.
	User pulumi.StringInput
	// Validate the existence of the remote path at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
	ValidateRpath pulumi.BoolPtrInput
}

func (RsyncTaskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*rsyncTaskArgs)(nil)).Elem()
}

type RsyncTaskInput interface {
	pulumi.Input

	ToRsyncTaskOutput() RsyncTaskOutput
	ToRsyncTaskOutputWithContext(ctx context.Context) RsyncTaskOutput
}

func (*RsyncTask) ElementType() reflect.Type {
	return reflect.TypeOf((**RsyncTask)(nil)).Elem()
}

func (i *RsyncTask) ToRsyncTaskOutput() RsyncTaskOutput {
	return i.ToRsyncTaskOutputWithContext(context.Background())
}

func (i *RsyncTask) ToRsyncTaskOutputWithContext(ctx context.Context) RsyncTaskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RsyncTaskOutput)
}

// RsyncTaskArrayInput is an input type that accepts RsyncTaskArray and RsyncTaskArrayOutput values.
// You can construct a concrete instance of `RsyncTaskArrayInput` via:
//
//	RsyncTaskArray{ RsyncTaskArgs{...} }
type RsyncTaskArrayInput interface {
	pulumi.Input

	ToRsyncTaskArrayOutput() RsyncTaskArrayOutput
	ToRsyncTaskArrayOutputWithContext(context.Context) RsyncTaskArrayOutput
}

type RsyncTaskArray []RsyncTaskInput

func (RsyncTaskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RsyncTask)(nil)).Elem()
}

func (i RsyncTaskArray) ToRsyncTaskArrayOutput() RsyncTaskArrayOutput {
	return i.ToRsyncTaskArrayOutputWithContext(context.Background())
}

func (i RsyncTaskArray) ToRsyncTaskArrayOutputWithContext(ctx context.Context) RsyncTaskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RsyncTaskArrayOutput)
}

// RsyncTaskMapInput is an input type that accepts RsyncTaskMap and RsyncTaskMapOutput values.
// You can construct a concrete instance of `RsyncTaskMapInput` via:
//
//	RsyncTaskMap{ "key": RsyncTaskArgs{...} }
type RsyncTaskMapInput interface {
	pulumi.Input

	ToRsyncTaskMapOutput() RsyncTaskMapOutput
	ToRsyncTaskMapOutputWithContext(context.Context) RsyncTaskMapOutput
}

type RsyncTaskMap map[string]RsyncTaskInput

func (RsyncTaskMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RsyncTask)(nil)).Elem()
}

func (i RsyncTaskMap) ToRsyncTaskMapOutput() RsyncTaskMapOutput {
	return i.ToRsyncTaskMapOutputWithContext(context.Background())
}

func (i RsyncTaskMap) ToRsyncTaskMapOutputWithContext(ctx context.Context) RsyncTaskMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RsyncTaskMapOutput)
}

type RsyncTaskOutput struct{ *pulumi.OutputState }

func (RsyncTaskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RsyncTask)(nil)).Elem()
}

func (o RsyncTaskOutput) ToRsyncTaskOutput() RsyncTaskOutput {
	return o
}

func (o RsyncTaskOutput) ToRsyncTaskOutputWithContext(ctx context.Context) RsyncTaskOutput {
	return o
}

// Make rsync run recursively, preserving symlinks, permissions, modification times, group, and special files. Defaults to false.
func (o RsyncTaskOutput) Archive() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Archive }).(pulumi.BoolOutput)
}

// Reduce the size of the data to be transmitted. Defaults to true.
func (o RsyncTaskOutput) Compress() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Compress }).(pulumi.BoolOutput)
}

// Delay updating destination files until all transfers are complete. Defaults to true.
func (o RsyncTaskOutput) Delayupdates() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Delayupdates }).(pulumi.BoolOutput)
}

// Delete files in the destination directory that do not exist in the source directory. Defaults to false.
func (o RsyncTaskOutput) Delete() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Delete }).(pulumi.BoolOutput)
}

// Description of the rsync task.
func (o RsyncTaskOutput) Desc() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.Desc }).(pulumi.StringOutput)
}

// Whether data is PUSHed to or PULLed from the remote system. Defaults to PUSH.
func (o RsyncTaskOutput) Direction() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.Direction }).(pulumi.StringOutput)
}

// Whether this rsync task is enabled. Defaults to true.
func (o RsyncTaskOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Additional rsync command-line options. Defaults to an empty list.
func (o RsyncTaskOutput) Extras() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringArrayOutput { return v.Extras }).(pulumi.StringArrayOutput)
}

// Operating mechanism for rsync: MODULE (rsync module/daemon protocol) or SSH. Defaults to MODULE.
func (o RsyncTaskOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.Mode }).(pulumi.StringOutput)
}

// Local filesystem path to synchronize.
func (o RsyncTaskOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

// Preserve extended attributes of files. Defaults to false.
func (o RsyncTaskOutput) Preserveattr() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Preserveattr }).(pulumi.BoolOutput)
}

// Preserve original file permissions. Defaults to false.
func (o RsyncTaskOutput) Preserveperm() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Preserveperm }).(pulumi.BoolOutput)
}

// Suppress informational messages from rsync. Defaults to false.
func (o RsyncTaskOutput) Quiet() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Quiet }).(pulumi.BoolOutput)
}

// Recursively transfer subdirectories. Defaults to true.
func (o RsyncTaskOutput) Recursive() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Recursive }).(pulumi.BoolOutput)
}

// IP address or hostname of the remote system. If the username differs on the remote host, use "username@remote_host" format. Null when unset.
func (o RsyncTaskOutput) Remotehost() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.Remotehost }).(pulumi.StringOutput)
}

// Name of the remote rsync module. Should be set when mode is MODULE. Null when unset.
func (o RsyncTaskOutput) Remotemodule() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.Remotemodule }).(pulumi.StringOutput)
}

// Path on the remote system to synchronize with.
func (o RsyncTaskOutput) Remotepath() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.Remotepath }).(pulumi.StringOutput)
}

// Port number for the SSH connection. Only applies when mode is SSH. Null when unset.
func (o RsyncTaskOutput) Remoteport() pulumi.IntOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.IntOutput { return v.Remoteport }).(pulumi.IntOutput)
}

// Cron schedule for when the rsync task should run.
func (o RsyncTaskOutput) Schedule() RsyncTaskScheduleOutput {
	return o.ApplyT(func(v *RsyncTask) RsyncTaskScheduleOutput { return v.Schedule }).(RsyncTaskScheduleOutput)
}

// Keychain credential ID (of type SSH_CREDENTIALS) used to connect to the remote host in SSH mode. Null (the default) means the run-as user's own SSH keys are used.
func (o RsyncTaskOutput) SshCredentials() pulumi.IntOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.IntOutput { return v.SshCredentials }).(pulumi.IntOutput)
}

// Automatically add the remote host key to the run-as user's<span pulumi-lang-nodejs=" knownHosts " pulumi-lang-dotnet=" KnownHosts " pulumi-lang-go=" knownHosts " pulumi-lang-python=" known_hosts " pulumi-lang-yaml=" knownHosts " pulumi-lang-java=" knownHosts " pulumi-lang-hcl=" known_hosts "> knownHosts </span>file at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
func (o RsyncTaskOutput) SshKeyscan() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolPtrOutput { return v.SshKeyscan }).(pulumi.BoolPtrOutput)
}

// Preserve modification times of files. Defaults to true.
func (o RsyncTaskOutput) Times() pulumi.BoolOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolOutput { return v.Times }).(pulumi.BoolOutput)
}

// Username to run the rsync task as.
func (o RsyncTaskOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.StringOutput { return v.User }).(pulumi.StringOutput)
}

// Validate the existence of the remote path at create/update time. Write-only: rsynctask.query never returns this flag, so it is not read back from the API and is not verified on import.
func (o RsyncTaskOutput) ValidateRpath() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RsyncTask) pulumi.BoolPtrOutput { return v.ValidateRpath }).(pulumi.BoolPtrOutput)
}

type RsyncTaskArrayOutput struct{ *pulumi.OutputState }

func (RsyncTaskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RsyncTask)(nil)).Elem()
}

func (o RsyncTaskArrayOutput) ToRsyncTaskArrayOutput() RsyncTaskArrayOutput {
	return o
}

func (o RsyncTaskArrayOutput) ToRsyncTaskArrayOutputWithContext(ctx context.Context) RsyncTaskArrayOutput {
	return o
}

func (o RsyncTaskArrayOutput) Index(i pulumi.IntInput) RsyncTaskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RsyncTask {
		return vs[0].([]*RsyncTask)[vs[1].(int)]
	}).(RsyncTaskOutput)
}

type RsyncTaskMapOutput struct{ *pulumi.OutputState }

func (RsyncTaskMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RsyncTask)(nil)).Elem()
}

func (o RsyncTaskMapOutput) ToRsyncTaskMapOutput() RsyncTaskMapOutput {
	return o
}

func (o RsyncTaskMapOutput) ToRsyncTaskMapOutputWithContext(ctx context.Context) RsyncTaskMapOutput {
	return o
}

func (o RsyncTaskMapOutput) MapIndex(k pulumi.StringInput) RsyncTaskOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RsyncTask {
		return vs[0].(map[string]*RsyncTask)[vs[1].(string)]
	}).(RsyncTaskOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RsyncTaskInput)(nil)).Elem(), &RsyncTask{})
	pulumi.RegisterInputType(reflect.TypeOf((*RsyncTaskArrayInput)(nil)).Elem(), RsyncTaskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RsyncTaskMapInput)(nil)).Elem(), RsyncTaskMap{})
	pulumi.RegisterOutputType(RsyncTaskOutput{})
	pulumi.RegisterOutputType(RsyncTaskArrayOutput{})
	pulumi.RegisterOutputType(RsyncTaskMapOutput{})
}
