// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SmbShareAcl struct {
	pulumi.CustomResourceState

	// Ordered list of share ACL entries. Order is significant (DENIED entries are typically listed before ALLOWED ones). At least one entry is required.
	ShareAcls SmbShareAclShareAclArrayOutput `pulumi:"shareAcls"`
	// Name of the existing SMB share (truenas_smb_share.name) whose share ACL this resource manages. Changing it forces a new resource (it targets a different share).
	ShareName pulumi.StringOutput `pulumi:"shareName"`
}

// NewSmbShareAcl registers a new resource with the given unique name, arguments, and options.
func NewSmbShareAcl(ctx *pulumi.Context,
	name string, args *SmbShareAclArgs, opts ...pulumi.ResourceOption) (*SmbShareAcl, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ShareAcls == nil {
		return nil, errors.New("invalid value for required argument 'ShareAcls'")
	}
	if args.ShareName == nil {
		return nil, errors.New("invalid value for required argument 'ShareName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SmbShareAcl
	err := ctx.RegisterResource("truenas:index/smbShareAcl:SmbShareAcl", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSmbShareAcl gets an existing SmbShareAcl resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSmbShareAcl(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SmbShareAclState, opts ...pulumi.ResourceOption) (*SmbShareAcl, error) {
	var resource SmbShareAcl
	err := ctx.ReadResource("truenas:index/smbShareAcl:SmbShareAcl", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SmbShareAcl resources.
type smbShareAclState struct {
	// Ordered list of share ACL entries. Order is significant (DENIED entries are typically listed before ALLOWED ones). At least one entry is required.
	ShareAcls []SmbShareAclShareAcl `pulumi:"shareAcls"`
	// Name of the existing SMB share (truenas_smb_share.name) whose share ACL this resource manages. Changing it forces a new resource (it targets a different share).
	ShareName *string `pulumi:"shareName"`
}

type SmbShareAclState struct {
	// Ordered list of share ACL entries. Order is significant (DENIED entries are typically listed before ALLOWED ones). At least one entry is required.
	ShareAcls SmbShareAclShareAclArrayInput
	// Name of the existing SMB share (truenas_smb_share.name) whose share ACL this resource manages. Changing it forces a new resource (it targets a different share).
	ShareName pulumi.StringPtrInput
}

func (SmbShareAclState) ElementType() reflect.Type {
	return reflect.TypeOf((*smbShareAclState)(nil)).Elem()
}

type smbShareAclArgs struct {
	// Ordered list of share ACL entries. Order is significant (DENIED entries are typically listed before ALLOWED ones). At least one entry is required.
	ShareAcls []SmbShareAclShareAcl `pulumi:"shareAcls"`
	// Name of the existing SMB share (truenas_smb_share.name) whose share ACL this resource manages. Changing it forces a new resource (it targets a different share).
	ShareName string `pulumi:"shareName"`
}

// The set of arguments for constructing a SmbShareAcl resource.
type SmbShareAclArgs struct {
	// Ordered list of share ACL entries. Order is significant (DENIED entries are typically listed before ALLOWED ones). At least one entry is required.
	ShareAcls SmbShareAclShareAclArrayInput
	// Name of the existing SMB share (truenas_smb_share.name) whose share ACL this resource manages. Changing it forces a new resource (it targets a different share).
	ShareName pulumi.StringInput
}

func (SmbShareAclArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*smbShareAclArgs)(nil)).Elem()
}

type SmbShareAclInput interface {
	pulumi.Input

	ToSmbShareAclOutput() SmbShareAclOutput
	ToSmbShareAclOutputWithContext(ctx context.Context) SmbShareAclOutput
}

func (*SmbShareAcl) ElementType() reflect.Type {
	return reflect.TypeOf((**SmbShareAcl)(nil)).Elem()
}

func (i *SmbShareAcl) ToSmbShareAclOutput() SmbShareAclOutput {
	return i.ToSmbShareAclOutputWithContext(context.Background())
}

func (i *SmbShareAcl) ToSmbShareAclOutputWithContext(ctx context.Context) SmbShareAclOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmbShareAclOutput)
}

// SmbShareAclArrayInput is an input type that accepts SmbShareAclArray and SmbShareAclArrayOutput values.
// You can construct a concrete instance of `SmbShareAclArrayInput` via:
//
//	SmbShareAclArray{ SmbShareAclArgs{...} }
type SmbShareAclArrayInput interface {
	pulumi.Input

	ToSmbShareAclArrayOutput() SmbShareAclArrayOutput
	ToSmbShareAclArrayOutputWithContext(context.Context) SmbShareAclArrayOutput
}

type SmbShareAclArray []SmbShareAclInput

func (SmbShareAclArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmbShareAcl)(nil)).Elem()
}

func (i SmbShareAclArray) ToSmbShareAclArrayOutput() SmbShareAclArrayOutput {
	return i.ToSmbShareAclArrayOutputWithContext(context.Background())
}

func (i SmbShareAclArray) ToSmbShareAclArrayOutputWithContext(ctx context.Context) SmbShareAclArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmbShareAclArrayOutput)
}

// SmbShareAclMapInput is an input type that accepts SmbShareAclMap and SmbShareAclMapOutput values.
// You can construct a concrete instance of `SmbShareAclMapInput` via:
//
//	SmbShareAclMap{ "key": SmbShareAclArgs{...} }
type SmbShareAclMapInput interface {
	pulumi.Input

	ToSmbShareAclMapOutput() SmbShareAclMapOutput
	ToSmbShareAclMapOutputWithContext(context.Context) SmbShareAclMapOutput
}

type SmbShareAclMap map[string]SmbShareAclInput

func (SmbShareAclMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmbShareAcl)(nil)).Elem()
}

func (i SmbShareAclMap) ToSmbShareAclMapOutput() SmbShareAclMapOutput {
	return i.ToSmbShareAclMapOutputWithContext(context.Background())
}

func (i SmbShareAclMap) ToSmbShareAclMapOutputWithContext(ctx context.Context) SmbShareAclMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmbShareAclMapOutput)
}

type SmbShareAclOutput struct{ *pulumi.OutputState }

func (SmbShareAclOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SmbShareAcl)(nil)).Elem()
}

func (o SmbShareAclOutput) ToSmbShareAclOutput() SmbShareAclOutput {
	return o
}

func (o SmbShareAclOutput) ToSmbShareAclOutputWithContext(ctx context.Context) SmbShareAclOutput {
	return o
}

// Ordered list of share ACL entries. Order is significant (DENIED entries are typically listed before ALLOWED ones). At least one entry is required.
func (o SmbShareAclOutput) ShareAcls() SmbShareAclShareAclArrayOutput {
	return o.ApplyT(func(v *SmbShareAcl) SmbShareAclShareAclArrayOutput { return v.ShareAcls }).(SmbShareAclShareAclArrayOutput)
}

// Name of the existing SMB share (truenas_smb_share.name) whose share ACL this resource manages. Changing it forces a new resource (it targets a different share).
func (o SmbShareAclOutput) ShareName() pulumi.StringOutput {
	return o.ApplyT(func(v *SmbShareAcl) pulumi.StringOutput { return v.ShareName }).(pulumi.StringOutput)
}

type SmbShareAclArrayOutput struct{ *pulumi.OutputState }

func (SmbShareAclArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmbShareAcl)(nil)).Elem()
}

func (o SmbShareAclArrayOutput) ToSmbShareAclArrayOutput() SmbShareAclArrayOutput {
	return o
}

func (o SmbShareAclArrayOutput) ToSmbShareAclArrayOutputWithContext(ctx context.Context) SmbShareAclArrayOutput {
	return o
}

func (o SmbShareAclArrayOutput) Index(i pulumi.IntInput) SmbShareAclOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SmbShareAcl {
		return vs[0].([]*SmbShareAcl)[vs[1].(int)]
	}).(SmbShareAclOutput)
}

type SmbShareAclMapOutput struct{ *pulumi.OutputState }

func (SmbShareAclMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmbShareAcl)(nil)).Elem()
}

func (o SmbShareAclMapOutput) ToSmbShareAclMapOutput() SmbShareAclMapOutput {
	return o
}

func (o SmbShareAclMapOutput) ToSmbShareAclMapOutputWithContext(ctx context.Context) SmbShareAclMapOutput {
	return o
}

func (o SmbShareAclMapOutput) MapIndex(k pulumi.StringInput) SmbShareAclOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SmbShareAcl {
		return vs[0].(map[string]*SmbShareAcl)[vs[1].(string)]
	}).(SmbShareAclOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SmbShareAclInput)(nil)).Elem(), &SmbShareAcl{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmbShareAclArrayInput)(nil)).Elem(), SmbShareAclArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmbShareAclMapInput)(nil)).Elem(), SmbShareAclMap{})
	pulumi.RegisterOutputType(SmbShareAclOutput{})
	pulumi.RegisterOutputType(SmbShareAclArrayOutput{})
	pulumi.RegisterOutputType(SmbShareAclMapOutput{})
}
