// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SshConfig struct {
	pulumi.CustomResourceState

	// Interfaces to bind the SSH service to. Empty list binds to all interfaces.
	Bindifaces pulumi.StringArrayOutput `pulumi:"bindifaces"`
	// Whether SSH compression is enabled.
	Compression pulumi.BoolOutput `pulumi:"compression"`
	// Whether Kerberos authentication is enabled.
	Kerberosauth pulumi.BoolOutput `pulumi:"kerberosauth"`
	// Extra<span pulumi-lang-nodejs=" sshdConfig " pulumi-lang-dotnet=" SshdConfig " pulumi-lang-go=" sshdConfig " pulumi-lang-python=" sshd_config " pulumi-lang-yaml=" sshdConfig " pulumi-lang-java=" sshdConfig " pulumi-lang-hcl=" sshd_config "> sshdConfig </span>options, appended verbatim.
	Options pulumi.StringOutput `pulumi:"options"`
	// Groups whose members are allowed to authenticate with a password.
	PasswordLoginGroups pulumi.StringArrayOutput `pulumi:"passwordLoginGroups"`
	// Whether password authentication is enabled.
	Passwordauth pulumi.BoolOutput `pulumi:"passwordauth"`
	// SFTP subsystem syslog facility. One of "" (default), DAEMON, USER, AUTH, LOCAL0-LOCAL7. Not validated by this provider.
	SftpLogFacility pulumi.StringOutput `pulumi:"sftpLogFacility"`
	// SFTP subsystem syslog level. One of "" (default), QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2, DEBUG3. Not validated by this provider.
	SftpLogLevel pulumi.StringOutput `pulumi:"sftpLogLevel"`
	// Whether TCP forwarding is enabled.
	Tcpfwd pulumi.BoolOutput `pulumi:"tcpfwd"`
	// TCP port the SSH service listens on.
	Tcpport pulumi.IntOutput `pulumi:"tcpport"`
	// Weak ciphers to allow. Valid values: AES128-CBC, NONE.
	WeakCiphers pulumi.StringArrayOutput `pulumi:"weakCiphers"`
}

// NewSshConfig registers a new resource with the given unique name, arguments, and options.
func NewSshConfig(ctx *pulumi.Context,
	name string, args *SshConfigArgs, opts ...pulumi.ResourceOption) (*SshConfig, error) {
	if args == nil {
		args = &SshConfigArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SshConfig
	err := ctx.RegisterResource("truenas:index/sshConfig:SshConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSshConfig gets an existing SshConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSshConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SshConfigState, opts ...pulumi.ResourceOption) (*SshConfig, error) {
	var resource SshConfig
	err := ctx.ReadResource("truenas:index/sshConfig:SshConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SshConfig resources.
type sshConfigState struct {
	// Interfaces to bind the SSH service to. Empty list binds to all interfaces.
	Bindifaces []string `pulumi:"bindifaces"`
	// Whether SSH compression is enabled.
	Compression *bool `pulumi:"compression"`
	// Whether Kerberos authentication is enabled.
	Kerberosauth *bool `pulumi:"kerberosauth"`
	// Extra<span pulumi-lang-nodejs=" sshdConfig " pulumi-lang-dotnet=" SshdConfig " pulumi-lang-go=" sshdConfig " pulumi-lang-python=" sshd_config " pulumi-lang-yaml=" sshdConfig " pulumi-lang-java=" sshdConfig " pulumi-lang-hcl=" sshd_config "> sshdConfig </span>options, appended verbatim.
	Options *string `pulumi:"options"`
	// Groups whose members are allowed to authenticate with a password.
	PasswordLoginGroups []string `pulumi:"passwordLoginGroups"`
	// Whether password authentication is enabled.
	Passwordauth *bool `pulumi:"passwordauth"`
	// SFTP subsystem syslog facility. One of "" (default), DAEMON, USER, AUTH, LOCAL0-LOCAL7. Not validated by this provider.
	SftpLogFacility *string `pulumi:"sftpLogFacility"`
	// SFTP subsystem syslog level. One of "" (default), QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2, DEBUG3. Not validated by this provider.
	SftpLogLevel *string `pulumi:"sftpLogLevel"`
	// Whether TCP forwarding is enabled.
	Tcpfwd *bool `pulumi:"tcpfwd"`
	// TCP port the SSH service listens on.
	Tcpport *int `pulumi:"tcpport"`
	// Weak ciphers to allow. Valid values: AES128-CBC, NONE.
	WeakCiphers []string `pulumi:"weakCiphers"`
}

type SshConfigState struct {
	// Interfaces to bind the SSH service to. Empty list binds to all interfaces.
	Bindifaces pulumi.StringArrayInput
	// Whether SSH compression is enabled.
	Compression pulumi.BoolPtrInput
	// Whether Kerberos authentication is enabled.
	Kerberosauth pulumi.BoolPtrInput
	// Extra<span pulumi-lang-nodejs=" sshdConfig " pulumi-lang-dotnet=" SshdConfig " pulumi-lang-go=" sshdConfig " pulumi-lang-python=" sshd_config " pulumi-lang-yaml=" sshdConfig " pulumi-lang-java=" sshdConfig " pulumi-lang-hcl=" sshd_config "> sshdConfig </span>options, appended verbatim.
	Options pulumi.StringPtrInput
	// Groups whose members are allowed to authenticate with a password.
	PasswordLoginGroups pulumi.StringArrayInput
	// Whether password authentication is enabled.
	Passwordauth pulumi.BoolPtrInput
	// SFTP subsystem syslog facility. One of "" (default), DAEMON, USER, AUTH, LOCAL0-LOCAL7. Not validated by this provider.
	SftpLogFacility pulumi.StringPtrInput
	// SFTP subsystem syslog level. One of "" (default), QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2, DEBUG3. Not validated by this provider.
	SftpLogLevel pulumi.StringPtrInput
	// Whether TCP forwarding is enabled.
	Tcpfwd pulumi.BoolPtrInput
	// TCP port the SSH service listens on.
	Tcpport pulumi.IntPtrInput
	// Weak ciphers to allow. Valid values: AES128-CBC, NONE.
	WeakCiphers pulumi.StringArrayInput
}

func (SshConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*sshConfigState)(nil)).Elem()
}

type sshConfigArgs struct {
	// Interfaces to bind the SSH service to. Empty list binds to all interfaces.
	Bindifaces []string `pulumi:"bindifaces"`
	// Whether SSH compression is enabled.
	Compression *bool `pulumi:"compression"`
	// Whether Kerberos authentication is enabled.
	Kerberosauth *bool `pulumi:"kerberosauth"`
	// Extra<span pulumi-lang-nodejs=" sshdConfig " pulumi-lang-dotnet=" SshdConfig " pulumi-lang-go=" sshdConfig " pulumi-lang-python=" sshd_config " pulumi-lang-yaml=" sshdConfig " pulumi-lang-java=" sshdConfig " pulumi-lang-hcl=" sshd_config "> sshdConfig </span>options, appended verbatim.
	Options *string `pulumi:"options"`
	// Groups whose members are allowed to authenticate with a password.
	PasswordLoginGroups []string `pulumi:"passwordLoginGroups"`
	// Whether password authentication is enabled.
	Passwordauth *bool `pulumi:"passwordauth"`
	// SFTP subsystem syslog facility. One of "" (default), DAEMON, USER, AUTH, LOCAL0-LOCAL7. Not validated by this provider.
	SftpLogFacility *string `pulumi:"sftpLogFacility"`
	// SFTP subsystem syslog level. One of "" (default), QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2, DEBUG3. Not validated by this provider.
	SftpLogLevel *string `pulumi:"sftpLogLevel"`
	// Whether TCP forwarding is enabled.
	Tcpfwd *bool `pulumi:"tcpfwd"`
	// TCP port the SSH service listens on.
	Tcpport *int `pulumi:"tcpport"`
	// Weak ciphers to allow. Valid values: AES128-CBC, NONE.
	WeakCiphers []string `pulumi:"weakCiphers"`
}

// The set of arguments for constructing a SshConfig resource.
type SshConfigArgs struct {
	// Interfaces to bind the SSH service to. Empty list binds to all interfaces.
	Bindifaces pulumi.StringArrayInput
	// Whether SSH compression is enabled.
	Compression pulumi.BoolPtrInput
	// Whether Kerberos authentication is enabled.
	Kerberosauth pulumi.BoolPtrInput
	// Extra<span pulumi-lang-nodejs=" sshdConfig " pulumi-lang-dotnet=" SshdConfig " pulumi-lang-go=" sshdConfig " pulumi-lang-python=" sshd_config " pulumi-lang-yaml=" sshdConfig " pulumi-lang-java=" sshdConfig " pulumi-lang-hcl=" sshd_config "> sshdConfig </span>options, appended verbatim.
	Options pulumi.StringPtrInput
	// Groups whose members are allowed to authenticate with a password.
	PasswordLoginGroups pulumi.StringArrayInput
	// Whether password authentication is enabled.
	Passwordauth pulumi.BoolPtrInput
	// SFTP subsystem syslog facility. One of "" (default), DAEMON, USER, AUTH, LOCAL0-LOCAL7. Not validated by this provider.
	SftpLogFacility pulumi.StringPtrInput
	// SFTP subsystem syslog level. One of "" (default), QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2, DEBUG3. Not validated by this provider.
	SftpLogLevel pulumi.StringPtrInput
	// Whether TCP forwarding is enabled.
	Tcpfwd pulumi.BoolPtrInput
	// TCP port the SSH service listens on.
	Tcpport pulumi.IntPtrInput
	// Weak ciphers to allow. Valid values: AES128-CBC, NONE.
	WeakCiphers pulumi.StringArrayInput
}

func (SshConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sshConfigArgs)(nil)).Elem()
}

type SshConfigInput interface {
	pulumi.Input

	ToSshConfigOutput() SshConfigOutput
	ToSshConfigOutputWithContext(ctx context.Context) SshConfigOutput
}

func (*SshConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**SshConfig)(nil)).Elem()
}

func (i *SshConfig) ToSshConfigOutput() SshConfigOutput {
	return i.ToSshConfigOutputWithContext(context.Background())
}

func (i *SshConfig) ToSshConfigOutputWithContext(ctx context.Context) SshConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SshConfigOutput)
}

// SshConfigArrayInput is an input type that accepts SshConfigArray and SshConfigArrayOutput values.
// You can construct a concrete instance of `SshConfigArrayInput` via:
//
//	SshConfigArray{ SshConfigArgs{...} }
type SshConfigArrayInput interface {
	pulumi.Input

	ToSshConfigArrayOutput() SshConfigArrayOutput
	ToSshConfigArrayOutputWithContext(context.Context) SshConfigArrayOutput
}

type SshConfigArray []SshConfigInput

func (SshConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SshConfig)(nil)).Elem()
}

func (i SshConfigArray) ToSshConfigArrayOutput() SshConfigArrayOutput {
	return i.ToSshConfigArrayOutputWithContext(context.Background())
}

func (i SshConfigArray) ToSshConfigArrayOutputWithContext(ctx context.Context) SshConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SshConfigArrayOutput)
}

// SshConfigMapInput is an input type that accepts SshConfigMap and SshConfigMapOutput values.
// You can construct a concrete instance of `SshConfigMapInput` via:
//
//	SshConfigMap{ "key": SshConfigArgs{...} }
type SshConfigMapInput interface {
	pulumi.Input

	ToSshConfigMapOutput() SshConfigMapOutput
	ToSshConfigMapOutputWithContext(context.Context) SshConfigMapOutput
}

type SshConfigMap map[string]SshConfigInput

func (SshConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SshConfig)(nil)).Elem()
}

func (i SshConfigMap) ToSshConfigMapOutput() SshConfigMapOutput {
	return i.ToSshConfigMapOutputWithContext(context.Background())
}

func (i SshConfigMap) ToSshConfigMapOutputWithContext(ctx context.Context) SshConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SshConfigMapOutput)
}

type SshConfigOutput struct{ *pulumi.OutputState }

func (SshConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SshConfig)(nil)).Elem()
}

func (o SshConfigOutput) ToSshConfigOutput() SshConfigOutput {
	return o
}

func (o SshConfigOutput) ToSshConfigOutputWithContext(ctx context.Context) SshConfigOutput {
	return o
}

// Interfaces to bind the SSH service to. Empty list binds to all interfaces.
func (o SshConfigOutput) Bindifaces() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.StringArrayOutput { return v.Bindifaces }).(pulumi.StringArrayOutput)
}

// Whether SSH compression is enabled.
func (o SshConfigOutput) Compression() pulumi.BoolOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.BoolOutput { return v.Compression }).(pulumi.BoolOutput)
}

// Whether Kerberos authentication is enabled.
func (o SshConfigOutput) Kerberosauth() pulumi.BoolOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.BoolOutput { return v.Kerberosauth }).(pulumi.BoolOutput)
}

// Extra<span pulumi-lang-nodejs=" sshdConfig " pulumi-lang-dotnet=" SshdConfig " pulumi-lang-go=" sshdConfig " pulumi-lang-python=" sshd_config " pulumi-lang-yaml=" sshdConfig " pulumi-lang-java=" sshdConfig " pulumi-lang-hcl=" sshd_config "> sshdConfig </span>options, appended verbatim.
func (o SshConfigOutput) Options() pulumi.StringOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.StringOutput { return v.Options }).(pulumi.StringOutput)
}

// Groups whose members are allowed to authenticate with a password.
func (o SshConfigOutput) PasswordLoginGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.StringArrayOutput { return v.PasswordLoginGroups }).(pulumi.StringArrayOutput)
}

// Whether password authentication is enabled.
func (o SshConfigOutput) Passwordauth() pulumi.BoolOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.BoolOutput { return v.Passwordauth }).(pulumi.BoolOutput)
}

// SFTP subsystem syslog facility. One of "" (default), DAEMON, USER, AUTH, LOCAL0-LOCAL7. Not validated by this provider.
func (o SshConfigOutput) SftpLogFacility() pulumi.StringOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.StringOutput { return v.SftpLogFacility }).(pulumi.StringOutput)
}

// SFTP subsystem syslog level. One of "" (default), QUIET, FATAL, ERROR, INFO, VERBOSE, DEBUG, DEBUG1, DEBUG2, DEBUG3. Not validated by this provider.
func (o SshConfigOutput) SftpLogLevel() pulumi.StringOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.StringOutput { return v.SftpLogLevel }).(pulumi.StringOutput)
}

// Whether TCP forwarding is enabled.
func (o SshConfigOutput) Tcpfwd() pulumi.BoolOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.BoolOutput { return v.Tcpfwd }).(pulumi.BoolOutput)
}

// TCP port the SSH service listens on.
func (o SshConfigOutput) Tcpport() pulumi.IntOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.IntOutput { return v.Tcpport }).(pulumi.IntOutput)
}

// Weak ciphers to allow. Valid values: AES128-CBC, NONE.
func (o SshConfigOutput) WeakCiphers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SshConfig) pulumi.StringArrayOutput { return v.WeakCiphers }).(pulumi.StringArrayOutput)
}

type SshConfigArrayOutput struct{ *pulumi.OutputState }

func (SshConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SshConfig)(nil)).Elem()
}

func (o SshConfigArrayOutput) ToSshConfigArrayOutput() SshConfigArrayOutput {
	return o
}

func (o SshConfigArrayOutput) ToSshConfigArrayOutputWithContext(ctx context.Context) SshConfigArrayOutput {
	return o
}

func (o SshConfigArrayOutput) Index(i pulumi.IntInput) SshConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SshConfig {
		return vs[0].([]*SshConfig)[vs[1].(int)]
	}).(SshConfigOutput)
}

type SshConfigMapOutput struct{ *pulumi.OutputState }

func (SshConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SshConfig)(nil)).Elem()
}

func (o SshConfigMapOutput) ToSshConfigMapOutput() SshConfigMapOutput {
	return o
}

func (o SshConfigMapOutput) ToSshConfigMapOutputWithContext(ctx context.Context) SshConfigMapOutput {
	return o
}

func (o SshConfigMapOutput) MapIndex(k pulumi.StringInput) SshConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SshConfig {
		return vs[0].(map[string]*SshConfig)[vs[1].(string)]
	}).(SshConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SshConfigInput)(nil)).Elem(), &SshConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*SshConfigArrayInput)(nil)).Elem(), SshConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SshConfigMapInput)(nil)).Elem(), SshConfigMap{})
	pulumi.RegisterOutputType(SshConfigOutput{})
	pulumi.RegisterOutputType(SshConfigArrayOutput{})
	pulumi.RegisterOutputType(SshConfigMapOutput{})
}
