// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SystemDataset struct {
	pulumi.CustomResourceState

	// Base path of the system dataset (e.g. "tank/.system"). Changes whenever pool changes; server-computed, never sent to systemdataset.update.
	Basename pulumi.StringOutput `pulumi:"basename"`
	// Filesystem path the system dataset is mounted at (e.g. "/var/db/system"). Server-computed, never sent to systemdataset.update.
	Path pulumi.StringOutput `pulumi:"path"`
	// Name of the pool the system dataset lives on. WARNING: changing this migrates the system dataset to the new pool, a disruptive, long-running operation.
	Pool pulumi.StringOutput `pulumi:"pool"`
	// Name of a pool to exclude from automatic selection when migrating the system dataset. Write-only: never read back from TrueNAS, and only sent to systemdataset.update when explicitly set.
	PoolExclude pulumi.StringPtrOutput `pulumi:"poolExclude"`
	// Whether the system dataset pool has been explicitly set. Server-computed, never sent to systemdataset.update.
	PoolSet pulumi.BoolOutput `pulumi:"poolSet"`
	// UUID of the system dataset. Server-computed, never sent to systemdataset.update.
	Uuid pulumi.StringOutput `pulumi:"uuid"`
}

// NewSystemDataset registers a new resource with the given unique name, arguments, and options.
func NewSystemDataset(ctx *pulumi.Context,
	name string, args *SystemDatasetArgs, opts ...pulumi.ResourceOption) (*SystemDataset, error) {
	if args == nil {
		args = &SystemDatasetArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SystemDataset
	err := ctx.RegisterResource("truenas:index/systemDataset:SystemDataset", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSystemDataset gets an existing SystemDataset resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSystemDataset(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SystemDatasetState, opts ...pulumi.ResourceOption) (*SystemDataset, error) {
	var resource SystemDataset
	err := ctx.ReadResource("truenas:index/systemDataset:SystemDataset", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SystemDataset resources.
type systemDatasetState struct {
	// Base path of the system dataset (e.g. "tank/.system"). Changes whenever pool changes; server-computed, never sent to systemdataset.update.
	Basename *string `pulumi:"basename"`
	// Filesystem path the system dataset is mounted at (e.g. "/var/db/system"). Server-computed, never sent to systemdataset.update.
	Path *string `pulumi:"path"`
	// Name of the pool the system dataset lives on. WARNING: changing this migrates the system dataset to the new pool, a disruptive, long-running operation.
	Pool *string `pulumi:"pool"`
	// Name of a pool to exclude from automatic selection when migrating the system dataset. Write-only: never read back from TrueNAS, and only sent to systemdataset.update when explicitly set.
	PoolExclude *string `pulumi:"poolExclude"`
	// Whether the system dataset pool has been explicitly set. Server-computed, never sent to systemdataset.update.
	PoolSet *bool `pulumi:"poolSet"`
	// UUID of the system dataset. Server-computed, never sent to systemdataset.update.
	Uuid *string `pulumi:"uuid"`
}

type SystemDatasetState struct {
	// Base path of the system dataset (e.g. "tank/.system"). Changes whenever pool changes; server-computed, never sent to systemdataset.update.
	Basename pulumi.StringPtrInput
	// Filesystem path the system dataset is mounted at (e.g. "/var/db/system"). Server-computed, never sent to systemdataset.update.
	Path pulumi.StringPtrInput
	// Name of the pool the system dataset lives on. WARNING: changing this migrates the system dataset to the new pool, a disruptive, long-running operation.
	Pool pulumi.StringPtrInput
	// Name of a pool to exclude from automatic selection when migrating the system dataset. Write-only: never read back from TrueNAS, and only sent to systemdataset.update when explicitly set.
	PoolExclude pulumi.StringPtrInput
	// Whether the system dataset pool has been explicitly set. Server-computed, never sent to systemdataset.update.
	PoolSet pulumi.BoolPtrInput
	// UUID of the system dataset. Server-computed, never sent to systemdataset.update.
	Uuid pulumi.StringPtrInput
}

func (SystemDatasetState) ElementType() reflect.Type {
	return reflect.TypeOf((*systemDatasetState)(nil)).Elem()
}

type systemDatasetArgs struct {
	// Name of the pool the system dataset lives on. WARNING: changing this migrates the system dataset to the new pool, a disruptive, long-running operation.
	Pool *string `pulumi:"pool"`
	// Name of a pool to exclude from automatic selection when migrating the system dataset. Write-only: never read back from TrueNAS, and only sent to systemdataset.update when explicitly set.
	PoolExclude *string `pulumi:"poolExclude"`
}

// The set of arguments for constructing a SystemDataset resource.
type SystemDatasetArgs struct {
	// Name of the pool the system dataset lives on. WARNING: changing this migrates the system dataset to the new pool, a disruptive, long-running operation.
	Pool pulumi.StringPtrInput
	// Name of a pool to exclude from automatic selection when migrating the system dataset. Write-only: never read back from TrueNAS, and only sent to systemdataset.update when explicitly set.
	PoolExclude pulumi.StringPtrInput
}

func (SystemDatasetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*systemDatasetArgs)(nil)).Elem()
}

type SystemDatasetInput interface {
	pulumi.Input

	ToSystemDatasetOutput() SystemDatasetOutput
	ToSystemDatasetOutputWithContext(ctx context.Context) SystemDatasetOutput
}

func (*SystemDataset) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemDataset)(nil)).Elem()
}

func (i *SystemDataset) ToSystemDatasetOutput() SystemDatasetOutput {
	return i.ToSystemDatasetOutputWithContext(context.Background())
}

func (i *SystemDataset) ToSystemDatasetOutputWithContext(ctx context.Context) SystemDatasetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemDatasetOutput)
}

// SystemDatasetArrayInput is an input type that accepts SystemDatasetArray and SystemDatasetArrayOutput values.
// You can construct a concrete instance of `SystemDatasetArrayInput` via:
//
//	SystemDatasetArray{ SystemDatasetArgs{...} }
type SystemDatasetArrayInput interface {
	pulumi.Input

	ToSystemDatasetArrayOutput() SystemDatasetArrayOutput
	ToSystemDatasetArrayOutputWithContext(context.Context) SystemDatasetArrayOutput
}

type SystemDatasetArray []SystemDatasetInput

func (SystemDatasetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SystemDataset)(nil)).Elem()
}

func (i SystemDatasetArray) ToSystemDatasetArrayOutput() SystemDatasetArrayOutput {
	return i.ToSystemDatasetArrayOutputWithContext(context.Background())
}

func (i SystemDatasetArray) ToSystemDatasetArrayOutputWithContext(ctx context.Context) SystemDatasetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemDatasetArrayOutput)
}

// SystemDatasetMapInput is an input type that accepts SystemDatasetMap and SystemDatasetMapOutput values.
// You can construct a concrete instance of `SystemDatasetMapInput` via:
//
//	SystemDatasetMap{ "key": SystemDatasetArgs{...} }
type SystemDatasetMapInput interface {
	pulumi.Input

	ToSystemDatasetMapOutput() SystemDatasetMapOutput
	ToSystemDatasetMapOutputWithContext(context.Context) SystemDatasetMapOutput
}

type SystemDatasetMap map[string]SystemDatasetInput

func (SystemDatasetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SystemDataset)(nil)).Elem()
}

func (i SystemDatasetMap) ToSystemDatasetMapOutput() SystemDatasetMapOutput {
	return i.ToSystemDatasetMapOutputWithContext(context.Background())
}

func (i SystemDatasetMap) ToSystemDatasetMapOutputWithContext(ctx context.Context) SystemDatasetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemDatasetMapOutput)
}

type SystemDatasetOutput struct{ *pulumi.OutputState }

func (SystemDatasetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemDataset)(nil)).Elem()
}

func (o SystemDatasetOutput) ToSystemDatasetOutput() SystemDatasetOutput {
	return o
}

func (o SystemDatasetOutput) ToSystemDatasetOutputWithContext(ctx context.Context) SystemDatasetOutput {
	return o
}

// Base path of the system dataset (e.g. "tank/.system"). Changes whenever pool changes; server-computed, never sent to systemdataset.update.
func (o SystemDatasetOutput) Basename() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemDataset) pulumi.StringOutput { return v.Basename }).(pulumi.StringOutput)
}

// Filesystem path the system dataset is mounted at (e.g. "/var/db/system"). Server-computed, never sent to systemdataset.update.
func (o SystemDatasetOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemDataset) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

// Name of the pool the system dataset lives on. WARNING: changing this migrates the system dataset to the new pool, a disruptive, long-running operation.
func (o SystemDatasetOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemDataset) pulumi.StringOutput { return v.Pool }).(pulumi.StringOutput)
}

// Name of a pool to exclude from automatic selection when migrating the system dataset. Write-only: never read back from TrueNAS, and only sent to systemdataset.update when explicitly set.
func (o SystemDatasetOutput) PoolExclude() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SystemDataset) pulumi.StringPtrOutput { return v.PoolExclude }).(pulumi.StringPtrOutput)
}

// Whether the system dataset pool has been explicitly set. Server-computed, never sent to systemdataset.update.
func (o SystemDatasetOutput) PoolSet() pulumi.BoolOutput {
	return o.ApplyT(func(v *SystemDataset) pulumi.BoolOutput { return v.PoolSet }).(pulumi.BoolOutput)
}

// UUID of the system dataset. Server-computed, never sent to systemdataset.update.
func (o SystemDatasetOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v *SystemDataset) pulumi.StringOutput { return v.Uuid }).(pulumi.StringOutput)
}

type SystemDatasetArrayOutput struct{ *pulumi.OutputState }

func (SystemDatasetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SystemDataset)(nil)).Elem()
}

func (o SystemDatasetArrayOutput) ToSystemDatasetArrayOutput() SystemDatasetArrayOutput {
	return o
}

func (o SystemDatasetArrayOutput) ToSystemDatasetArrayOutputWithContext(ctx context.Context) SystemDatasetArrayOutput {
	return o
}

func (o SystemDatasetArrayOutput) Index(i pulumi.IntInput) SystemDatasetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SystemDataset {
		return vs[0].([]*SystemDataset)[vs[1].(int)]
	}).(SystemDatasetOutput)
}

type SystemDatasetMapOutput struct{ *pulumi.OutputState }

func (SystemDatasetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SystemDataset)(nil)).Elem()
}

func (o SystemDatasetMapOutput) ToSystemDatasetMapOutput() SystemDatasetMapOutput {
	return o
}

func (o SystemDatasetMapOutput) ToSystemDatasetMapOutputWithContext(ctx context.Context) SystemDatasetMapOutput {
	return o
}

func (o SystemDatasetMapOutput) MapIndex(k pulumi.StringInput) SystemDatasetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SystemDataset {
		return vs[0].(map[string]*SystemDataset)[vs[1].(string)]
	}).(SystemDatasetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SystemDatasetInput)(nil)).Elem(), &SystemDataset{})
	pulumi.RegisterInputType(reflect.TypeOf((*SystemDatasetArrayInput)(nil)).Elem(), SystemDatasetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SystemDatasetMapInput)(nil)).Elem(), SystemDatasetMap{})
	pulumi.RegisterOutputType(SystemDatasetOutput{})
	pulumi.RegisterOutputType(SystemDatasetArrayOutput{})
	pulumi.RegisterOutputType(SystemDatasetMapOutput{})
}
