// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type User struct {
	pulumi.CustomResourceState

	// Whether this is a built-in system user.
	Builtin pulumi.BoolOutput `pulumi:"builtin"`
	// User's email address.
	Email pulumi.StringOutput `pulumi:"email"`
	// User's full name.
	FullName pulumi.StringOutput `pulumi:"fullName"`
	// Primary group ID for the user. Either 'group' or 'group_create' must be set when creating a user.
	Group pulumi.IntOutput `pulumi:"group"`
	// When true, creates a new primary group matching the username instead of using an existing group id from 'group'. Write-only: only sent on create, never read back into state.
	GroupCreate pulumi.BoolPtrOutput `pulumi:"groupCreate"`
	// List of additional group IDs the user belongs to.
	Groups pulumi.IntArrayOutput `pulumi:"groups"`
	// Home directory path.
	Home pulumi.StringOutput `pulumi:"home"`
	// Octal permission mode for the user's home directory, e.g. "700". Write-only: accepted on create/update but not returned by the API, so it is not read back or drift-detected.
	HomeMode pulumi.StringPtrOutput `pulumi:"homeMode"`
	// Whether this user cannot be modified.
	Immutable pulumi.BoolOutput `pulumi:"immutable"`
	// Whether this is a local user (vs. directory service).
	Local pulumi.BoolOutput `pulumi:"local"`
	// Whether the user account is locked.
	Locked pulumi.BoolOutput `pulumi:"locked"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// User password. Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// Whether password authentication is disabled.
	PasswordDisabled pulumi.BoolOutput `pulumi:"passwordDisabled"`
	// Login shell path.
	Shell pulumi.StringOutput `pulumi:"shell"`
	// Whether the user has SMB authentication enabled.
	Smb pulumi.BoolOutput `pulumi:"smb"`
	// Whether SSH password authentication is enabled.
	SshPasswordEnabled pulumi.BoolOutput `pulumi:"sshPasswordEnabled"`
	// SSH public key(s) for the user.
	Sshpubkey pulumi.StringOutput `pulumi:"sshpubkey"`
	// List of allowed sudo commands.
	SudoCommands pulumi.StringArrayOutput `pulumi:"sudoCommands"`
	// List of sudo commands allowed without password.
	SudoCommandsNopasswds pulumi.StringArrayOutput `pulumi:"sudoCommandsNopasswds"`
	// UNIX UID for the user (auto-assigned if omitted). Changing this forces a new resource.
	Uid pulumi.IntOutput `pulumi:"uid"`
	// Login username. Changing this forces a new resource.
	Username pulumi.StringOutput `pulumi:"username"`
	// Grant the user access to the web-based file share. Requires TrueNAS 26.0 or newer; on older releases it is ignored (the API does not accept it).
	Webshare pulumi.BoolOutput `pulumi:"webshare"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("truenas:index/user:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("truenas:index/user:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	// Whether this is a built-in system user.
	Builtin *bool `pulumi:"builtin"`
	// User's email address.
	Email *string `pulumi:"email"`
	// User's full name.
	FullName *string `pulumi:"fullName"`
	// Primary group ID for the user. Either 'group' or 'group_create' must be set when creating a user.
	Group *int `pulumi:"group"`
	// When true, creates a new primary group matching the username instead of using an existing group id from 'group'. Write-only: only sent on create, never read back into state.
	GroupCreate *bool `pulumi:"groupCreate"`
	// List of additional group IDs the user belongs to.
	Groups []int `pulumi:"groups"`
	// Home directory path.
	Home *string `pulumi:"home"`
	// Octal permission mode for the user's home directory, e.g. "700". Write-only: accepted on create/update but not returned by the API, so it is not read back or drift-detected.
	HomeMode *string `pulumi:"homeMode"`
	// Whether this user cannot be modified.
	Immutable *bool `pulumi:"immutable"`
	// Whether this is a local user (vs. directory service).
	Local *bool `pulumi:"local"`
	// Whether the user account is locked.
	Locked *bool `pulumi:"locked"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// User password. Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Password *string `pulumi:"password"`
	// Whether password authentication is disabled.
	PasswordDisabled *bool `pulumi:"passwordDisabled"`
	// Login shell path.
	Shell *string `pulumi:"shell"`
	// Whether the user has SMB authentication enabled.
	Smb *bool `pulumi:"smb"`
	// Whether SSH password authentication is enabled.
	SshPasswordEnabled *bool `pulumi:"sshPasswordEnabled"`
	// SSH public key(s) for the user.
	Sshpubkey *string `pulumi:"sshpubkey"`
	// List of allowed sudo commands.
	SudoCommands []string `pulumi:"sudoCommands"`
	// List of sudo commands allowed without password.
	SudoCommandsNopasswds []string `pulumi:"sudoCommandsNopasswds"`
	// UNIX UID for the user (auto-assigned if omitted). Changing this forces a new resource.
	Uid *int `pulumi:"uid"`
	// Login username. Changing this forces a new resource.
	Username *string `pulumi:"username"`
	// Grant the user access to the web-based file share. Requires TrueNAS 26.0 or newer; on older releases it is ignored (the API does not accept it).
	Webshare *bool `pulumi:"webshare"`
}

type UserState struct {
	// Whether this is a built-in system user.
	Builtin pulumi.BoolPtrInput
	// User's email address.
	Email pulumi.StringPtrInput
	// User's full name.
	FullName pulumi.StringPtrInput
	// Primary group ID for the user. Either 'group' or 'group_create' must be set when creating a user.
	Group pulumi.IntPtrInput
	// When true, creates a new primary group matching the username instead of using an existing group id from 'group'. Write-only: only sent on create, never read back into state.
	GroupCreate pulumi.BoolPtrInput
	// List of additional group IDs the user belongs to.
	Groups pulumi.IntArrayInput
	// Home directory path.
	Home pulumi.StringPtrInput
	// Octal permission mode for the user's home directory, e.g. "700". Write-only: accepted on create/update but not returned by the API, so it is not read back or drift-detected.
	HomeMode pulumi.StringPtrInput
	// Whether this user cannot be modified.
	Immutable pulumi.BoolPtrInput
	// Whether this is a local user (vs. directory service).
	Local pulumi.BoolPtrInput
	// Whether the user account is locked.
	Locked pulumi.BoolPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// User password. Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Password pulumi.StringPtrInput
	// Whether password authentication is disabled.
	PasswordDisabled pulumi.BoolPtrInput
	// Login shell path.
	Shell pulumi.StringPtrInput
	// Whether the user has SMB authentication enabled.
	Smb pulumi.BoolPtrInput
	// Whether SSH password authentication is enabled.
	SshPasswordEnabled pulumi.BoolPtrInput
	// SSH public key(s) for the user.
	Sshpubkey pulumi.StringPtrInput
	// List of allowed sudo commands.
	SudoCommands pulumi.StringArrayInput
	// List of sudo commands allowed without password.
	SudoCommandsNopasswds pulumi.StringArrayInput
	// UNIX UID for the user (auto-assigned if omitted). Changing this forces a new resource.
	Uid pulumi.IntPtrInput
	// Login username. Changing this forces a new resource.
	Username pulumi.StringPtrInput
	// Grant the user access to the web-based file share. Requires TrueNAS 26.0 or newer; on older releases it is ignored (the API does not accept it).
	Webshare pulumi.BoolPtrInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// User's email address.
	Email *string `pulumi:"email"`
	// User's full name.
	FullName *string `pulumi:"fullName"`
	// Primary group ID for the user. Either 'group' or 'group_create' must be set when creating a user.
	Group *int `pulumi:"group"`
	// When true, creates a new primary group matching the username instead of using an existing group id from 'group'. Write-only: only sent on create, never read back into state.
	GroupCreate *bool `pulumi:"groupCreate"`
	// List of additional group IDs the user belongs to.
	Groups []int `pulumi:"groups"`
	// Home directory path.
	Home *string `pulumi:"home"`
	// Octal permission mode for the user's home directory, e.g. "700". Write-only: accepted on create/update but not returned by the API, so it is not read back or drift-detected.
	HomeMode *string `pulumi:"homeMode"`
	// Whether the user account is locked.
	Locked *bool `pulumi:"locked"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// User password. Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Password *string `pulumi:"password"`
	// Whether password authentication is disabled.
	PasswordDisabled *bool `pulumi:"passwordDisabled"`
	// Login shell path.
	Shell *string `pulumi:"shell"`
	// Whether the user has SMB authentication enabled.
	Smb *bool `pulumi:"smb"`
	// Whether SSH password authentication is enabled.
	SshPasswordEnabled *bool `pulumi:"sshPasswordEnabled"`
	// SSH public key(s) for the user.
	Sshpubkey *string `pulumi:"sshpubkey"`
	// List of allowed sudo commands.
	SudoCommands []string `pulumi:"sudoCommands"`
	// List of sudo commands allowed without password.
	SudoCommandsNopasswds []string `pulumi:"sudoCommandsNopasswds"`
	// UNIX UID for the user (auto-assigned if omitted). Changing this forces a new resource.
	Uid *int `pulumi:"uid"`
	// Login username. Changing this forces a new resource.
	Username string `pulumi:"username"`
	// Grant the user access to the web-based file share. Requires TrueNAS 26.0 or newer; on older releases it is ignored (the API does not accept it).
	Webshare *bool `pulumi:"webshare"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// User's email address.
	Email pulumi.StringPtrInput
	// User's full name.
	FullName pulumi.StringPtrInput
	// Primary group ID for the user. Either 'group' or 'group_create' must be set when creating a user.
	Group pulumi.IntPtrInput
	// When true, creates a new primary group matching the username instead of using an existing group id from 'group'. Write-only: only sent on create, never read back into state.
	GroupCreate pulumi.BoolPtrInput
	// List of additional group IDs the user belongs to.
	Groups pulumi.IntArrayInput
	// Home directory path.
	Home pulumi.StringPtrInput
	// Octal permission mode for the user's home directory, e.g. "700". Write-only: accepted on create/update but not returned by the API, so it is not read back or drift-detected.
	HomeMode pulumi.StringPtrInput
	// Whether the user account is locked.
	Locked pulumi.BoolPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// User password. Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
	Password pulumi.StringPtrInput
	// Whether password authentication is disabled.
	PasswordDisabled pulumi.BoolPtrInput
	// Login shell path.
	Shell pulumi.StringPtrInput
	// Whether the user has SMB authentication enabled.
	Smb pulumi.BoolPtrInput
	// Whether SSH password authentication is enabled.
	SshPasswordEnabled pulumi.BoolPtrInput
	// SSH public key(s) for the user.
	Sshpubkey pulumi.StringPtrInput
	// List of allowed sudo commands.
	SudoCommands pulumi.StringArrayInput
	// List of sudo commands allowed without password.
	SudoCommandsNopasswds pulumi.StringArrayInput
	// UNIX UID for the user (auto-assigned if omitted). Changing this forces a new resource.
	Uid pulumi.IntPtrInput
	// Login username. Changing this forces a new resource.
	Username pulumi.StringInput
	// Grant the user access to the web-based file share. Requires TrueNAS 26.0 or newer; on older releases it is ignored (the API does not accept it).
	Webshare pulumi.BoolPtrInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

// UserArrayInput is an input type that accepts UserArray and UserArrayOutput values.
// You can construct a concrete instance of `UserArrayInput` via:
//
//	UserArray{ UserArgs{...} }
type UserArrayInput interface {
	pulumi.Input

	ToUserArrayOutput() UserArrayOutput
	ToUserArrayOutputWithContext(context.Context) UserArrayOutput
}

type UserArray []UserInput

func (UserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (i UserArray) ToUserArrayOutput() UserArrayOutput {
	return i.ToUserArrayOutputWithContext(context.Background())
}

func (i UserArray) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserArrayOutput)
}

// UserMapInput is an input type that accepts UserMap and UserMapOutput values.
// You can construct a concrete instance of `UserMapInput` via:
//
//	UserMap{ "key": UserArgs{...} }
type UserMapInput interface {
	pulumi.Input

	ToUserMapOutput() UserMapOutput
	ToUserMapOutputWithContext(context.Context) UserMapOutput
}

type UserMap map[string]UserInput

func (UserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (i UserMap) ToUserMapOutput() UserMapOutput {
	return i.ToUserMapOutputWithContext(context.Background())
}

func (i UserMap) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserMapOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// Whether this is a built-in system user.
func (o UserOutput) Builtin() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.Builtin }).(pulumi.BoolOutput)
}

// User's email address.
func (o UserOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// User's full name.
func (o UserOutput) FullName() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.FullName }).(pulumi.StringOutput)
}

// Primary group ID for the user. Either 'group' or 'group_create' must be set when creating a user.
func (o UserOutput) Group() pulumi.IntOutput {
	return o.ApplyT(func(v *User) pulumi.IntOutput { return v.Group }).(pulumi.IntOutput)
}

// When true, creates a new primary group matching the username instead of using an existing group id from 'group'. Write-only: only sent on create, never read back into state.
func (o UserOutput) GroupCreate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.GroupCreate }).(pulumi.BoolPtrOutput)
}

// List of additional group IDs the user belongs to.
func (o UserOutput) Groups() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *User) pulumi.IntArrayOutput { return v.Groups }).(pulumi.IntArrayOutput)
}

// Home directory path.
func (o UserOutput) Home() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Home }).(pulumi.StringOutput)
}

// Octal permission mode for the user's home directory, e.g. "700". Write-only: accepted on create/update but not returned by the API, so it is not read back or drift-detected.
func (o UserOutput) HomeMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.HomeMode }).(pulumi.StringPtrOutput)
}

// Whether this user cannot be modified.
func (o UserOutput) Immutable() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.Immutable }).(pulumi.BoolOutput)
}

// Whether this is a local user (vs. directory service).
func (o UserOutput) Local() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.Local }).(pulumi.BoolOutput)
}

// Whether the user account is locked.
func (o UserOutput) Locked() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.Locked }).(pulumi.BoolOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// User password. Write-only: never stored in Terraform state. Requires Terraform >= 1.11.
func (o UserOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// Whether password authentication is disabled.
func (o UserOutput) PasswordDisabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.PasswordDisabled }).(pulumi.BoolOutput)
}

// Login shell path.
func (o UserOutput) Shell() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Shell }).(pulumi.StringOutput)
}

// Whether the user has SMB authentication enabled.
func (o UserOutput) Smb() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.Smb }).(pulumi.BoolOutput)
}

// Whether SSH password authentication is enabled.
func (o UserOutput) SshPasswordEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.SshPasswordEnabled }).(pulumi.BoolOutput)
}

// SSH public key(s) for the user.
func (o UserOutput) Sshpubkey() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Sshpubkey }).(pulumi.StringOutput)
}

// List of allowed sudo commands.
func (o UserOutput) SudoCommands() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.SudoCommands }).(pulumi.StringArrayOutput)
}

// List of sudo commands allowed without password.
func (o UserOutput) SudoCommandsNopasswds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.SudoCommandsNopasswds }).(pulumi.StringArrayOutput)
}

// UNIX UID for the user (auto-assigned if omitted). Changing this forces a new resource.
func (o UserOutput) Uid() pulumi.IntOutput {
	return o.ApplyT(func(v *User) pulumi.IntOutput { return v.Uid }).(pulumi.IntOutput)
}

// Login username. Changing this forces a new resource.
func (o UserOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

// Grant the user access to the web-based file share. Requires TrueNAS 26.0 or newer; on older releases it is ignored (the API does not accept it).
func (o UserOutput) Webshare() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.Webshare }).(pulumi.BoolOutput)
}

type UserArrayOutput struct{ *pulumi.OutputState }

func (UserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (o UserArrayOutput) ToUserArrayOutput() UserArrayOutput {
	return o
}

func (o UserArrayOutput) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return o
}

func (o UserArrayOutput) Index(i pulumi.IntInput) UserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *User {
		return vs[0].([]*User)[vs[1].(int)]
	}).(UserOutput)
}

type UserMapOutput struct{ *pulumi.OutputState }

func (UserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (o UserMapOutput) ToUserMapOutput() UserMapOutput {
	return o
}

func (o UserMapOutput) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return o
}

func (o UserMapOutput) MapIndex(k pulumi.StringInput) UserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *User {
		return vs[0].(map[string]*User)[vs[1].(string)]
	}).(UserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserArrayInput)(nil)).Elem(), UserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserMapInput)(nil)).Elem(), UserMap{})
	pulumi.RegisterOutputType(UserOutput{})
	pulumi.RegisterOutputType(UserArrayOutput{})
	pulumi.RegisterOutputType(UserMapOutput{})
}
