// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Vmware struct {
	pulumi.CustomResourceState

	// Valid datastore name which exists on the VMware host.
	Datastore pulumi.StringOutput `pulumi:"datastore"`
	// ZFS filesystem or dataset to use for VMware storage.
	Filesystem pulumi.StringOutput `pulumi:"filesystem"`
	// Valid IP address / hostname of a VMware host. When clustering, this is the vCenter server for the cluster. Validated against the real endpoint at apply time (see the resource-level description).
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password for VMware host authentication. Write-only: never stored in Terraform state. Requires Terraform >= 1.11. Validated against the real vCenter/ESXi endpoint at apply time (see the resource-level description).
	Password pulumi.StringOutput `pulumi:"password"`
	// Current connection and synchronization state with the VMware host.
	State VmwareStateTypeOutput `pulumi:"state"`
	// Credentials used to authorize access to the VMware host.
	Username pulumi.StringOutput `pulumi:"username"`
}

// NewVmware registers a new resource with the given unique name, arguments, and options.
func NewVmware(ctx *pulumi.Context,
	name string, args *VmwareArgs, opts ...pulumi.ResourceOption) (*Vmware, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Datastore == nil {
		return nil, errors.New("invalid value for required argument 'Datastore'")
	}
	if args.Filesystem == nil {
		return nil, errors.New("invalid value for required argument 'Filesystem'")
	}
	if args.Hostname == nil {
		return nil, errors.New("invalid value for required argument 'Hostname'")
	}
	if args.Password == nil {
		return nil, errors.New("invalid value for required argument 'Password'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Vmware
	err := ctx.RegisterResource("truenas:index/vmware:Vmware", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVmware gets an existing Vmware resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVmware(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VmwareState, opts ...pulumi.ResourceOption) (*Vmware, error) {
	var resource Vmware
	err := ctx.ReadResource("truenas:index/vmware:Vmware", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Vmware resources.
type vmwareState struct {
	// Valid datastore name which exists on the VMware host.
	Datastore *string `pulumi:"datastore"`
	// ZFS filesystem or dataset to use for VMware storage.
	Filesystem *string `pulumi:"filesystem"`
	// Valid IP address / hostname of a VMware host. When clustering, this is the vCenter server for the cluster. Validated against the real endpoint at apply time (see the resource-level description).
	Hostname *string `pulumi:"hostname"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password for VMware host authentication. Write-only: never stored in Terraform state. Requires Terraform >= 1.11. Validated against the real vCenter/ESXi endpoint at apply time (see the resource-level description).
	Password *string `pulumi:"password"`
	// Current connection and synchronization state with the VMware host.
	State *VmwareStateType `pulumi:"state"`
	// Credentials used to authorize access to the VMware host.
	Username *string `pulumi:"username"`
}

type VmwareState struct {
	// Valid datastore name which exists on the VMware host.
	Datastore pulumi.StringPtrInput
	// ZFS filesystem or dataset to use for VMware storage.
	Filesystem pulumi.StringPtrInput
	// Valid IP address / hostname of a VMware host. When clustering, this is the vCenter server for the cluster. Validated against the real endpoint at apply time (see the resource-level description).
	Hostname pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password for VMware host authentication. Write-only: never stored in Terraform state. Requires Terraform >= 1.11. Validated against the real vCenter/ESXi endpoint at apply time (see the resource-level description).
	Password pulumi.StringPtrInput
	// Current connection and synchronization state with the VMware host.
	State VmwareStateTypePtrInput
	// Credentials used to authorize access to the VMware host.
	Username pulumi.StringPtrInput
}

func (VmwareState) ElementType() reflect.Type {
	return reflect.TypeOf((*vmwareState)(nil)).Elem()
}

type vmwareArgs struct {
	// Valid datastore name which exists on the VMware host.
	Datastore string `pulumi:"datastore"`
	// ZFS filesystem or dataset to use for VMware storage.
	Filesystem string `pulumi:"filesystem"`
	// Valid IP address / hostname of a VMware host. When clustering, this is the vCenter server for the cluster. Validated against the real endpoint at apply time (see the resource-level description).
	Hostname string `pulumi:"hostname"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password for VMware host authentication. Write-only: never stored in Terraform state. Requires Terraform >= 1.11. Validated against the real vCenter/ESXi endpoint at apply time (see the resource-level description).
	Password string `pulumi:"password"`
	// Credentials used to authorize access to the VMware host.
	Username string `pulumi:"username"`
}

// The set of arguments for constructing a Vmware resource.
type VmwareArgs struct {
	// Valid datastore name which exists on the VMware host.
	Datastore pulumi.StringInput
	// ZFS filesystem or dataset to use for VMware storage.
	Filesystem pulumi.StringInput
	// Valid IP address / hostname of a VMware host. When clustering, this is the vCenter server for the cluster. Validated against the real endpoint at apply time (see the resource-level description).
	Hostname pulumi.StringInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Password for VMware host authentication. Write-only: never stored in Terraform state. Requires Terraform >= 1.11. Validated against the real vCenter/ESXi endpoint at apply time (see the resource-level description).
	Password pulumi.StringInput
	// Credentials used to authorize access to the VMware host.
	Username pulumi.StringInput
}

func (VmwareArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*vmwareArgs)(nil)).Elem()
}

type VmwareInput interface {
	pulumi.Input

	ToVmwareOutput() VmwareOutput
	ToVmwareOutputWithContext(ctx context.Context) VmwareOutput
}

func (*Vmware) ElementType() reflect.Type {
	return reflect.TypeOf((**Vmware)(nil)).Elem()
}

func (i *Vmware) ToVmwareOutput() VmwareOutput {
	return i.ToVmwareOutputWithContext(context.Background())
}

func (i *Vmware) ToVmwareOutputWithContext(ctx context.Context) VmwareOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmwareOutput)
}

// VmwareArrayInput is an input type that accepts VmwareArray and VmwareArrayOutput values.
// You can construct a concrete instance of `VmwareArrayInput` via:
//
//	VmwareArray{ VmwareArgs{...} }
type VmwareArrayInput interface {
	pulumi.Input

	ToVmwareArrayOutput() VmwareArrayOutput
	ToVmwareArrayOutputWithContext(context.Context) VmwareArrayOutput
}

type VmwareArray []VmwareInput

func (VmwareArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Vmware)(nil)).Elem()
}

func (i VmwareArray) ToVmwareArrayOutput() VmwareArrayOutput {
	return i.ToVmwareArrayOutputWithContext(context.Background())
}

func (i VmwareArray) ToVmwareArrayOutputWithContext(ctx context.Context) VmwareArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmwareArrayOutput)
}

// VmwareMapInput is an input type that accepts VmwareMap and VmwareMapOutput values.
// You can construct a concrete instance of `VmwareMapInput` via:
//
//	VmwareMap{ "key": VmwareArgs{...} }
type VmwareMapInput interface {
	pulumi.Input

	ToVmwareMapOutput() VmwareMapOutput
	ToVmwareMapOutputWithContext(context.Context) VmwareMapOutput
}

type VmwareMap map[string]VmwareInput

func (VmwareMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Vmware)(nil)).Elem()
}

func (i VmwareMap) ToVmwareMapOutput() VmwareMapOutput {
	return i.ToVmwareMapOutputWithContext(context.Background())
}

func (i VmwareMap) ToVmwareMapOutputWithContext(ctx context.Context) VmwareMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VmwareMapOutput)
}

type VmwareOutput struct{ *pulumi.OutputState }

func (VmwareOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Vmware)(nil)).Elem()
}

func (o VmwareOutput) ToVmwareOutput() VmwareOutput {
	return o
}

func (o VmwareOutput) ToVmwareOutputWithContext(ctx context.Context) VmwareOutput {
	return o
}

// Valid datastore name which exists on the VMware host.
func (o VmwareOutput) Datastore() pulumi.StringOutput {
	return o.ApplyT(func(v *Vmware) pulumi.StringOutput { return v.Datastore }).(pulumi.StringOutput)
}

// ZFS filesystem or dataset to use for VMware storage.
func (o VmwareOutput) Filesystem() pulumi.StringOutput {
	return o.ApplyT(func(v *Vmware) pulumi.StringOutput { return v.Filesystem }).(pulumi.StringOutput)
}

// Valid IP address / hostname of a VMware host. When clustering, this is the vCenter server for the cluster. Validated against the real endpoint at apply time (see the resource-level description).
func (o VmwareOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *Vmware) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Password for VMware host authentication. Write-only: never stored in Terraform state. Requires Terraform >= 1.11. Validated against the real vCenter/ESXi endpoint at apply time (see the resource-level description).
func (o VmwareOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v *Vmware) pulumi.StringOutput { return v.Password }).(pulumi.StringOutput)
}

// Current connection and synchronization state with the VMware host.
func (o VmwareOutput) State() VmwareStateTypeOutput {
	return o.ApplyT(func(v *Vmware) VmwareStateTypeOutput { return v.State }).(VmwareStateTypeOutput)
}

// Credentials used to authorize access to the VMware host.
func (o VmwareOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *Vmware) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

type VmwareArrayOutput struct{ *pulumi.OutputState }

func (VmwareArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Vmware)(nil)).Elem()
}

func (o VmwareArrayOutput) ToVmwareArrayOutput() VmwareArrayOutput {
	return o
}

func (o VmwareArrayOutput) ToVmwareArrayOutputWithContext(ctx context.Context) VmwareArrayOutput {
	return o
}

func (o VmwareArrayOutput) Index(i pulumi.IntInput) VmwareOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Vmware {
		return vs[0].([]*Vmware)[vs[1].(int)]
	}).(VmwareOutput)
}

type VmwareMapOutput struct{ *pulumi.OutputState }

func (VmwareMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Vmware)(nil)).Elem()
}

func (o VmwareMapOutput) ToVmwareMapOutput() VmwareMapOutput {
	return o
}

func (o VmwareMapOutput) ToVmwareMapOutputWithContext(ctx context.Context) VmwareMapOutput {
	return o
}

func (o VmwareMapOutput) MapIndex(k pulumi.StringInput) VmwareOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Vmware {
		return vs[0].(map[string]*Vmware)[vs[1].(string)]
	}).(VmwareOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VmwareInput)(nil)).Elem(), &Vmware{})
	pulumi.RegisterInputType(reflect.TypeOf((*VmwareArrayInput)(nil)).Elem(), VmwareArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VmwareMapInput)(nil)).Elem(), VmwareMap{})
	pulumi.RegisterOutputType(VmwareOutput{})
	pulumi.RegisterOutputType(VmwareArrayOutput{})
	pulumi.RegisterOutputType(VmwareMapOutput{})
}
