// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Webshare struct {
	pulumi.CustomResourceState

	// Dataset name component of path (e.g. "tank/share"), or null if it cannot be resolved. Probed live: this can read back null immediately after create — see the resource documentation's known-quirks note — even though it settles to a real value on a subsequent read or update.
	Dataset pulumi.StringOutput `pulumi:"dataset"`
	// Whether the share is available. Defaults to true (matches the API's own default).
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// If set, this share is used as the base path for user home directories. Only one share on the system can have this enabled — setting it here on more than one<span pulumi-lang-nodejs=" truenas.Webshare " pulumi-lang-dotnet=" truenas.Webshare " pulumi-lang-go=" Webshare " pulumi-lang-python=" Webshare " pulumi-lang-yaml=" truenas.Webshare " pulumi-lang-java=" truenas.Webshare " pulumi-lang-hcl=" truenas_webshare "> truenas.Webshare </span>resource, or on a system where another share already has it set outside Terraform, produces undefined API-side behavior. Defaults to false.
	IsHomeBase pulumi.BoolOutput `pulumi:"isHomeBase"`
	// Whether the share path is currently on a locked (encrypted, unmounted) dataset, or null if lock status is unavailable.
	Locked pulumi.BoolOutput `pulumi:"locked"`
	// Webshare share name. Mutable: sharing.webshare.update accepts and applies a rename (probed live).
	Name pulumi.StringOutput `pulumi:"name"`
	// Local server path to share by using the Webshare protocol. Must start with "/mnt/" and be in a ZFS pool (e.g. /mnt/tank/share). Changing it replaces the share (this provider's convention for share paths, mirroring truenas_smb_share/truenas_nfs_share, even though sharing.webshare.update does accept a "path" key).
	Path pulumi.StringOutput `pulumi:"path"`
	// Relative path component within the dataset (e.g. "subdir/data", or "" when path IS the dataset's own mountpoint), or null if it cannot be resolved. Subject to the same create-time null quirk as "dataset" — see its description.
	RelativePath pulumi.StringOutput `pulumi:"relativePath"`
}

// NewWebshare registers a new resource with the given unique name, arguments, and options.
func NewWebshare(ctx *pulumi.Context,
	name string, args *WebshareArgs, opts ...pulumi.ResourceOption) (*Webshare, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Path == nil {
		return nil, errors.New("invalid value for required argument 'Path'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Webshare
	err := ctx.RegisterResource("truenas:index/webshare:Webshare", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWebshare gets an existing Webshare resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWebshare(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WebshareState, opts ...pulumi.ResourceOption) (*Webshare, error) {
	var resource Webshare
	err := ctx.ReadResource("truenas:index/webshare:Webshare", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Webshare resources.
type webshareState struct {
	// Dataset name component of path (e.g. "tank/share"), or null if it cannot be resolved. Probed live: this can read back null immediately after create — see the resource documentation's known-quirks note — even though it settles to a real value on a subsequent read or update.
	Dataset *string `pulumi:"dataset"`
	// Whether the share is available. Defaults to true (matches the API's own default).
	Enabled *bool `pulumi:"enabled"`
	// If set, this share is used as the base path for user home directories. Only one share on the system can have this enabled — setting it here on more than one<span pulumi-lang-nodejs=" truenas.Webshare " pulumi-lang-dotnet=" truenas.Webshare " pulumi-lang-go=" Webshare " pulumi-lang-python=" Webshare " pulumi-lang-yaml=" truenas.Webshare " pulumi-lang-java=" truenas.Webshare " pulumi-lang-hcl=" truenas_webshare "> truenas.Webshare </span>resource, or on a system where another share already has it set outside Terraform, produces undefined API-side behavior. Defaults to false.
	IsHomeBase *bool `pulumi:"isHomeBase"`
	// Whether the share path is currently on a locked (encrypted, unmounted) dataset, or null if lock status is unavailable.
	Locked *bool `pulumi:"locked"`
	// Webshare share name. Mutable: sharing.webshare.update accepts and applies a rename (probed live).
	Name *string `pulumi:"name"`
	// Local server path to share by using the Webshare protocol. Must start with "/mnt/" and be in a ZFS pool (e.g. /mnt/tank/share). Changing it replaces the share (this provider's convention for share paths, mirroring truenas_smb_share/truenas_nfs_share, even though sharing.webshare.update does accept a "path" key).
	Path *string `pulumi:"path"`
	// Relative path component within the dataset (e.g. "subdir/data", or "" when path IS the dataset's own mountpoint), or null if it cannot be resolved. Subject to the same create-time null quirk as "dataset" — see its description.
	RelativePath *string `pulumi:"relativePath"`
}

type WebshareState struct {
	// Dataset name component of path (e.g. "tank/share"), or null if it cannot be resolved. Probed live: this can read back null immediately after create — see the resource documentation's known-quirks note — even though it settles to a real value on a subsequent read or update.
	Dataset pulumi.StringPtrInput
	// Whether the share is available. Defaults to true (matches the API's own default).
	Enabled pulumi.BoolPtrInput
	// If set, this share is used as the base path for user home directories. Only one share on the system can have this enabled — setting it here on more than one<span pulumi-lang-nodejs=" truenas.Webshare " pulumi-lang-dotnet=" truenas.Webshare " pulumi-lang-go=" Webshare " pulumi-lang-python=" Webshare " pulumi-lang-yaml=" truenas.Webshare " pulumi-lang-java=" truenas.Webshare " pulumi-lang-hcl=" truenas_webshare "> truenas.Webshare </span>resource, or on a system where another share already has it set outside Terraform, produces undefined API-side behavior. Defaults to false.
	IsHomeBase pulumi.BoolPtrInput
	// Whether the share path is currently on a locked (encrypted, unmounted) dataset, or null if lock status is unavailable.
	Locked pulumi.BoolPtrInput
	// Webshare share name. Mutable: sharing.webshare.update accepts and applies a rename (probed live).
	Name pulumi.StringPtrInput
	// Local server path to share by using the Webshare protocol. Must start with "/mnt/" and be in a ZFS pool (e.g. /mnt/tank/share). Changing it replaces the share (this provider's convention for share paths, mirroring truenas_smb_share/truenas_nfs_share, even though sharing.webshare.update does accept a "path" key).
	Path pulumi.StringPtrInput
	// Relative path component within the dataset (e.g. "subdir/data", or "" when path IS the dataset's own mountpoint), or null if it cannot be resolved. Subject to the same create-time null quirk as "dataset" — see its description.
	RelativePath pulumi.StringPtrInput
}

func (WebshareState) ElementType() reflect.Type {
	return reflect.TypeOf((*webshareState)(nil)).Elem()
}

type webshareArgs struct {
	// Whether the share is available. Defaults to true (matches the API's own default).
	Enabled *bool `pulumi:"enabled"`
	// If set, this share is used as the base path for user home directories. Only one share on the system can have this enabled — setting it here on more than one<span pulumi-lang-nodejs=" truenas.Webshare " pulumi-lang-dotnet=" truenas.Webshare " pulumi-lang-go=" Webshare " pulumi-lang-python=" Webshare " pulumi-lang-yaml=" truenas.Webshare " pulumi-lang-java=" truenas.Webshare " pulumi-lang-hcl=" truenas_webshare "> truenas.Webshare </span>resource, or on a system where another share already has it set outside Terraform, produces undefined API-side behavior. Defaults to false.
	IsHomeBase *bool `pulumi:"isHomeBase"`
	// Webshare share name. Mutable: sharing.webshare.update accepts and applies a rename (probed live).
	Name string `pulumi:"name"`
	// Local server path to share by using the Webshare protocol. Must start with "/mnt/" and be in a ZFS pool (e.g. /mnt/tank/share). Changing it replaces the share (this provider's convention for share paths, mirroring truenas_smb_share/truenas_nfs_share, even though sharing.webshare.update does accept a "path" key).
	Path string `pulumi:"path"`
}

// The set of arguments for constructing a Webshare resource.
type WebshareArgs struct {
	// Whether the share is available. Defaults to true (matches the API's own default).
	Enabled pulumi.BoolPtrInput
	// If set, this share is used as the base path for user home directories. Only one share on the system can have this enabled — setting it here on more than one<span pulumi-lang-nodejs=" truenas.Webshare " pulumi-lang-dotnet=" truenas.Webshare " pulumi-lang-go=" Webshare " pulumi-lang-python=" Webshare " pulumi-lang-yaml=" truenas.Webshare " pulumi-lang-java=" truenas.Webshare " pulumi-lang-hcl=" truenas_webshare "> truenas.Webshare </span>resource, or on a system where another share already has it set outside Terraform, produces undefined API-side behavior. Defaults to false.
	IsHomeBase pulumi.BoolPtrInput
	// Webshare share name. Mutable: sharing.webshare.update accepts and applies a rename (probed live).
	Name pulumi.StringInput
	// Local server path to share by using the Webshare protocol. Must start with "/mnt/" and be in a ZFS pool (e.g. /mnt/tank/share). Changing it replaces the share (this provider's convention for share paths, mirroring truenas_smb_share/truenas_nfs_share, even though sharing.webshare.update does accept a "path" key).
	Path pulumi.StringInput
}

func (WebshareArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*webshareArgs)(nil)).Elem()
}

type WebshareInput interface {
	pulumi.Input

	ToWebshareOutput() WebshareOutput
	ToWebshareOutputWithContext(ctx context.Context) WebshareOutput
}

func (*Webshare) ElementType() reflect.Type {
	return reflect.TypeOf((**Webshare)(nil)).Elem()
}

func (i *Webshare) ToWebshareOutput() WebshareOutput {
	return i.ToWebshareOutputWithContext(context.Background())
}

func (i *Webshare) ToWebshareOutputWithContext(ctx context.Context) WebshareOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebshareOutput)
}

// WebshareArrayInput is an input type that accepts WebshareArray and WebshareArrayOutput values.
// You can construct a concrete instance of `WebshareArrayInput` via:
//
//	WebshareArray{ WebshareArgs{...} }
type WebshareArrayInput interface {
	pulumi.Input

	ToWebshareArrayOutput() WebshareArrayOutput
	ToWebshareArrayOutputWithContext(context.Context) WebshareArrayOutput
}

type WebshareArray []WebshareInput

func (WebshareArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Webshare)(nil)).Elem()
}

func (i WebshareArray) ToWebshareArrayOutput() WebshareArrayOutput {
	return i.ToWebshareArrayOutputWithContext(context.Background())
}

func (i WebshareArray) ToWebshareArrayOutputWithContext(ctx context.Context) WebshareArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebshareArrayOutput)
}

// WebshareMapInput is an input type that accepts WebshareMap and WebshareMapOutput values.
// You can construct a concrete instance of `WebshareMapInput` via:
//
//	WebshareMap{ "key": WebshareArgs{...} }
type WebshareMapInput interface {
	pulumi.Input

	ToWebshareMapOutput() WebshareMapOutput
	ToWebshareMapOutputWithContext(context.Context) WebshareMapOutput
}

type WebshareMap map[string]WebshareInput

func (WebshareMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Webshare)(nil)).Elem()
}

func (i WebshareMap) ToWebshareMapOutput() WebshareMapOutput {
	return i.ToWebshareMapOutputWithContext(context.Background())
}

func (i WebshareMap) ToWebshareMapOutputWithContext(ctx context.Context) WebshareMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebshareMapOutput)
}

type WebshareOutput struct{ *pulumi.OutputState }

func (WebshareOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Webshare)(nil)).Elem()
}

func (o WebshareOutput) ToWebshareOutput() WebshareOutput {
	return o
}

func (o WebshareOutput) ToWebshareOutputWithContext(ctx context.Context) WebshareOutput {
	return o
}

// Dataset name component of path (e.g. "tank/share"), or null if it cannot be resolved. Probed live: this can read back null immediately after create — see the resource documentation's known-quirks note — even though it settles to a real value on a subsequent read or update.
func (o WebshareOutput) Dataset() pulumi.StringOutput {
	return o.ApplyT(func(v *Webshare) pulumi.StringOutput { return v.Dataset }).(pulumi.StringOutput)
}

// Whether the share is available. Defaults to true (matches the API's own default).
func (o WebshareOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Webshare) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// If set, this share is used as the base path for user home directories. Only one share on the system can have this enabled — setting it here on more than one<span pulumi-lang-nodejs=" truenas.Webshare " pulumi-lang-dotnet=" truenas.Webshare " pulumi-lang-go=" Webshare " pulumi-lang-python=" Webshare " pulumi-lang-yaml=" truenas.Webshare " pulumi-lang-java=" truenas.Webshare " pulumi-lang-hcl=" truenas_webshare "> truenas.Webshare </span>resource, or on a system where another share already has it set outside Terraform, produces undefined API-side behavior. Defaults to false.
func (o WebshareOutput) IsHomeBase() pulumi.BoolOutput {
	return o.ApplyT(func(v *Webshare) pulumi.BoolOutput { return v.IsHomeBase }).(pulumi.BoolOutput)
}

// Whether the share path is currently on a locked (encrypted, unmounted) dataset, or null if lock status is unavailable.
func (o WebshareOutput) Locked() pulumi.BoolOutput {
	return o.ApplyT(func(v *Webshare) pulumi.BoolOutput { return v.Locked }).(pulumi.BoolOutput)
}

// Webshare share name. Mutable: sharing.webshare.update accepts and applies a rename (probed live).
func (o WebshareOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Webshare) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Local server path to share by using the Webshare protocol. Must start with "/mnt/" and be in a ZFS pool (e.g. /mnt/tank/share). Changing it replaces the share (this provider's convention for share paths, mirroring truenas_smb_share/truenas_nfs_share, even though sharing.webshare.update does accept a "path" key).
func (o WebshareOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *Webshare) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

// Relative path component within the dataset (e.g. "subdir/data", or "" when path IS the dataset's own mountpoint), or null if it cannot be resolved. Subject to the same create-time null quirk as "dataset" — see its description.
func (o WebshareOutput) RelativePath() pulumi.StringOutput {
	return o.ApplyT(func(v *Webshare) pulumi.StringOutput { return v.RelativePath }).(pulumi.StringOutput)
}

type WebshareArrayOutput struct{ *pulumi.OutputState }

func (WebshareArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Webshare)(nil)).Elem()
}

func (o WebshareArrayOutput) ToWebshareArrayOutput() WebshareArrayOutput {
	return o
}

func (o WebshareArrayOutput) ToWebshareArrayOutputWithContext(ctx context.Context) WebshareArrayOutput {
	return o
}

func (o WebshareArrayOutput) Index(i pulumi.IntInput) WebshareOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Webshare {
		return vs[0].([]*Webshare)[vs[1].(int)]
	}).(WebshareOutput)
}

type WebshareMapOutput struct{ *pulumi.OutputState }

func (WebshareMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Webshare)(nil)).Elem()
}

func (o WebshareMapOutput) ToWebshareMapOutput() WebshareMapOutput {
	return o
}

func (o WebshareMapOutput) ToWebshareMapOutputWithContext(ctx context.Context) WebshareMapOutput {
	return o
}

func (o WebshareMapOutput) MapIndex(k pulumi.StringInput) WebshareOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Webshare {
		return vs[0].(map[string]*Webshare)[vs[1].(string)]
	}).(WebshareOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WebshareInput)(nil)).Elem(), &Webshare{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebshareArrayInput)(nil)).Elem(), WebshareArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebshareMapInput)(nil)).Elem(), WebshareMap{})
	pulumi.RegisterOutputType(WebshareOutput{})
	pulumi.RegisterOutputType(WebshareArrayOutput{})
	pulumi.RegisterOutputType(WebshareMapOutput{})
}
