// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package truenas

import (
	"context"
	"reflect"

	"errors"
	"github.com/jetersen/pulumi-truenas/sdk/go/truenas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Zvol struct {
	pulumi.CustomResourceState

	// Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, or BLAKE3. Null inherits.
	Checksum pulumi.StringOutput `pulumi:"checksum"`
	// Human-readable description.
	Comments pulumi.StringOutput `pulumi:"comments"`
	// Compression algorithm. Case-insensitive: lz4, zstd, off, inherit, etc.
	Compression pulumi.StringOutput `pulumi:"compression"`
	// Number of copies of each block (1-3). Null (unset) inherits from the parent.
	Copies pulumi.IntOutput `pulumi:"copies"`
	// Deduplication: ON, VERIFY, or OFF. INHERIT inherits from the parent.
	Dedup pulumi.StringOutput `pulumi:"dedup"`
	// Whether the zvol is encrypted.
	Encrypted pulumi.BoolOutput `pulumi:"encrypted"`
	// Enable ZFS encryption on this zvol at creation. Create-only: changing it recreates the zvol. Cannot be combined with<span pulumi-lang-nodejs=" inheritEncryption " pulumi-lang-dotnet=" InheritEncryption " pulumi-lang-go=" inheritEncryption " pulumi-lang-python=" inherit_encryption " pulumi-lang-yaml=" inheritEncryption " pulumi-lang-java=" inheritEncryption " pulumi-lang-hcl=" inherit_encryption "> inheritEncryption </span>= true (the parent determines encryption).
	Encryption pulumi.BoolOutput `pulumi:"encryption"`
	// Encryption algorithm, e.g. "AES-256-GCM". Create-only.
	EncryptionAlgorithm pulumi.StringOutput `pulumi:"encryptionAlgorithm"`
	// Automatically generate the encryption key (key-based encryption). Create-only.
	EncryptionGenerateKey pulumi.BoolPtrOutput `pulumi:"encryptionGenerateKey"`
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// 64-character hex key for key-based encryption. Write-only: never stored in state. Create-only.
	EncryptionKey pulumi.StringPtrOutput `pulumi:"encryptionKey"`
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Passphrase for passphrase-based encryption (minimum 8 characters). Write-only: never stored in state. Create-only.
	EncryptionPassphrase pulumi.StringPtrOutput `pulumi:"encryptionPassphrase"`
	// Whether this zvol inherits its encryption from the parent dataset rather than owning its own key. Create-only. Computed: reconciled from the zvol's encryption root on read, so it reflects reality even when left unset.
	InheritEncryption pulumi.BoolOutput `pulumi:"inheritEncryption"`
	// Encryption key format: PASSPHRASE or HEX (null when not encrypted).
	KeyFormat pulumi.StringOutput `pulumi:"keyFormat"`
	// Whether the encrypted zvol is currently locked.
	Locked pulumi.BoolOutput `pulumi:"locked"`
	// Full zvol path, e.g. tank/myvol.
	Name pulumi.StringOutput `pulumi:"name"`
	// Name of the pool containing this zvol.
	Pool pulumi.StringOutput `pulumi:"pool"`
	// Mount read-only: ON or OFF. Null inherits.
	Readonly pulumi.StringOutput `pulumi:"readonly"`
	// Referenced reservation in bytes (space guaranteed to the volume, excluding snapshots). Null (unset) inherits.
	Refreservation pulumi.IntOutput `pulumi:"refreservation"`
	// Reserved space in bytes (guaranteed to this volume including snapshots). Null (unset) inherits.
	Reservation pulumi.IntOutput `pulumi:"reservation"`
	// Visibility of the volume's snapshot device nodes: VISIBLE or HIDDEN. Null inherits.
	Snapdev pulumi.StringOutput `pulumi:"snapdev"`
	// Sparse provisioning (write-only; not returned by API).
	Sparse pulumi.BoolPtrOutput `pulumi:"sparse"`
	// Sync write behaviour: STANDARD, ALWAYS, or DISABLED. INHERIT inherits from the parent.
	Sync pulumi.StringOutput `pulumi:"sync"`
	// Block size in bytes (512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072). Set at create time only.
	Volblocksize pulumi.IntOutput `pulumi:"volblocksize"`
	// Volume size in bytes.
	Volsize pulumi.IntOutput `pulumi:"volsize"`
}

// NewZvol registers a new resource with the given unique name, arguments, and options.
func NewZvol(ctx *pulumi.Context,
	name string, args *ZvolArgs, opts ...pulumi.ResourceOption) (*Zvol, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Volsize == nil {
		return nil, errors.New("invalid value for required argument 'Volsize'")
	}
	if args.EncryptionKey != nil {
		args.EncryptionKey = pulumi.ToSecret(args.EncryptionKey).(pulumi.StringPtrInput)
	}
	if args.EncryptionPassphrase != nil {
		args.EncryptionPassphrase = pulumi.ToSecret(args.EncryptionPassphrase).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"encryptionKey",
		"encryptionPassphrase",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Zvol
	err := ctx.RegisterResource("truenas:index/zvol:Zvol", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetZvol gets an existing Zvol resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetZvol(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ZvolState, opts ...pulumi.ResourceOption) (*Zvol, error) {
	var resource Zvol
	err := ctx.ReadResource("truenas:index/zvol:Zvol", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Zvol resources.
type zvolState struct {
	// Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, or BLAKE3. Null inherits.
	Checksum *string `pulumi:"checksum"`
	// Human-readable description.
	Comments *string `pulumi:"comments"`
	// Compression algorithm. Case-insensitive: lz4, zstd, off, inherit, etc.
	Compression *string `pulumi:"compression"`
	// Number of copies of each block (1-3). Null (unset) inherits from the parent.
	Copies *int `pulumi:"copies"`
	// Deduplication: ON, VERIFY, or OFF. INHERIT inherits from the parent.
	Dedup *string `pulumi:"dedup"`
	// Whether the zvol is encrypted.
	Encrypted *bool `pulumi:"encrypted"`
	// Enable ZFS encryption on this zvol at creation. Create-only: changing it recreates the zvol. Cannot be combined with<span pulumi-lang-nodejs=" inheritEncryption " pulumi-lang-dotnet=" InheritEncryption " pulumi-lang-go=" inheritEncryption " pulumi-lang-python=" inherit_encryption " pulumi-lang-yaml=" inheritEncryption " pulumi-lang-java=" inheritEncryption " pulumi-lang-hcl=" inherit_encryption "> inheritEncryption </span>= true (the parent determines encryption).
	Encryption *bool `pulumi:"encryption"`
	// Encryption algorithm, e.g. "AES-256-GCM". Create-only.
	EncryptionAlgorithm *string `pulumi:"encryptionAlgorithm"`
	// Automatically generate the encryption key (key-based encryption). Create-only.
	EncryptionGenerateKey *bool `pulumi:"encryptionGenerateKey"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// 64-character hex key for key-based encryption. Write-only: never stored in state. Create-only.
	EncryptionKey *string `pulumi:"encryptionKey"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Passphrase for passphrase-based encryption (minimum 8 characters). Write-only: never stored in state. Create-only.
	EncryptionPassphrase *string `pulumi:"encryptionPassphrase"`
	// Whether this zvol inherits its encryption from the parent dataset rather than owning its own key. Create-only. Computed: reconciled from the zvol's encryption root on read, so it reflects reality even when left unset.
	InheritEncryption *bool `pulumi:"inheritEncryption"`
	// Encryption key format: PASSPHRASE or HEX (null when not encrypted).
	KeyFormat *string `pulumi:"keyFormat"`
	// Whether the encrypted zvol is currently locked.
	Locked *bool `pulumi:"locked"`
	// Full zvol path, e.g. tank/myvol.
	Name *string `pulumi:"name"`
	// Name of the pool containing this zvol.
	Pool *string `pulumi:"pool"`
	// Mount read-only: ON or OFF. Null inherits.
	Readonly *string `pulumi:"readonly"`
	// Referenced reservation in bytes (space guaranteed to the volume, excluding snapshots). Null (unset) inherits.
	Refreservation *int `pulumi:"refreservation"`
	// Reserved space in bytes (guaranteed to this volume including snapshots). Null (unset) inherits.
	Reservation *int `pulumi:"reservation"`
	// Visibility of the volume's snapshot device nodes: VISIBLE or HIDDEN. Null inherits.
	Snapdev *string `pulumi:"snapdev"`
	// Sparse provisioning (write-only; not returned by API).
	Sparse *bool `pulumi:"sparse"`
	// Sync write behaviour: STANDARD, ALWAYS, or DISABLED. INHERIT inherits from the parent.
	Sync *string `pulumi:"sync"`
	// Block size in bytes (512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072). Set at create time only.
	Volblocksize *int `pulumi:"volblocksize"`
	// Volume size in bytes.
	Volsize *int `pulumi:"volsize"`
}

type ZvolState struct {
	// Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, or BLAKE3. Null inherits.
	Checksum pulumi.StringPtrInput
	// Human-readable description.
	Comments pulumi.StringPtrInput
	// Compression algorithm. Case-insensitive: lz4, zstd, off, inherit, etc.
	Compression pulumi.StringPtrInput
	// Number of copies of each block (1-3). Null (unset) inherits from the parent.
	Copies pulumi.IntPtrInput
	// Deduplication: ON, VERIFY, or OFF. INHERIT inherits from the parent.
	Dedup pulumi.StringPtrInput
	// Whether the zvol is encrypted.
	Encrypted pulumi.BoolPtrInput
	// Enable ZFS encryption on this zvol at creation. Create-only: changing it recreates the zvol. Cannot be combined with<span pulumi-lang-nodejs=" inheritEncryption " pulumi-lang-dotnet=" InheritEncryption " pulumi-lang-go=" inheritEncryption " pulumi-lang-python=" inherit_encryption " pulumi-lang-yaml=" inheritEncryption " pulumi-lang-java=" inheritEncryption " pulumi-lang-hcl=" inherit_encryption "> inheritEncryption </span>= true (the parent determines encryption).
	Encryption pulumi.BoolPtrInput
	// Encryption algorithm, e.g. "AES-256-GCM". Create-only.
	EncryptionAlgorithm pulumi.StringPtrInput
	// Automatically generate the encryption key (key-based encryption). Create-only.
	EncryptionGenerateKey pulumi.BoolPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// 64-character hex key for key-based encryption. Write-only: never stored in state. Create-only.
	EncryptionKey pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Passphrase for passphrase-based encryption (minimum 8 characters). Write-only: never stored in state. Create-only.
	EncryptionPassphrase pulumi.StringPtrInput
	// Whether this zvol inherits its encryption from the parent dataset rather than owning its own key. Create-only. Computed: reconciled from the zvol's encryption root on read, so it reflects reality even when left unset.
	InheritEncryption pulumi.BoolPtrInput
	// Encryption key format: PASSPHRASE or HEX (null when not encrypted).
	KeyFormat pulumi.StringPtrInput
	// Whether the encrypted zvol is currently locked.
	Locked pulumi.BoolPtrInput
	// Full zvol path, e.g. tank/myvol.
	Name pulumi.StringPtrInput
	// Name of the pool containing this zvol.
	Pool pulumi.StringPtrInput
	// Mount read-only: ON or OFF. Null inherits.
	Readonly pulumi.StringPtrInput
	// Referenced reservation in bytes (space guaranteed to the volume, excluding snapshots). Null (unset) inherits.
	Refreservation pulumi.IntPtrInput
	// Reserved space in bytes (guaranteed to this volume including snapshots). Null (unset) inherits.
	Reservation pulumi.IntPtrInput
	// Visibility of the volume's snapshot device nodes: VISIBLE or HIDDEN. Null inherits.
	Snapdev pulumi.StringPtrInput
	// Sparse provisioning (write-only; not returned by API).
	Sparse pulumi.BoolPtrInput
	// Sync write behaviour: STANDARD, ALWAYS, or DISABLED. INHERIT inherits from the parent.
	Sync pulumi.StringPtrInput
	// Block size in bytes (512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072). Set at create time only.
	Volblocksize pulumi.IntPtrInput
	// Volume size in bytes.
	Volsize pulumi.IntPtrInput
}

func (ZvolState) ElementType() reflect.Type {
	return reflect.TypeOf((*zvolState)(nil)).Elem()
}

type zvolArgs struct {
	// Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, or BLAKE3. Null inherits.
	Checksum *string `pulumi:"checksum"`
	// Human-readable description.
	Comments *string `pulumi:"comments"`
	// Compression algorithm. Case-insensitive: lz4, zstd, off, inherit, etc.
	Compression *string `pulumi:"compression"`
	// Number of copies of each block (1-3). Null (unset) inherits from the parent.
	Copies *int `pulumi:"copies"`
	// Deduplication: ON, VERIFY, or OFF. INHERIT inherits from the parent.
	Dedup *string `pulumi:"dedup"`
	// Enable ZFS encryption on this zvol at creation. Create-only: changing it recreates the zvol. Cannot be combined with<span pulumi-lang-nodejs=" inheritEncryption " pulumi-lang-dotnet=" InheritEncryption " pulumi-lang-go=" inheritEncryption " pulumi-lang-python=" inherit_encryption " pulumi-lang-yaml=" inheritEncryption " pulumi-lang-java=" inheritEncryption " pulumi-lang-hcl=" inherit_encryption "> inheritEncryption </span>= true (the parent determines encryption).
	Encryption *bool `pulumi:"encryption"`
	// Encryption algorithm, e.g. "AES-256-GCM". Create-only.
	EncryptionAlgorithm *string `pulumi:"encryptionAlgorithm"`
	// Automatically generate the encryption key (key-based encryption). Create-only.
	EncryptionGenerateKey *bool `pulumi:"encryptionGenerateKey"`
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// 64-character hex key for key-based encryption. Write-only: never stored in state. Create-only.
	EncryptionKey *string `pulumi:"encryptionKey"`
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Passphrase for passphrase-based encryption (minimum 8 characters). Write-only: never stored in state. Create-only.
	EncryptionPassphrase *string `pulumi:"encryptionPassphrase"`
	// Whether this zvol inherits its encryption from the parent dataset rather than owning its own key. Create-only. Computed: reconciled from the zvol's encryption root on read, so it reflects reality even when left unset.
	InheritEncryption *bool `pulumi:"inheritEncryption"`
	// Full zvol path, e.g. tank/myvol.
	Name string `pulumi:"name"`
	// Mount read-only: ON or OFF. Null inherits.
	Readonly *string `pulumi:"readonly"`
	// Referenced reservation in bytes (space guaranteed to the volume, excluding snapshots). Null (unset) inherits.
	Refreservation *int `pulumi:"refreservation"`
	// Reserved space in bytes (guaranteed to this volume including snapshots). Null (unset) inherits.
	Reservation *int `pulumi:"reservation"`
	// Visibility of the volume's snapshot device nodes: VISIBLE or HIDDEN. Null inherits.
	Snapdev *string `pulumi:"snapdev"`
	// Sparse provisioning (write-only; not returned by API).
	Sparse *bool `pulumi:"sparse"`
	// Sync write behaviour: STANDARD, ALWAYS, or DISABLED. INHERIT inherits from the parent.
	Sync *string `pulumi:"sync"`
	// Block size in bytes (512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072). Set at create time only.
	Volblocksize *int `pulumi:"volblocksize"`
	// Volume size in bytes.
	Volsize int `pulumi:"volsize"`
}

// The set of arguments for constructing a Zvol resource.
type ZvolArgs struct {
	// Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, or BLAKE3. Null inherits.
	Checksum pulumi.StringPtrInput
	// Human-readable description.
	Comments pulumi.StringPtrInput
	// Compression algorithm. Case-insensitive: lz4, zstd, off, inherit, etc.
	Compression pulumi.StringPtrInput
	// Number of copies of each block (1-3). Null (unset) inherits from the parent.
	Copies pulumi.IntPtrInput
	// Deduplication: ON, VERIFY, or OFF. INHERIT inherits from the parent.
	Dedup pulumi.StringPtrInput
	// Enable ZFS encryption on this zvol at creation. Create-only: changing it recreates the zvol. Cannot be combined with<span pulumi-lang-nodejs=" inheritEncryption " pulumi-lang-dotnet=" InheritEncryption " pulumi-lang-go=" inheritEncryption " pulumi-lang-python=" inherit_encryption " pulumi-lang-yaml=" inheritEncryption " pulumi-lang-java=" inheritEncryption " pulumi-lang-hcl=" inherit_encryption "> inheritEncryption </span>= true (the parent determines encryption).
	Encryption pulumi.BoolPtrInput
	// Encryption algorithm, e.g. "AES-256-GCM". Create-only.
	EncryptionAlgorithm pulumi.StringPtrInput
	// Automatically generate the encryption key (key-based encryption). Create-only.
	EncryptionGenerateKey pulumi.BoolPtrInput
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// 64-character hex key for key-based encryption. Write-only: never stored in state. Create-only.
	EncryptionKey pulumi.StringPtrInput
	// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
	//
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Passphrase for passphrase-based encryption (minimum 8 characters). Write-only: never stored in state. Create-only.
	EncryptionPassphrase pulumi.StringPtrInput
	// Whether this zvol inherits its encryption from the parent dataset rather than owning its own key. Create-only. Computed: reconciled from the zvol's encryption root on read, so it reflects reality even when left unset.
	InheritEncryption pulumi.BoolPtrInput
	// Full zvol path, e.g. tank/myvol.
	Name pulumi.StringInput
	// Mount read-only: ON or OFF. Null inherits.
	Readonly pulumi.StringPtrInput
	// Referenced reservation in bytes (space guaranteed to the volume, excluding snapshots). Null (unset) inherits.
	Refreservation pulumi.IntPtrInput
	// Reserved space in bytes (guaranteed to this volume including snapshots). Null (unset) inherits.
	Reservation pulumi.IntPtrInput
	// Visibility of the volume's snapshot device nodes: VISIBLE or HIDDEN. Null inherits.
	Snapdev pulumi.StringPtrInput
	// Sparse provisioning (write-only; not returned by API).
	Sparse pulumi.BoolPtrInput
	// Sync write behaviour: STANDARD, ALWAYS, or DISABLED. INHERIT inherits from the parent.
	Sync pulumi.StringPtrInput
	// Block size in bytes (512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072). Set at create time only.
	Volblocksize pulumi.IntPtrInput
	// Volume size in bytes.
	Volsize pulumi.IntInput
}

func (ZvolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*zvolArgs)(nil)).Elem()
}

type ZvolInput interface {
	pulumi.Input

	ToZvolOutput() ZvolOutput
	ToZvolOutputWithContext(ctx context.Context) ZvolOutput
}

func (*Zvol) ElementType() reflect.Type {
	return reflect.TypeOf((**Zvol)(nil)).Elem()
}

func (i *Zvol) ToZvolOutput() ZvolOutput {
	return i.ToZvolOutputWithContext(context.Background())
}

func (i *Zvol) ToZvolOutputWithContext(ctx context.Context) ZvolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZvolOutput)
}

// ZvolArrayInput is an input type that accepts ZvolArray and ZvolArrayOutput values.
// You can construct a concrete instance of `ZvolArrayInput` via:
//
//	ZvolArray{ ZvolArgs{...} }
type ZvolArrayInput interface {
	pulumi.Input

	ToZvolArrayOutput() ZvolArrayOutput
	ToZvolArrayOutputWithContext(context.Context) ZvolArrayOutput
}

type ZvolArray []ZvolInput

func (ZvolArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Zvol)(nil)).Elem()
}

func (i ZvolArray) ToZvolArrayOutput() ZvolArrayOutput {
	return i.ToZvolArrayOutputWithContext(context.Background())
}

func (i ZvolArray) ToZvolArrayOutputWithContext(ctx context.Context) ZvolArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZvolArrayOutput)
}

// ZvolMapInput is an input type that accepts ZvolMap and ZvolMapOutput values.
// You can construct a concrete instance of `ZvolMapInput` via:
//
//	ZvolMap{ "key": ZvolArgs{...} }
type ZvolMapInput interface {
	pulumi.Input

	ToZvolMapOutput() ZvolMapOutput
	ToZvolMapOutputWithContext(context.Context) ZvolMapOutput
}

type ZvolMap map[string]ZvolInput

func (ZvolMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Zvol)(nil)).Elem()
}

func (i ZvolMap) ToZvolMapOutput() ZvolMapOutput {
	return i.ToZvolMapOutputWithContext(context.Background())
}

func (i ZvolMap) ToZvolMapOutputWithContext(ctx context.Context) ZvolMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ZvolMapOutput)
}

type ZvolOutput struct{ *pulumi.OutputState }

func (ZvolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Zvol)(nil)).Elem()
}

func (o ZvolOutput) ToZvolOutput() ZvolOutput {
	return o
}

func (o ZvolOutput) ToZvolOutputWithContext(ctx context.Context) ZvolOutput {
	return o
}

// Checksum algorithm: ON, OFF, FLETCHER2, FLETCHER4, SHA256, SHA512, SKEIN, EDONR, or BLAKE3. Null inherits.
func (o ZvolOutput) Checksum() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Checksum }).(pulumi.StringOutput)
}

// Human-readable description.
func (o ZvolOutput) Comments() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Comments }).(pulumi.StringOutput)
}

// Compression algorithm. Case-insensitive: lz4, zstd, off, inherit, etc.
func (o ZvolOutput) Compression() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Compression }).(pulumi.StringOutput)
}

// Number of copies of each block (1-3). Null (unset) inherits from the parent.
func (o ZvolOutput) Copies() pulumi.IntOutput {
	return o.ApplyT(func(v *Zvol) pulumi.IntOutput { return v.Copies }).(pulumi.IntOutput)
}

// Deduplication: ON, VERIFY, or OFF. INHERIT inherits from the parent.
func (o ZvolOutput) Dedup() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Dedup }).(pulumi.StringOutput)
}

// Whether the zvol is encrypted.
func (o ZvolOutput) Encrypted() pulumi.BoolOutput {
	return o.ApplyT(func(v *Zvol) pulumi.BoolOutput { return v.Encrypted }).(pulumi.BoolOutput)
}

// Enable ZFS encryption on this zvol at creation. Create-only: changing it recreates the zvol. Cannot be combined with<span pulumi-lang-nodejs=" inheritEncryption " pulumi-lang-dotnet=" InheritEncryption " pulumi-lang-go=" inheritEncryption " pulumi-lang-python=" inherit_encryption " pulumi-lang-yaml=" inheritEncryption " pulumi-lang-java=" inheritEncryption " pulumi-lang-hcl=" inherit_encryption "> inheritEncryption </span>= true (the parent determines encryption).
func (o ZvolOutput) Encryption() pulumi.BoolOutput {
	return o.ApplyT(func(v *Zvol) pulumi.BoolOutput { return v.Encryption }).(pulumi.BoolOutput)
}

// Encryption algorithm, e.g. "AES-256-GCM". Create-only.
func (o ZvolOutput) EncryptionAlgorithm() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.EncryptionAlgorithm }).(pulumi.StringOutput)
}

// Automatically generate the encryption key (key-based encryption). Create-only.
func (o ZvolOutput) EncryptionGenerateKey() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Zvol) pulumi.BoolPtrOutput { return v.EncryptionGenerateKey }).(pulumi.BoolPtrOutput)
}

// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
//
// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// 64-character hex key for key-based encryption. Write-only: never stored in state. Create-only.
func (o ZvolOutput) EncryptionKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringPtrOutput { return v.EncryptionKey }).(pulumi.StringPtrOutput)
}

// Pulumi stores this input encrypted in state. Upstream statements below about never storing it apply to Terraform, not Pulumi.
//
// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Passphrase for passphrase-based encryption (minimum 8 characters). Write-only: never stored in state. Create-only.
func (o ZvolOutput) EncryptionPassphrase() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringPtrOutput { return v.EncryptionPassphrase }).(pulumi.StringPtrOutput)
}

// Whether this zvol inherits its encryption from the parent dataset rather than owning its own key. Create-only. Computed: reconciled from the zvol's encryption root on read, so it reflects reality even when left unset.
func (o ZvolOutput) InheritEncryption() pulumi.BoolOutput {
	return o.ApplyT(func(v *Zvol) pulumi.BoolOutput { return v.InheritEncryption }).(pulumi.BoolOutput)
}

// Encryption key format: PASSPHRASE or HEX (null when not encrypted).
func (o ZvolOutput) KeyFormat() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.KeyFormat }).(pulumi.StringOutput)
}

// Whether the encrypted zvol is currently locked.
func (o ZvolOutput) Locked() pulumi.BoolOutput {
	return o.ApplyT(func(v *Zvol) pulumi.BoolOutput { return v.Locked }).(pulumi.BoolOutput)
}

// Full zvol path, e.g. tank/myvol.
func (o ZvolOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Name of the pool containing this zvol.
func (o ZvolOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Pool }).(pulumi.StringOutput)
}

// Mount read-only: ON or OFF. Null inherits.
func (o ZvolOutput) Readonly() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Readonly }).(pulumi.StringOutput)
}

// Referenced reservation in bytes (space guaranteed to the volume, excluding snapshots). Null (unset) inherits.
func (o ZvolOutput) Refreservation() pulumi.IntOutput {
	return o.ApplyT(func(v *Zvol) pulumi.IntOutput { return v.Refreservation }).(pulumi.IntOutput)
}

// Reserved space in bytes (guaranteed to this volume including snapshots). Null (unset) inherits.
func (o ZvolOutput) Reservation() pulumi.IntOutput {
	return o.ApplyT(func(v *Zvol) pulumi.IntOutput { return v.Reservation }).(pulumi.IntOutput)
}

// Visibility of the volume's snapshot device nodes: VISIBLE or HIDDEN. Null inherits.
func (o ZvolOutput) Snapdev() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Snapdev }).(pulumi.StringOutput)
}

// Sparse provisioning (write-only; not returned by API).
func (o ZvolOutput) Sparse() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Zvol) pulumi.BoolPtrOutput { return v.Sparse }).(pulumi.BoolPtrOutput)
}

// Sync write behaviour: STANDARD, ALWAYS, or DISABLED. INHERIT inherits from the parent.
func (o ZvolOutput) Sync() pulumi.StringOutput {
	return o.ApplyT(func(v *Zvol) pulumi.StringOutput { return v.Sync }).(pulumi.StringOutput)
}

// Block size in bytes (512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072). Set at create time only.
func (o ZvolOutput) Volblocksize() pulumi.IntOutput {
	return o.ApplyT(func(v *Zvol) pulumi.IntOutput { return v.Volblocksize }).(pulumi.IntOutput)
}

// Volume size in bytes.
func (o ZvolOutput) Volsize() pulumi.IntOutput {
	return o.ApplyT(func(v *Zvol) pulumi.IntOutput { return v.Volsize }).(pulumi.IntOutput)
}

type ZvolArrayOutput struct{ *pulumi.OutputState }

func (ZvolArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Zvol)(nil)).Elem()
}

func (o ZvolArrayOutput) ToZvolArrayOutput() ZvolArrayOutput {
	return o
}

func (o ZvolArrayOutput) ToZvolArrayOutputWithContext(ctx context.Context) ZvolArrayOutput {
	return o
}

func (o ZvolArrayOutput) Index(i pulumi.IntInput) ZvolOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Zvol {
		return vs[0].([]*Zvol)[vs[1].(int)]
	}).(ZvolOutput)
}

type ZvolMapOutput struct{ *pulumi.OutputState }

func (ZvolMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Zvol)(nil)).Elem()
}

func (o ZvolMapOutput) ToZvolMapOutput() ZvolMapOutput {
	return o
}

func (o ZvolMapOutput) ToZvolMapOutputWithContext(ctx context.Context) ZvolMapOutput {
	return o
}

func (o ZvolMapOutput) MapIndex(k pulumi.StringInput) ZvolOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Zvol {
		return vs[0].(map[string]*Zvol)[vs[1].(string)]
	}).(ZvolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ZvolInput)(nil)).Elem(), &Zvol{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZvolArrayInput)(nil)).Elem(), ZvolArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ZvolMapInput)(nil)).Elem(), ZvolMap{})
	pulumi.RegisterOutputType(ZvolOutput{})
	pulumi.RegisterOutputType(ZvolArrayOutput{})
	pulumi.RegisterOutputType(ZvolMapOutput{})
}
